/**
 * @fileoverview Legacy oxigraph facade
 * Generated by Agent 8 - Domain Kit Generator
 */

import { createSubstrate } from '../../substrate/oxigraph-substrate.mjs';

/**
 * Legacy oxigraph facade
 * Wraps substrate and exposes legacy API
 */
class OxigraphFacade {
  constructor(config = {}) {
    this.substrate = createSubstrate(config);
    this.config = config;
  }

  /**
   * Create RDF store instance
   * @param {Object} config - Store configuration
   * @returns {Store} Store instance
   */
  async createStore(config) {
    // Adapt legacy params to substrate format
    const substrateInput = {
      config
    };

    // Execute on substrate
    const result = await this.substrate.execute('createStore', substrateInput);

    // Adapt substrate result to legacy format
    return result;
  }

  /**
   * Add quad to store
   * @param {Store} store - Store instance
   * @param {Quad} quad - Quad to add
   * @returns {boolean} Success flag
   */
  async addQuad(store, quad) {
    // Adapt legacy params to substrate format
    const substrateInput = {
      store,
      quad
    };

    // Execute on substrate
    const result = await this.substrate.execute('addQuad', substrateInput);

    // Adapt substrate result to legacy format
    return result;
  }

  /**
   * Execute SPARQL query
   * @param {Store} store - Store instance
   * @param {string} sparql - SPARQL query
   * @returns {Array} Query results
   */
  async query(store, sparql) {
    // Adapt legacy params to substrate format
    const substrateInput = {
      store,
      sparql
    };

    // Execute on substrate
    const result = await this.substrate.execute('query', substrateInput);

    // Adapt substrate result to legacy format
    return result;
  }
}


/**
 * Create oxigraph facade instance
 *
 * @param {Object} config - Configuration
 * @returns {OxigraphFacade} Facade instance
 */
export function createOxigraphFacade(config = {}) {
  return new OxigraphFacade(config);
}

export default OxigraphFacade;
