/**
 * Auto-generated Zod schemas for andon-signals.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for computeSignalState
 */
export const computeSignalStateParamsSchema = z.tuple([z.number(), z.unknown().optional(), z.unknown()]);

export const computeSignalStateReturnSchema = z.unknown();

export const computeSignalStateSchema = {
  params: computeSignalStateParamsSchema,
  returns: computeSignalStateReturnSchema,
};

/**
 * Schema for getStatePriority
 */
export const getStatePriorityParamsSchema = z.tuple([z.unknown()]);

export const getStatePriorityReturnSchema = z.number();

export const getStatePrioritySchema = {
  params: getStatePriorityParamsSchema,
  returns: getStatePriorityReturnSchema,
};

/**
 * Schema for getWorstState
 */
export const getWorstStateParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const getWorstStateReturnSchema = z.unknown();

export const getWorstStateSchema = {
  params: getWorstStateParamsSchema,
  returns: getWorstStateReturnSchema,
};

/**
 * Schema for createAndonSignalManager
 */
export const createAndonSignalManagerParamsSchema = z.tuple([z.unknown().optional()]);

export const createAndonSignalManagerReturnSchema = z.unknown();

export const createAndonSignalManagerSchema = {
  params: createAndonSignalManagerParamsSchema,
  returns: createAndonSignalManagerReturnSchema,
};

export default {
  computeSignalState: computeSignalStateSchema,
  getStatePriority: getStatePrioritySchema,
  getWorstState: getWorstStateSchema,
  createAndonSignalManager: createAndonSignalManagerSchema
};
