/**
 * Auto-generated Zod schemas for n3-justified-only.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for streamingParse
 */
export const streamingParseParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const streamingParseReturnSchema = z.unknown();

export const streamingParseSchema = {
  params: streamingParseParamsSchema,
  returns: streamingParseReturnSchema,
};

/**
 * Schema for streamingWrite
 */
export const streamingWriteParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const streamingWriteReturnSchema = z.unknown();

export const streamingWriteSchema = {
  params: streamingWriteParamsSchema,
  returns: streamingWriteReturnSchema,
};

/**
 * Schema for createStreamParser
 */
export const createStreamParserParamsSchema = z.tuple([z.unknown().optional()]);

export const createStreamParserReturnSchema = z.unknown();

export const createStreamParserSchema = {
  params: createStreamParserParamsSchema,
  returns: createStreamParserReturnSchema,
};

/**
 * Schema for createStreamWriter
 */
export const createStreamWriterParamsSchema = z.tuple([z.unknown().optional()]);

export const createStreamWriterReturnSchema = z.unknown();

export const createStreamWriterSchema = {
  params: createStreamWriterParamsSchema,
  returns: createStreamWriterReturnSchema,
};

export default {
  streamingParse: streamingParseSchema,
  streamingWrite: streamingWriteSchema,
  createStreamParser: createStreamParserSchema,
  createStreamWriter: createStreamWriterSchema
};
