/**
 * Auto-generated Zod schemas for n3-migration.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for isN3Store
 */
export const isN3StoreParamsSchema = z.tuple([z.any()]);

export const isN3StoreReturnSchema = z.boolean();

export const isN3StoreSchema = {
  params: isN3StoreParamsSchema,
  returns: isN3StoreReturnSchema,
};

/**
 * Schema for convertN3ToOxigraph
 */
export const convertN3ToOxigraphParamsSchema = z.tuple([z.unknown()]);

export const convertN3ToOxigraphReturnSchema = z.unknown();

export const convertN3ToOxigraphSchema = {
  params: convertN3ToOxigraphParamsSchema,
  returns: convertN3ToOxigraphReturnSchema,
};

/**
 * Schema for ensureOxigraphStore
 */
export const ensureOxigraphStoreParamsSchema = z.tuple([z.any()]);

export const ensureOxigraphStoreReturnSchema = z.unknown();

export const ensureOxigraphStoreSchema = {
  params: ensureOxigraphStoreParamsSchema,
  returns: ensureOxigraphStoreReturnSchema,
};

/**
 * Schema for createN3Store
 */
export const createN3StoreParamsSchema = z.tuple([]);

export const createN3StoreReturnSchema = z.unknown();

export const createN3StoreSchema = {
  params: createN3StoreParamsSchema,
  returns: createN3StoreReturnSchema,
};

export default {
  isN3Store: isN3StoreSchema,
  convertN3ToOxigraph: convertN3ToOxigraphSchema,
  ensureOxigraphStore: ensureOxigraphStoreSchema,
  createN3Store: createN3StoreSchema
};
