/**
 * Auto-generated Zod schemas for store.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createStore
 */
export const createStoreParamsSchema = z.tuple([]);

export const createStoreReturnSchema = z.unknown();

export const createStoreSchema = {
  params: createStoreParamsSchema,
  returns: createStoreReturnSchema,
};

/**
 * Schema for addQuad
 */
export const addQuadParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const addQuadReturnSchema = z.void();

export const addQuadSchema = {
  params: addQuadParamsSchema,
  returns: addQuadReturnSchema,
};

/**
 * Schema for removeQuad
 */
export const removeQuadParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const removeQuadReturnSchema = z.void();

export const removeQuadSchema = {
  params: removeQuadParamsSchema,
  returns: removeQuadReturnSchema,
};

/**
 * Schema for getQuads
 */
export const getQuadsParamsSchema = z.tuple([z.unknown(), z.unknown().optional(), z.unknown().optional(), z.unknown().optional(), z.unknown().optional()]);

export const getQuadsReturnSchema = z.unknown();

export const getQuadsSchema = {
  params: getQuadsParamsSchema,
  returns: getQuadsReturnSchema,
};

export default {
  createStore: createStoreSchema,
  addQuad: addQuadSchema,
  removeQuad: removeQuadSchema,
  getQuads: getQuadsSchema
};
