/**
 * Auto-generated Zod schemas for unrdf-store.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createStore
 */
export const createStoreParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const createStoreReturnSchema = z.unknown();

export const createStoreSchema = {
  params: createStoreParamsSchema,
  returns: createStoreReturnSchema,
};

export default {
  createStore: createStoreSchema
};
