/**
 * Auto-generated Zod schemas for critical-path.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createCriticalPathIdentifier
 */
export const createCriticalPathIdentifierParamsSchema = z.tuple([z.unknown().optional()]);

export const createCriticalPathIdentifierReturnSchema = z.unknown();

export const createCriticalPathIdentifierSchema = {
  params: createCriticalPathIdentifierParamsSchema,
  returns: createCriticalPathIdentifierReturnSchema,
};

export default {
  createCriticalPathIdentifier: createCriticalPathIdentifierSchema
};
