/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createDarkMatterQuerySystem
 */
export const createDarkMatterQuerySystemParamsSchema = z.tuple([z.unknown().optional()]);

export const createDarkMatterQuerySystemReturnSchema = z.unknown();

export const createDarkMatterQuerySystemSchema = {
  params: createDarkMatterQuerySystemParamsSchema,
  returns: createDarkMatterQuerySystemReturnSchema,
};

export default {
  createDarkMatterQuerySystem: createDarkMatterQuerySystemSchema
};
