/**
 * Auto-generated Zod schemas for optimizer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createDarkMatterOptimizer
 */
export const createDarkMatterOptimizerParamsSchema = z.tuple([z.unknown().optional()]);

export const createDarkMatterOptimizerReturnSchema = z.unknown();

export const createDarkMatterOptimizerSchema = {
  params: createDarkMatterOptimizerParamsSchema,
  returns: createDarkMatterOptimizerReturnSchema,
};

export default {
  createDarkMatterOptimizer: createDarkMatterOptimizerSchema
};
