/**
 * Auto-generated Zod schemas for query-analyzer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createQueryAnalyzer
 */
export const createQueryAnalyzerParamsSchema = z.tuple([z.unknown().optional()]);

export const createQueryAnalyzerReturnSchema = z.unknown();

export const createQueryAnalyzerSchema = {
  params: createQueryAnalyzerParamsSchema,
  returns: createQueryAnalyzerReturnSchema,
};

export default {
  createQueryAnalyzer: createQueryAnalyzerSchema
};
