[book]
title = "Knowledge Geometry Calculus: From Field Theory to the Autonomic Enterprise"
authors = ["GitVan Team"]
description = "A mathematical framework for autonomic knowledge graph systems that transforms static RDF into self-governing, reactive, and cryptographically verifiable substrates"
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = true

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/gitvan/unrdf"
git-repository-icon = "fa-github"
site-url = "/books/kgc-thesis/"
preferred-dark-theme = "ayu"
default-theme = "light"

[output.html.search]
enable = true
limit-results = 30
