/**
 * Auto-generated Zod schemas for useBatchOperations.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useBatchOperations
 */
export const useBatchOperationsParamsSchema = z.tuple([]);

export const useBatchOperationsReturnSchema = z.unknown();

export const useBatchOperationsSchema = {
  params: useBatchOperationsParamsSchema,
  returns: useBatchOperationsReturnSchema,
};

export default {
  useBatchOperations: useBatchOperationsSchema
};
