/**
 * Auto-generated Zod schemas for useOptimizedBatch.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useOptimizedBatch
 */
export const useOptimizedBatchParamsSchema = z.tuple([]);

export const useOptimizedBatchReturnSchema = z.unknown();

export const useOptimizedBatchSchema = {
  params: useOptimizedBatchParamsSchema,
  returns: useOptimizedBatchReturnSchema,
};

export default {
  useOptimizedBatch: useOptimizedBatchSchema
};
