/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateQuad
 */
export const validateQuadParamsSchema = z.tuple([z.unknown()]);

export const validateQuadReturnSchema = z.boolean();

export const validateQuadSchema = {
  params: validateQuadParamsSchema,
  returns: validateQuadReturnSchema,
};

/**
 * Schema for validateStore
 */
export const validateStoreParamsSchema = z.tuple([z.unknown()]);

export const validateStoreReturnSchema = z.boolean();

export const validateStoreSchema = {
  params: validateStoreParamsSchema,
  returns: validateStoreReturnSchema,
};

export default {
  validateQuad: validateQuadSchema,
  validateStore: validateStoreSchema
};
