/**
 * @unrdf/otel — OpenTelemetry semantic convention constants for UNRDF.
 *
 * Generated by OTel Weaver from otel/registry/.
 * Do not edit the generated files in src/generated/ directly.
 * Re-generate: cd otel && weaver registry generate --registry registry/ js ../packages/otel/src/generated/
 */

export * from './generated/attributes.mjs';
export * from './generated/metrics.mjs';
