/**
 * Auto-generated Zod schemas for useDeltaQuery.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useDeltaQuery
 */
export const useDeltaQueryParamsSchema = z.tuple([z.unknown().optional()]);

export const useDeltaQueryReturnSchema = z.unknown();

export const useDeltaQuerySchema = {
  params: useDeltaQueryParamsSchema,
  returns: useDeltaQueryReturnSchema,
};

export default {
  useDeltaQuery: useDeltaQuerySchema
};
