/**
 * Auto-generated Zod schemas for useQueryAsync.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useQueryAsync
 */
export const useQueryAsyncParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const useQueryAsyncReturnSchema = z.unknown();

export const useQueryAsyncSchema = {
  params: useQueryAsyncParamsSchema,
  returns: useQueryAsyncReturnSchema,
};

export default {
  useQueryAsync: useQueryAsyncSchema
};
