/**
 * Auto-generated Zod schemas for useReasoning.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useReasoning
 */
export const useReasoningParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const useReasoningReturnSchema = z.unknown();

export const useReasoningSchema = {
  params: useReasoningParamsSchema,
  returns: useReasoningReturnSchema,
};

export default {
  useReasoning: useReasoningSchema
};
