/**
 * Auto-generated Zod schemas for useSPARQLQuery.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useSPARQLQuery
 */
export const useSPARQLQueryParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const useSPARQLQueryReturnSchema = z.unknown();

export const useSPARQLQuerySchema = {
  params: useSPARQLQueryParamsSchema,
  returns: useSPARQLQueryReturnSchema,
};

export default {
  useSPARQLQuery: useSPARQLQuerySchema
};
