/**
 * Auto-generated Zod schemas for useShapeValidation.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useShapeValidation
 */
export const useShapeValidationParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const useShapeValidationReturnSchema = z.unknown();

export const useShapeValidationSchema = {
  params: useShapeValidationParamsSchema,
  returns: useShapeValidationReturnSchema,
};

export default {
  useShapeValidation: useShapeValidationSchema
};
