/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createPipeline
 */
export const createPipelineParamsSchema = z.tuple([z.string(), z.unknown()]);

export const createPipelineReturnSchema = z.unknown();

export const createPipelineSchema = {
  params: createPipelineParamsSchema,
  returns: createPipelineReturnSchema,
};

/**
 * Schema for projectApiDoc
 */
export const projectApiDocParamsSchema = z.tuple([z.string(), z.string()]);

export const projectApiDocReturnSchema = z.unknown();

export const projectApiDocSchema = {
  params: projectApiDocParamsSchema,
  returns: projectApiDocReturnSchema,
};

/**
 * Schema for projectExamples
 */
export const projectExamplesParamsSchema = z.tuple([z.string(), z.string()]);

export const projectExamplesReturnSchema = z.unknown();

export const projectExamplesSchema = {
  params: projectExamplesParamsSchema,
  returns: projectExamplesReturnSchema,
};

/**
 * Schema for projectChangelog
 */
export const projectChangelogParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const projectChangelogReturnSchema = z.unknown();

export const projectChangelogSchema = {
  params: projectChangelogParamsSchema,
  returns: projectChangelogReturnSchema,
};

export default {
  createPipeline: createPipelineSchema,
  projectApiDoc: projectApiDocSchema,
  projectExamples: projectExamplesSchema,
  projectChangelog: projectChangelogSchema
};
