/**
 * Auto-generated Zod schemas for projection.test.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for add
 */
export const addParamsSchema = z.tuple([z.number(), z.number()]);

export const addReturnSchema = z.number();

export const addSchema = {
  params: addParamsSchema,
  returns: addReturnSchema,
};

/**
 * Schema for funcOne
 */
export const funcOneParamsSchema = z.tuple([z.number()]);

export const funcOneReturnSchema = z.number();

export const funcOneSchema = {
  params: funcOneParamsSchema,
  returns: funcOneReturnSchema,
};

/**
 * Schema for funcTwo
 */
export const funcTwoParamsSchema = z.tuple([z.string()]);

export const funcTwoReturnSchema = z.string();

export const funcTwoSchema = {
  params: funcTwoParamsSchema,
  returns: funcTwoReturnSchema,
};

export default {
  add: addSchema,
  funcOne: funcOneSchema,
  funcTwo: funcTwoSchema
};
