/**
 * Auto-generated Zod schemas for use-policy-pack.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for usePolicyPack
 */
export const usePolicyPackParamsSchema = z.tuple([z.unknown().optional()]);

export const usePolicyPackReturnSchema = z.unknown();

export const usePolicyPackSchema = {
  params: usePolicyPackParamsSchema,
  returns: usePolicyPackReturnSchema,
};

export default {
  usePolicyPack: usePolicyPackSchema
};
