/**
 * Auto-generated Zod schemas for use-sandbox.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useSandbox
 */
export const useSandboxParamsSchema = z.tuple([z.unknown().optional()]);

export const useSandboxReturnSchema = z.unknown();

export const useSandboxSchema = {
  params: useSandboxParamsSchema,
  returns: useSandboxReturnSchema,
};

export default {
  useSandbox: useSandboxSchema
};
