/**
 * Auto-generated Zod schemas for use-security-validator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useSecurityValidator
 */
export const useSecurityValidatorParamsSchema = z.tuple([z.unknown().optional()]);

export const useSecurityValidatorReturnSchema = z.unknown();

export const useSecurityValidatorSchema = {
  params: useSecurityValidatorParamsSchema,
  returns: useSecurityValidatorReturnSchema,
};

export default {
  useSecurityValidator: useSecurityValidatorSchema
};
