/**
 * Auto-generated Zod schemas for useIndexedDBStore.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useIndexedDBStore
 */
export const useIndexedDBStoreParamsSchema = z.tuple([z.unknown().optional()]);

export const useIndexedDBStoreReturnSchema = z.unknown();

export const useIndexedDBStoreSchema = {
  params: useIndexedDBStoreParamsSchema,
  returns: useIndexedDBStoreReturnSchema,
};

export default {
  useIndexedDBStore: useIndexedDBStoreSchema
};
