/**
 * Auto-generated Zod schemas for useQuadStore.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useQuadStore
 */
export const useQuadStoreParamsSchema = z.tuple([z.unknown().optional()]);

export const useQuadStoreReturnSchema = z.unknown();

export const useQuadStoreSchema = {
  params: useQuadStoreParamsSchema,
  returns: useQuadStoreReturnSchema,
};

export default {
  useQuadStore: useQuadStoreSchema
};
