/**
 * Auto-generated Zod schemas for useTransaction.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useTransaction
 */
export const useTransactionParamsSchema = z.tuple([]);

export const useTransactionReturnSchema = z.unknown();

export const useTransactionSchema = {
  params: useTransactionParamsSchema,
  returns: useTransactionReturnSchema,
};

export default {
  useTransaction: useTransactionSchema
};
