/**
 * Auto-generated Zod schemas for useDeltaTracking.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useDeltaTracking
 */
export const useDeltaTrackingParamsSchema = z.tuple([z.unknown()]);

export const useDeltaTrackingReturnSchema = z.unknown();

export const useDeltaTrackingSchema = {
  params: useDeltaTrackingParamsSchema,
  returns: useDeltaTrackingReturnSchema,
};

export default {
  useDeltaTracking: useDeltaTrackingSchema
};
