/**
 * Auto-generated Zod schemas for useGraphListener.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useGraphListener
 */
export const useGraphListenerParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const useGraphListenerReturnSchema = z.unknown();

export const useGraphListenerSchema = {
  params: useGraphListenerParamsSchema,
  returns: useGraphListenerReturnSchema,
};

export default {
  useGraphListener: useGraphListenerSchema
};
