/**
 * Auto-generated Zod schemas for useKnowledgeEffect.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useKnowledgeEffect
 */
export const useKnowledgeEffectParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const useKnowledgeEffectReturnSchema = z.unknown();

export const useKnowledgeEffectSchema = {
  params: useKnowledgeEffectParamsSchema,
  returns: useKnowledgeEffectReturnSchema,
};

export default {
  useKnowledgeEffect: useKnowledgeEffectSchema
};
