/**
 * Auto-generated Zod schemas for use-recovery.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useRecovery
 */
export const useRecoveryParamsSchema = z.tuple([z.unknown().optional()]);

export const useRecoveryReturnSchema = z.unknown();

export const useRecoverySchema = {
  params: useRecoveryParamsSchema,
  returns: useRecoveryReturnSchema,
};

export default {
  useRecovery: useRecoverySchema
};
