/**
 * Auto-generated Zod schemas for use-error-boundary.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useErrorBoundary
 */
export const useErrorBoundaryParamsSchema = z.tuple([z.unknown().optional()]);

export const useErrorBoundaryReturnSchema = z.unknown();

export const useErrorBoundarySchema = {
  params: useErrorBoundaryParamsSchema,
  returns: useErrorBoundaryReturnSchema,
};

export default {
  useErrorBoundary: useErrorBoundarySchema
};
