/**
 * Auto-generated Zod schemas for cpu-profiler.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for measureCpu
 */
export const measureCpuParamsSchema = z.tuple([z.string(), z.unknown()]);

export const measureCpuReturnSchema = z.unknown();

export const measureCpuSchema = {
  params: measureCpuParamsSchema,
  returns: measureCpuReturnSchema,
};

export default {
  measureCpu: measureCpuSchema
};
