/**
 * Auto-generated Zod schemas for memory-profiler.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for measureMemory
 */
export const measureMemoryParamsSchema = z.tuple([z.string(), z.unknown()]);

export const measureMemoryReturnSchema = z.unknown();

export const measureMemorySchema = {
  params: measureMemoryParamsSchema,
  returns: measureMemoryReturnSchema,
};

export default {
  measureMemory: measureMemorySchema
};
