/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for getV6Status
 */
export const getV6StatusParamsSchema = z.tuple([]);

export const getV6StatusReturnSchema = z.unknown();

export const getV6StatusSchema = {
  params: getV6StatusParamsSchema,
  returns: getV6StatusReturnSchema,
};

/**
 * Schema for isFeatureEnabled
 */
export const isFeatureEnabledParamsSchema = z.tuple([z.string()]);

export const isFeatureEnabledReturnSchema = z.boolean();

export const isFeatureEnabledSchema = {
  params: isFeatureEnabledParamsSchema,
  returns: isFeatureEnabledReturnSchema,
};

export default {
  getV6Status: getV6StatusSchema,
  isFeatureEnabled: isFeatureEnabledSchema
};
