/**
 * Auto-generated Zod schemas for receipt-pattern.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for blake3Hash
 */
export const blake3HashParamsSchema = z.tuple([z.string()]);

export const blake3HashReturnSchema = z.string();

export const blake3HashSchema = {
  params: blake3HashParamsSchema,
  returns: blake3HashReturnSchema,
};

/**
 * Schema for canonicalize
 */
export const canonicalizeParamsSchema = z.tuple([z.any()]);

export const canonicalizeReturnSchema = z.string();

export const canonicalizeSchema = {
  params: canonicalizeParamsSchema,
  returns: canonicalizeReturnSchema,
};

/**
 * Schema for deterministicUUID
 */
export const deterministicUUIDParamsSchema = z.tuple([z.string()]);

export const deterministicUUIDReturnSchema = z.string();

export const deterministicUUIDSchema = {
  params: deterministicUUIDParamsSchema,
  returns: deterministicUUIDReturnSchema,
};

/**
 * Schema for withReceipt
 */
export const withReceiptParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const withReceiptReturnSchema = z.unknown();

export const withReceiptSchema = {
  params: withReceiptParamsSchema,
  returns: withReceiptReturnSchema,
};

/**
 * Schema for createContext
 */
export const createContextParamsSchema = z.tuple([z.string().optional()]);

export const createContextReturnSchema = z.unknown();

export const createContextSchema = {
  params: createContextParamsSchema,
  returns: createContextReturnSchema,
};

/**
 * Schema for chainReceipts
 */
export const chainReceiptsParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const chainReceiptsReturnSchema = z.unknown();

export const chainReceiptsSchema = {
  params: chainReceiptsParamsSchema,
  returns: chainReceiptsReturnSchema,
};

/**
 * Schema for verifyReceiptChain
 */
export const verifyReceiptChainParamsSchema = z.tuple([z.unknown()]);

export const verifyReceiptChainReturnSchema = z.unknown();

export const verifyReceiptChainSchema = {
  params: verifyReceiptChainParamsSchema,
  returns: verifyReceiptChainReturnSchema,
};

/**
 * Schema for compose
 */
export const composeParamsSchema = z.tuple([z.unknown()]);

export const composeReturnSchema = z.unknown();

export const composeSchema = {
  params: composeParamsSchema,
  returns: composeReturnSchema,
};

export default {
  blake3Hash: blake3HashSchema,
  canonicalize: canonicalizeSchema,
  deterministicUUID: deterministicUUIDSchema,
  withReceipt: withReceiptSchema,
  createContext: createContextSchema,
  chainReceipts: chainReceiptsSchema,
  verifyReceiptChain: verifyReceiptChainSchema,
  compose: composeSchema
};
