/**
 * Auto-generated Zod schemas for dependency-graph.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for buildDependencyGraph
 */
export const buildDependencyGraphParamsSchema = z.tuple([z.unknown()]);

export const buildDependencyGraphReturnSchema = z.unknown();

export const buildDependencyGraphSchema = {
  params: buildDependencyGraphParamsSchema,
  returns: buildDependencyGraphReturnSchema,
};

/**
 * Schema for getDirectDependents
 */
export const getDirectDependentsParamsSchema = z.tuple([z.unknown(), z.string()]);

export const getDirectDependentsReturnSchema = z.unknown();

export const getDirectDependentsSchema = {
  params: getDirectDependentsParamsSchema,
  returns: getDirectDependentsReturnSchema,
};

/**
 * Schema for getDirectDependencies
 */
export const getDirectDependenciesParamsSchema = z.tuple([z.unknown(), z.string()]);

export const getDirectDependenciesReturnSchema = z.unknown();

export const getDirectDependenciesSchema = {
  params: getDirectDependenciesParamsSchema,
  returns: getDirectDependenciesReturnSchema,
};

/**
 * Schema for getTransitiveDependents
 */
export const getTransitiveDependentsParamsSchema = z.tuple([z.unknown(), z.string()]);

export const getTransitiveDependentsReturnSchema = z.unknown();

export const getTransitiveDependentsSchema = {
  params: getTransitiveDependentsParamsSchema,
  returns: getTransitiveDependentsReturnSchema,
};

/**
 * Schema for getTransitiveDependencies
 */
export const getTransitiveDependenciesParamsSchema = z.tuple([z.unknown(), z.string()]);

export const getTransitiveDependenciesReturnSchema = z.unknown();

export const getTransitiveDependenciesSchema = {
  params: getTransitiveDependenciesParamsSchema,
  returns: getTransitiveDependenciesReturnSchema,
};

/**
 * Schema for findLeafPackages
 */
export const findLeafPackagesParamsSchema = z.tuple([z.unknown()]);

export const findLeafPackagesReturnSchema = z.unknown();

export const findLeafPackagesSchema = {
  params: findLeafPackagesParamsSchema,
  returns: findLeafPackagesReturnSchema,
};

/**
 * Schema for findRootPackages
 */
export const findRootPackagesParamsSchema = z.tuple([z.unknown()]);

export const findRootPackagesReturnSchema = z.unknown();

export const findRootPackagesSchema = {
  params: findRootPackagesParamsSchema,
  returns: findRootPackagesReturnSchema,
};

/**
 * Schema for topologicalSort
 */
export const topologicalSortParamsSchema = z.tuple([z.unknown()]);

export const topologicalSortReturnSchema = z.unknown();

export const topologicalSortSchema = {
  params: topologicalSortParamsSchema,
  returns: topologicalSortReturnSchema,
};

/**
 * Schema for generateGraphSummary
 */
export const generateGraphSummaryParamsSchema = z.tuple([z.unknown()]);

export const generateGraphSummaryReturnSchema = z.unknown();

export const generateGraphSummarySchema = {
  params: generateGraphSummaryParamsSchema,
  returns: generateGraphSummaryReturnSchema,
};

/**
 * Schema for exportGraphToJSON
 */
export const exportGraphToJSONParamsSchema = z.tuple([z.unknown()]);

export const exportGraphToJSONReturnSchema = z.unknown();

export const exportGraphToJSONSchema = {
  params: exportGraphToJSONParamsSchema,
  returns: exportGraphToJSONReturnSchema,
};

/**
 * Schema for visualizeGraphAsText
 */
export const visualizeGraphAsTextParamsSchema = z.tuple([z.unknown()]);

export const visualizeGraphAsTextReturnSchema = z.string();

export const visualizeGraphAsTextSchema = {
  params: visualizeGraphAsTextParamsSchema,
  returns: visualizeGraphAsTextReturnSchema,
};

export default {
  buildDependencyGraph: buildDependencyGraphSchema,
  getDirectDependents: getDirectDependentsSchema,
  getDirectDependencies: getDirectDependenciesSchema,
  getTransitiveDependents: getTransitiveDependentsSchema,
  getTransitiveDependencies: getTransitiveDependenciesSchema,
  findLeafPackages: findLeafPackagesSchema,
  findRootPackages: findRootPackagesSchema,
  topologicalSort: topologicalSortSchema,
  generateGraphSummary: generateGraphSummarySchema,
  exportGraphToJSON: exportGraphToJSONSchema,
  visualizeGraphAsText: visualizeGraphAsTextSchema
};
