/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for analyzeDependencies
 */
export const analyzeDependenciesParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const analyzeDependenciesReturnSchema = z.unknown();

export const analyzeDependenciesSchema = {
  params: analyzeDependenciesParamsSchema,
  returns: analyzeDependenciesReturnSchema,
};

/**
 * Schema for generateDetailedReports
 */
export const generateDetailedReportsParamsSchema = z.tuple([z.unknown()]);

export const generateDetailedReportsReturnSchema = z.unknown();

export const generateDetailedReportsSchema = {
  params: generateDetailedReportsParamsSchema,
  returns: generateDetailedReportsReturnSchema,
};

/**
 * Schema for generateGOSReceipt
 */
export const generateGOSReceiptParamsSchema = z.tuple([z.unknown()]);

export const generateGOSReceiptReturnSchema = z.unknown();

export const generateGOSReceiptSchema = {
  params: generateGOSReceiptParamsSchema,
  returns: generateGOSReceiptReturnSchema,
};

/**
 * Schema for quickHealthCheck
 */
export const quickHealthCheckParamsSchema = z.tuple([z.string()]);

export const quickHealthCheckReturnSchema = z.unknown();

export const quickHealthCheckSchema = {
  params: quickHealthCheckParamsSchema,
  returns: quickHealthCheckReturnSchema,
};

/**
 * Schema for getChangeImpact
 */
export const getChangeImpactParamsSchema = z.tuple([z.string(), z.string()]);

export const getChangeImpactReturnSchema = z.unknown();

export const getChangeImpactSchema = {
  params: getChangeImpactParamsSchema,
  returns: getChangeImpactReturnSchema,
};

export default {
  analyzeDependencies: analyzeDependenciesSchema,
  generateDetailedReports: generateDetailedReportsSchema,
  generateGOSReceipt: generateGOSReceiptSchema,
  quickHealthCheck: quickHealthCheckSchema,
  getChangeImpact: getChangeImpactSchema
};
