/**
 * Auto-generated Zod schemas for metrics-computer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for computeMetrics
 */
export const computeMetricsParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const computeMetricsReturnSchema = z.unknown();

export const computeMetricsSchema = {
  params: computeMetricsParamsSchema,
  returns: computeMetricsReturnSchema,
};

/**
 * Schema for formatMetricsReport
 */
export const formatMetricsReportParamsSchema = z.tuple([z.unknown()]);

export const formatMetricsReportReturnSchema = z.string();

export const formatMetricsReportSchema = {
  params: formatMetricsReportParamsSchema,
  returns: formatMetricsReportReturnSchema,
};

/**
 * Schema for exportMetricsToJSON
 */
export const exportMetricsToJSONParamsSchema = z.tuple([z.unknown()]);

export const exportMetricsToJSONReturnSchema = z.unknown();

export const exportMetricsToJSONSchema = {
  params: exportMetricsToJSONParamsSchema,
  returns: exportMetricsToJSONReturnSchema,
};

export default {
  computeMetrics: computeMetricsSchema,
  formatMetricsReport: formatMetricsReportSchema,
  exportMetricsToJSON: exportMetricsToJSONSchema
};
