/**
 * Auto-generated Zod schemas for optimization-suggester.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for generateOptimizations
 */
export const generateOptimizationsParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown()]);

export const generateOptimizationsReturnSchema = z.unknown();

export const generateOptimizationsSchema = {
  params: generateOptimizationsParamsSchema,
  returns: generateOptimizationsReturnSchema,
};

/**
 * Schema for formatOptimizationReport
 */
export const formatOptimizationReportParamsSchema = z.tuple([z.unknown()]);

export const formatOptimizationReportReturnSchema = z.string();

export const formatOptimizationReportSchema = {
  params: formatOptimizationReportParamsSchema,
  returns: formatOptimizationReportReturnSchema,
};

/**
 * Schema for exportOptimizationToJSON
 */
export const exportOptimizationToJSONParamsSchema = z.tuple([z.unknown()]);

export const exportOptimizationToJSONReturnSchema = z.unknown();

export const exportOptimizationToJSONSchema = {
  params: exportOptimizationToJSONParamsSchema,
  returns: exportOptimizationToJSONReturnSchema,
};

export default {
  generateOptimizations: generateOptimizationsSchema,
  formatOptimizationReport: formatOptimizationReportSchema,
  exportOptimizationToJSON: exportOptimizationToJSONSchema
};
