/**
 * Auto-generated Zod schemas for accessibility-check.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for accessibilityCheck
 */
export const accessibilityCheckParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const accessibilityCheckReturnSchema = z.unknown();

export const accessibilityCheckSchema = {
  params: accessibilityCheckParamsSchema,
  returns: accessibilityCheckReturnSchema,
};

export default {
  accessibilityCheck: accessibilityCheckSchema
};
