/**
 * Auto-generated Zod schemas for code-quality-check.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for codeQualityCheck
 */
export const codeQualityCheckParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const codeQualityCheckReturnSchema = z.unknown();

export const codeQualityCheckSchema = {
  params: codeQualityCheckParamsSchema,
  returns: codeQualityCheckReturnSchema,
};

export default {
  codeQualityCheck: codeQualityCheckSchema
};
