/**
 * Auto-generated Zod schemas for compatibility-check.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for compatibilityCheck
 */
export const compatibilityCheckParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const compatibilityCheckReturnSchema = z.unknown();

export const compatibilityCheckSchema = {
  params: compatibilityCheckParamsSchema,
  returns: compatibilityCheckReturnSchema,
};

export default {
  compatibilityCheck: compatibilityCheckSchema
};
