/**
 * Auto-generated Zod schemas for dependency-check.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for dependencyCheck
 */
export const dependencyCheckParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const dependencyCheckReturnSchema = z.unknown();

export const dependencyCheckSchema = {
  params: dependencyCheckParamsSchema,
  returns: dependencyCheckReturnSchema,
};

export default {
  dependencyCheck: dependencyCheckSchema
};
