/**
 * Auto-generated Zod schemas for documentation-check.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for documentationCheck
 */
export const documentationCheckParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const documentationCheckReturnSchema = z.unknown();

export const documentationCheckSchema = {
  params: documentationCheckParamsSchema,
  returns: documentationCheckReturnSchema,
};

export default {
  documentationCheck: documentationCheckSchema
};
