/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for runAllChecks
 */
export const runAllChecksParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const runAllChecksReturnSchema = z.unknown();

export const runAllChecksSchema = {
  params: runAllChecksParamsSchema,
  returns: runAllChecksReturnSchema,
};

export default {
  runAllChecks: runAllChecksSchema
};
