/**
 * Auto-generated Zod schemas for performance-check.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for performanceCheck
 */
export const performanceCheckParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const performanceCheckReturnSchema = z.unknown();

export const performanceCheckSchema = {
  params: performanceCheckParamsSchema,
  returns: performanceCheckReturnSchema,
};

export default {
  performanceCheck: performanceCheckSchema
};
