/**
 * Auto-generated Zod schemas for security-check.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for securityCheck
 */
export const securityCheckParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const securityCheckReturnSchema = z.unknown();

export const securityCheckSchema = {
  params: securityCheckParamsSchema,
  returns: securityCheckReturnSchema,
};

export default {
  securityCheck: securityCheckSchema
};
