/**
 * Auto-generated Zod schemas for test-check.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for testCheck
 */
export const testCheckParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const testCheckReturnSchema = z.unknown();

export const testCheckSchema = {
  params: testCheckParamsSchema,
  returns: testCheckReturnSchema,
};

export default {
  testCheck: testCheckSchema
};
