/**
 * Auto-generated Zod schemas for otel-validator-core.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createOTELValidator
 */
export const createOTELValidatorParamsSchema = z.tuple([z.unknown().optional()]);

export const createOTELValidatorReturnSchema = z.unknown();

export const createOTELValidatorSchema = {
  params: createOTELValidatorParamsSchema,
  returns: createOTELValidatorReturnSchema,
};

export default {
  createOTELValidator: createOTELValidatorSchema
};
