/**
 * Auto-generated Zod schemas for otel-metrics-collector.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateMetrics
 */
export const validateMetricsParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const validateMetricsReturnSchema = z.unknown();

export const validateMetricsSchema = {
  params: validateMetricsParamsSchema,
  returns: validateMetricsReturnSchema,
};

/**
 * Schema for createMetricsCollector
 */
export const createMetricsCollectorParamsSchema = z.tuple([z.unknown()]);

export const createMetricsCollectorReturnSchema = z.unknown();

export const createMetricsCollectorSchema = {
  params: createMetricsCollectorParamsSchema,
  returns: createMetricsCollectorReturnSchema,
};

export default {
  validateMetrics: validateMetricsSchema,
  createMetricsCollector: createMetricsCollectorSchema
};
