/**
 * Auto-generated Zod schemas for otel-reporter.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for formatValidationResult
 */
export const formatValidationResultParamsSchema = z.tuple([z.unknown()]);

export const formatValidationResultReturnSchema = z.string();

export const formatValidationResultSchema = {
  params: formatValidationResultParamsSchema,
  returns: formatValidationResultReturnSchema,
};

/**
 * Schema for formatValidationSummary
 */
export const formatValidationSummaryParamsSchema = z.tuple([z.unknown()]);

export const formatValidationSummaryReturnSchema = z.string();

export const formatValidationSummarySchema = {
  params: formatValidationSummaryParamsSchema,
  returns: formatValidationSummaryReturnSchema,
};

/**
 * Schema for formatAsJSON
 */
export const formatAsJSONParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const formatAsJSONReturnSchema = z.string();

export const formatAsJSONSchema = {
  params: formatAsJSONParamsSchema,
  returns: formatAsJSONReturnSchema,
};

/**
 * Schema for formatAsMarkdown
 */
export const formatAsMarkdownParamsSchema = z.tuple([z.unknown()]);

export const formatAsMarkdownReturnSchema = z.string();

export const formatAsMarkdownSchema = {
  params: formatAsMarkdownParamsSchema,
  returns: formatAsMarkdownReturnSchema,
};

/**
 * Schema for createReport
 */
export const createReportParamsSchema = z.tuple([z.unknown()]);

export const createReportReturnSchema = z.unknown();

export const createReportSchema = {
  params: createReportParamsSchema,
  returns: createReportReturnSchema,
};

/**
 * Schema for printResult
 */
export const printResultParamsSchema = z.tuple([z.unknown()]);

export const printResultReturnSchema = z.unknown();

export const printResultSchema = {
  params: printResultParamsSchema,
  returns: printResultReturnSchema,
};

/**
 * Schema for printSummary
 */
export const printSummaryParamsSchema = z.tuple([z.unknown()]);

export const printSummaryReturnSchema = z.unknown();

export const printSummarySchema = {
  params: printSummaryParamsSchema,
  returns: printSummaryReturnSchema,
};

/**
 * Schema for createReporter
 */
export const createReporterParamsSchema = z.tuple([z.unknown()]);

export const createReporterReturnSchema = z.unknown();

export const createReporterSchema = {
  params: createReporterParamsSchema,
  returns: createReporterReturnSchema,
};

export default {
  formatValidationResult: formatValidationResultSchema,
  formatValidationSummary: formatValidationSummarySchema,
  formatAsJSON: formatAsJSONSchema,
  formatAsMarkdown: formatAsMarkdownSchema,
  createReport: createReportSchema,
  printResult: printResultSchema,
  printSummary: printSummarySchema,
  createReporter: createReporterSchema
};
