/**
 * Auto-generated Zod schemas for otel-span-builder.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createSpanData
 */
export const createSpanDataParamsSchema = z.tuple([z.string(), z.string(), z.number(), z.unknown().optional()]);

export const createSpanDataReturnSchema = z.unknown();

export const createSpanDataSchema = {
  params: createSpanDataParamsSchema,
  returns: createSpanDataReturnSchema,
};

/**
 * Schema for executeKnowledgeEngine
 */
export const executeKnowledgeEngineParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const executeKnowledgeEngineReturnSchema = z.unknown();

export const executeKnowledgeEngineSchema = {
  params: executeKnowledgeEngineParamsSchema,
  returns: executeKnowledgeEngineReturnSchema,
};

/**
 * Schema for executeCLIParse
 */
export const executeCLIParseParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const executeCLIParseReturnSchema = z.unknown();

export const executeCLIParseSchema = {
  params: executeCLIParseParamsSchema,
  returns: executeCLIParseReturnSchema,
};

/**
 * Schema for executeCLIQuery
 */
export const executeCLIQueryParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const executeCLIQueryReturnSchema = z.unknown();

export const executeCLIQuerySchema = {
  params: executeCLIQueryParamsSchema,
  returns: executeCLIQueryReturnSchema,
};

/**
 * Schema for executeCLIValidate
 */
export const executeCLIValidateParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const executeCLIValidateReturnSchema = z.unknown();

export const executeCLIValidateSchema = {
  params: executeCLIValidateParamsSchema,
  returns: executeCLIValidateReturnSchema,
};

/**
 * Schema for executeCLIHook
 */
export const executeCLIHookParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const executeCLIHookReturnSchema = z.unknown();

export const executeCLIHookSchema = {
  params: executeCLIHookParamsSchema,
  returns: executeCLIHookReturnSchema,
};

/**
 * Schema for executeTransactionManager
 */
export const executeTransactionManagerParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const executeTransactionManagerReturnSchema = z.unknown();

export const executeTransactionManagerSchema = {
  params: executeTransactionManagerParamsSchema,
  returns: executeTransactionManagerReturnSchema,
};

/**
 * Schema for executeKnowledgeEngineCore
 */
export const executeKnowledgeEngineCoreParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const executeKnowledgeEngineCoreReturnSchema = z.unknown();

export const executeKnowledgeEngineCoreSchema = {
  params: executeKnowledgeEngineCoreParamsSchema,
  returns: executeKnowledgeEngineCoreReturnSchema,
};

/**
 * Schema for executeKnowledgeHooksAPI
 */
export const executeKnowledgeHooksAPIParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const executeKnowledgeHooksAPIReturnSchema = z.unknown();

export const executeKnowledgeHooksAPISchema = {
  params: executeKnowledgeHooksAPIParamsSchema,
  returns: executeKnowledgeHooksAPIReturnSchema,
};

/**
 * Schema for executePolicyPacks
 */
export const executePolicyPacksParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const executePolicyPacksReturnSchema = z.unknown();

export const executePolicyPacksSchema = {
  params: executePolicyPacksParamsSchema,
  returns: executePolicyPacksReturnSchema,
};

/**
 * Schema for executeLockchainIntegrity
 */
export const executeLockchainIntegrityParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const executeLockchainIntegrityReturnSchema = z.unknown();

export const executeLockchainIntegritySchema = {
  params: executeLockchainIntegrityParamsSchema,
  returns: executeLockchainIntegrityReturnSchema,
};

/**
 * Schema for executeBrowserCompatibility
 */
export const executeBrowserCompatibilityParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const executeBrowserCompatibilityReturnSchema = z.unknown();

export const executeBrowserCompatibilitySchema = {
  params: executeBrowserCompatibilityParamsSchema,
  returns: executeBrowserCompatibilityReturnSchema,
};

export default {
  createSpanData: createSpanDataSchema,
  executeKnowledgeEngine: executeKnowledgeEngineSchema,
  executeCLIParse: executeCLIParseSchema,
  executeCLIQuery: executeCLIQuerySchema,
  executeCLIValidate: executeCLIValidateSchema,
  executeCLIHook: executeCLIHookSchema,
  executeTransactionManager: executeTransactionManagerSchema,
  executeKnowledgeEngineCore: executeKnowledgeEngineCoreSchema,
  executeKnowledgeHooksAPI: executeKnowledgeHooksAPISchema,
  executePolicyPacks: executePolicyPacksSchema,
  executeLockchainIntegrity: executeLockchainIntegritySchema,
  executeBrowserCompatibility: executeBrowserCompatibilitySchema
};
