/**
 * Auto-generated Zod schemas for production-validator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createProductionValidator
 */
export const createProductionValidatorParamsSchema = z.tuple([z.unknown().optional()]);

export const createProductionValidatorReturnSchema = z.unknown();

export const createProductionValidatorSchema = {
  params: createProductionValidatorParamsSchema,
  returns: createProductionValidatorReturnSchema,
};

/**
 * Schema for validatePackage
 */
export const validatePackageParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const validatePackageReturnSchema = z.unknown();

export const validatePackageSchema = {
  params: validatePackageParamsSchema,
  returns: validatePackageReturnSchema,
};

/**
 * Schema for validatePackages
 */
export const validatePackagesParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const validatePackagesReturnSchema = z.unknown();

export const validatePackagesSchema = {
  params: validatePackagesParamsSchema,
  returns: validatePackagesReturnSchema,
};

/**
 * Schema for isProductionReady
 */
export const isProductionReadyParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const isProductionReadyReturnSchema = z.unknown();

export const isProductionReadySchema = {
  params: isProductionReadyParamsSchema,
  returns: isProductionReadyReturnSchema,
};

export default {
  createProductionValidator: createProductionValidatorSchema,
  validatePackage: validatePackageSchema,
  validatePackages: validatePackagesSchema,
  isProductionReady: isProductionReadySchema
};
