/**
 * Auto-generated Zod schemas for validation-helpers.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createValidationHelpers
 */
export const createValidationHelpersParamsSchema = z.tuple([z.unknown().optional()]);

export const createValidationHelpersReturnSchema = z.unknown();

export const createValidationHelpersSchema = {
  params: createValidationHelpersParamsSchema,
  returns: createValidationHelpersReturnSchema,
};

export default {
  createValidationHelpers: createValidationHelpersSchema
};
