/**
 * Auto-generated Zod schemas for validation-runner.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createValidationRunner
 */
export const createValidationRunnerParamsSchema = z.tuple([z.unknown().optional()]);

export const createValidationRunnerReturnSchema = z.unknown();

export const createValidationRunnerSchema = {
  params: createValidationRunnerParamsSchema,
  returns: createValidationRunnerReturnSchema,
};

export default {
  createValidationRunner: createValidationRunnerSchema
};
