/**
 * Auto-generated Zod schemas for use-dark-matter-core.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useDarkMatterCore
 */
export const useDarkMatterCoreParamsSchema = z.tuple([z.unknown().optional()]);

export const useDarkMatterCoreReturnSchema = z.unknown();

export const useDarkMatterCoreSchema = {
  params: useDarkMatterCoreParamsSchema,
  returns: useDarkMatterCoreReturnSchema,
};

export default {
  useDarkMatterCore: useDarkMatterCoreSchema
};
