/**
 * Auto-generated Zod schemas for use-critical-path.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useCriticalPath
 */
export const useCriticalPathParamsSchema = z.tuple([z.unknown().optional()]);

export const useCriticalPathReturnSchema = z.unknown();

export const useCriticalPathSchema = {
  params: useCriticalPathParamsSchema,
  returns: useCriticalPathReturnSchema,
};

export default {
  useCriticalPath: useCriticalPathSchema
};
