/**
 * Auto-generated Zod schemas for use-query-analyzer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useQueryAnalyzer
 */
export const useQueryAnalyzerParamsSchema = z.tuple([z.unknown().optional()]);

export const useQueryAnalyzerReturnSchema = z.unknown();

export const useQueryAnalyzerSchema = {
  params: useQueryAnalyzerParamsSchema,
  returns: useQueryAnalyzerReturnSchema,
};

export default {
  useQueryAnalyzer: useQueryAnalyzerSchema
};
