/**
 * Auto-generated Zod schemas for use-optimizer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useOptimizer
 */
export const useOptimizerParamsSchema = z.tuple([z.unknown().optional()]);

export const useOptimizerReturnSchema = z.unknown();

export const useOptimizerSchema = {
  params: useOptimizerParamsSchema,
  returns: useOptimizerReturnSchema,
};

export default {
  useOptimizer: useOptimizerSchema
};
