/**
 * Auto-generated Zod schemas for store-backup.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for backupStore
 */
export const backupStoreParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const backupStoreReturnSchema = z.unknown();

export const backupStoreSchema = {
  params: backupStoreParamsSchema,
  returns: backupStoreReturnSchema,
};

export default {
  backupStore: backupStoreSchema
};
