/**
 * Auto-generated Zod schemas for store-restore.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for restoreStore
 */
export const restoreStoreParamsSchema = z.tuple([z.string(), z.string()]);

export const restoreStoreReturnSchema = z.unknown();

export const restoreStoreSchema = {
  params: restoreStoreParamsSchema,
  returns: restoreStoreReturnSchema,
};

export default {
  restoreStore: restoreStoreSchema
};
