/**
 * Auto-generated Zod schemas for store-import.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for importStore
 */
export const importStoreParamsSchema = z.tuple([z.unknown(), z.string()]);

export const importStoreReturnSchema = z.unknown();

export const importStoreSchema = {
  params: importStoreParamsSchema,
  returns: importStoreReturnSchema,
};

export default {
  importStore: importStoreSchema
};
