kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: unrdf

nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # UNRDF API
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
      # Grafana
      - containerPort: 30001
        hostPort: 3001
        protocol: TCP
      # Prometheus
      - containerPort: 30002
        hostPort: 9091
        protocol: TCP
      # OTLP gRPC
      - containerPort: 30437
        hostPort: 4317
        protocol: TCP
      # OTLP HTTP
      - containerPort: 30438
        hostPort: 4318
        protocol: TCP
      # Tempo API
      - containerPort: 30200
        hostPort: 3200
        protocol: TCP
      # Pyroscope
      - containerPort: 30040
        hostPort: 4040
        protocol: TCP
      # HotROD frontend
      - containerPort: 30082
        hostPort: 8082
        protocol: TCP
      # Node Exporter
      - containerPort: 30100
        hostPort: 9100
        protocol: TCP
      # Alertmanager
      - containerPort: 30093
        hostPort: 9093
        protocol: TCP
      # Loki
      - containerPort: 30100
        hostPort: 3100
        protocol: TCP
      # MinIO S3 API
      - containerPort: 30090
        hostPort: 9000
        protocol: TCP
      # MinIO Console
      - containerPort: 30091
        hostPort: 9001
        protocol: TCP
