kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: unrdf
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - "kind: InitConfiguration\nnodeRegistration:\n  kubeletExtraArgs:\n    node-labels:\
        \ \"ingress-ready=true\"\n"
    extraPortMappings:
      - containerPort: 30000
        hostPort: 7001
        protocol: TCP
      - containerPort: 30001
        hostPort: 7002
        protocol: TCP
      - containerPort: 30002
        hostPort: 7003
        protocol: TCP
      - containerPort: 30437
        hostPort: 7004
        protocol: TCP
      - containerPort: 30438
        hostPort: 7005
        protocol: TCP
      - containerPort: 30200
        hostPort: 7006
        protocol: TCP
      - containerPort: 30040
        hostPort: 7007
        protocol: TCP
      - containerPort: 30082
        hostPort: 7008
        protocol: TCP
      - containerPort: 30100
        hostPort: 7009
        protocol: TCP
      - containerPort: 30093
        hostPort: 7010
        protocol: TCP
      - containerPort: 30100
        hostPort: 7011
        protocol: TCP
      - containerPort: 30090
        hostPort: 7012
        protocol: TCP
      - containerPort: 30091
        hostPort: 7013
        protocol: TCP
      - containerPort: 30050
        hostPort: 7014
        protocol: TCP
      - containerPort: 30051
        hostPort: 7015
        protocol: TCP
