/**
 * Auto-generated Zod schemas for config.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for parseEnv
 */
export const parseEnvParamsSchema = z.tuple([z.unknown().optional()]);

export const parseEnvReturnSchema = z.unknown();

export const parseEnvSchema = {
  params: parseEnvParamsSchema,
  returns: parseEnvReturnSchema,
};

/**
 * Schema for mergeConfig
 */
export const mergeConfigParamsSchema = z.tuple([z.unknown()]);

export const mergeConfigReturnSchema = z.unknown();

export const mergeConfigSchema = {
  params: mergeConfigParamsSchema,
  returns: mergeConfigReturnSchema,
};

/**
 * Schema for createConfig
 */
export const createConfigParamsSchema = z.tuple([z.unknown().optional(), z.unknown()]);

export const createConfigReturnSchema = z.unknown();

export const createConfigSchema = {
  params: createConfigParamsSchema,
  returns: createConfigReturnSchema,
};

/**
 * Schema for getConfigValue
 */
export const getConfigValueParamsSchema = z.tuple([z.unknown(), z.string()]);

export const getConfigValueReturnSchema = z.unknown();

export const getConfigValueSchema = {
  params: getConfigValueParamsSchema,
  returns: getConfigValueReturnSchema,
};

/**
 * Schema for validateConfig
 */
export const validateConfigParamsSchema = z.tuple([z.unknown()]);

export const validateConfigReturnSchema = z.boolean();

export const validateConfigSchema = {
  params: validateConfigParamsSchema,
  returns: validateConfigReturnSchema,
};

/**
 * Schema for getGlobalConfig
 */
export const getGlobalConfigParamsSchema = z.tuple([]);

export const getGlobalConfigReturnSchema = z.unknown();

export const getGlobalConfigSchema = {
  params: getGlobalConfigParamsSchema,
  returns: getGlobalConfigReturnSchema,
};

/**
 * Schema for setGlobalConfig
 */
export const setGlobalConfigParamsSchema = z.tuple([z.unknown()]);

export const setGlobalConfigReturnSchema = z.unknown();

export const setGlobalConfigSchema = {
  params: setGlobalConfigParamsSchema,
  returns: setGlobalConfigReturnSchema,
};

/**
 * Schema for resetGlobalConfig
 */
export const resetGlobalConfigParamsSchema = z.tuple([]);

export const resetGlobalConfigReturnSchema = z.unknown();

export const resetGlobalConfigSchema = {
  params: resetGlobalConfigParamsSchema,
  returns: resetGlobalConfigReturnSchema,
};

export default {
  parseEnv: parseEnvSchema,
  mergeConfig: mergeConfigSchema,
  createConfig: createConfigSchema,
  getConfigValue: getConfigValueSchema,
  validateConfig: validateConfigSchema,
  getGlobalConfig: getGlobalConfigSchema,
  setGlobalConfig: setGlobalConfigSchema,
  resetGlobalConfig: resetGlobalConfigSchema
};
