/**
 * Auto-generated Zod schemas for debug.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createDebugger
 */
export const createDebuggerParamsSchema = z.tuple([z.string()]);

export const createDebuggerReturnSchema = z.unknown();

export const createDebuggerSchema = {
  params: createDebuggerParamsSchema,
  returns: createDebuggerReturnSchema,
};

/**
 * Schema for trace
 */
export const traceParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const traceReturnSchema = z.unknown();

export const traceSchema = {
  params: traceParamsSchema,
  returns: traceReturnSchema,
};

/**
 * Schema for traceMethod
 */
export const traceMethodParamsSchema = z.tuple([z.unknown().optional()]);

export const traceMethodReturnSchema = z.unknown();

export const traceMethodSchema = {
  params: traceMethodParamsSchema,
  returns: traceMethodReturnSchema,
};

/**
 * Schema for formatBytes
 */
export const formatBytesParamsSchema = z.tuple([z.number()]);

export const formatBytesReturnSchema = z.string();

export const formatBytesSchema = {
  params: formatBytesParamsSchema,
  returns: formatBytesReturnSchema,
};

/**
 * Schema for getSystemInfo
 */
export const getSystemInfoParamsSchema = z.tuple([]);

export const getSystemInfoReturnSchema = z.unknown();

export const getSystemInfoSchema = {
  params: getSystemInfoParamsSchema,
  returns: getSystemInfoReturnSchema,
};

/**
 * Schema for dumpDebugSnapshot
 */
export const dumpDebugSnapshotParamsSchema = z.tuple([]);

export const dumpDebugSnapshotReturnSchema = z.unknown();

export const dumpDebugSnapshotSchema = {
  params: dumpDebugSnapshotParamsSchema,
  returns: dumpDebugSnapshotReturnSchema,
};

export default {
  createDebugger: createDebuggerSchema,
  trace: traceSchema,
  traceMethod: traceMethodSchema,
  formatBytes: formatBytesSchema,
  getSystemInfo: getSystemInfoSchema,
  dumpDebugSnapshot: dumpDebugSnapshotSchema
};
