/**
 * Auto-generated Zod schemas for errors.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createError
 */
export const createErrorParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const createErrorReturnSchema = z.unknown();

export const createErrorSchema = {
  params: createErrorParamsSchema,
  returns: createErrorReturnSchema,
};

/**
 * Schema for wrapError
 */
export const wrapErrorParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const wrapErrorReturnSchema = z.unknown();

export const wrapErrorSchema = {
  params: wrapErrorParamsSchema,
  returns: wrapErrorReturnSchema,
};

/**
 * Schema for assertError
 */
export const assertErrorParamsSchema = z.tuple([z.boolean(), z.string(), z.unknown().optional()]);

export const assertErrorReturnSchema = z.unknown();

export const assertErrorSchema = {
  params: assertErrorParamsSchema,
  returns: assertErrorReturnSchema,
};

export default {
  createError: createErrorSchema,
  wrapError: wrapErrorSchema,
  assertError: assertErrorSchema
};
