/**
 * Auto-generated Zod schemas for health.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createHealthChecks
 */
export const createHealthChecksParamsSchema = z.tuple([z.string()]);

export const createHealthChecksReturnSchema = z.unknown();

export const createHealthChecksSchema = {
  params: createHealthChecksParamsSchema,
  returns: createHealthChecksReturnSchema,
};

/**
 * Schema for createHealthMiddleware
 */
export const createHealthMiddlewareParamsSchema = z.tuple([z.unknown()]);

export const createHealthMiddlewareReturnSchema = z.unknown();

export const createHealthMiddlewareSchema = {
  params: createHealthMiddlewareParamsSchema,
  returns: createHealthMiddlewareReturnSchema,
};

/**
 * Schema for createUnrdfHealthChecks
 */
export const createUnrdfHealthChecksParamsSchema = z.tuple([z.unknown().optional()]);

export const createUnrdfHealthChecksReturnSchema = z.unknown();

export const createUnrdfHealthChecksSchema = {
  params: createUnrdfHealthChecksParamsSchema,
  returns: createUnrdfHealthChecksReturnSchema,
};

export default {
  createHealthChecks: createHealthChecksSchema,
  createHealthMiddleware: createHealthMiddlewareSchema,
  createUnrdfHealthChecks: createUnrdfHealthChecksSchema
};
