/**
 * Auto-generated Zod schemas for logger.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createLogger
 */
export const createLoggerParamsSchema = z.tuple([z.string()]);

export const createLoggerReturnSchema = z.unknown();

export const createLoggerSchema = {
  params: createLoggerParamsSchema,
  returns: createLoggerReturnSchema,
};

/**
 * Schema for performanceTimer
 */
export const performanceTimerParamsSchema = z.tuple([]);

export const performanceTimerReturnSchema = z.unknown();

export const performanceTimerSchema = {
  params: performanceTimerParamsSchema,
  returns: performanceTimerReturnSchema,
};

/**
 * Schema for requestLogger
 */
export const requestLoggerParamsSchema = z.tuple([z.unknown().optional()]);

export const requestLoggerReturnSchema = z.unknown();

export const requestLoggerSchema = {
  params: requestLoggerParamsSchema,
  returns: requestLoggerReturnSchema,
};

export default {
  createLogger: createLoggerSchema,
  performanceTimer: performanceTimerSchema,
  requestLogger: requestLoggerSchema
};
