/**
 * Auto-generated Zod schemas for metrics.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createMetrics
 */
export const createMetricsParamsSchema = z.tuple([z.unknown().optional()]);

export const createMetricsReturnSchema = z.unknown();

export const createMetricsSchema = {
  params: createMetricsParamsSchema,
  returns: createMetricsReturnSchema,
};

export default {
  createMetrics: createMetricsSchema
};
