/**
 * Auto-generated Zod schemas for n3-justified-receipts.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for testN3Determinism
 */
export const testN3DeterminismParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const testN3DeterminismReturnSchema = z.unknown();

export const testN3DeterminismSchema = {
  params: testN3DeterminismParamsSchema,
  returns: testN3DeterminismReturnSchema,
};

export default {
  testN3Determinism: testN3DeterminismSchema
};
