/**
 * Auto-generated Zod schemas for recovery.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for retry
 */
export const retryParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const retryReturnSchema = z.unknown();

export const retrySchema = {
  params: retryParamsSchema,
  returns: retryReturnSchema,
};

/**
 * Schema for fallback
 */
export const fallbackParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const fallbackReturnSchema = z.unknown();

export const fallbackSchema = {
  params: fallbackParamsSchema,
  returns: fallbackReturnSchema,
};

/**
 * Schema for withTimeout
 */
export const withTimeoutParamsSchema = z.tuple([z.unknown(), z.number(), z.unknown().optional()]);

export const withTimeoutReturnSchema = z.unknown();

export const withTimeoutSchema = {
  params: withTimeoutParamsSchema,
  returns: withTimeoutReturnSchema,
};

/**
 * Schema for bulkOperation
 */
export const bulkOperationParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const bulkOperationReturnSchema = z.unknown();

export const bulkOperationSchema = {
  params: bulkOperationParamsSchema,
  returns: bulkOperationReturnSchema,
};

/**
 * Schema for withRecovery
 */
export const withRecoveryParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const withRecoveryReturnSchema = z.unknown();

export const withRecoverySchema = {
  params: withRecoveryParamsSchema,
  returns: withRecoveryReturnSchema,
};

export default {
  retry: retrySchema,
  fallback: fallbackSchema,
  withTimeout: withTimeoutSchema,
  bulkOperation: bulkOperationSchema,
  withRecovery: withRecoverySchema
};
