/**
 * Auto-generated Zod schemas for security.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for sanitizeHTML
 */
export const sanitizeHTMLParamsSchema = z.tuple([z.string()]);

export const sanitizeHTMLReturnSchema = z.string();

export const sanitizeHTMLSchema = {
  params: sanitizeHTMLParamsSchema,
  returns: sanitizeHTMLReturnSchema,
};

/**
 * Schema for sanitizeURL
 */
export const sanitizeURLParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const sanitizeURLReturnSchema = z.unknown();

export const sanitizeURLSchema = {
  params: sanitizeURLParamsSchema,
  returns: sanitizeURLReturnSchema,
};

/**
 * Schema for isPathSafe
 */
export const isPathSafeParamsSchema = z.tuple([z.string(), z.string()]);

export const isPathSafeReturnSchema = z.boolean();

export const isPathSafeSchema = {
  params: isPathSafeParamsSchema,
  returns: isPathSafeReturnSchema,
};

/**
 * Schema for generateSecureRandom
 */
export const generateSecureRandomParamsSchema = z.tuple([z.number().optional()]);

export const generateSecureRandomReturnSchema = z.string();

export const generateSecureRandomSchema = {
  params: generateSecureRandomParamsSchema,
  returns: generateSecureRandomReturnSchema,
};

/**
 * Schema for hashPassword
 */
export const hashPasswordParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const hashPasswordReturnSchema = z.unknown();

export const hashPasswordSchema = {
  params: hashPasswordParamsSchema,
  returns: hashPasswordReturnSchema,
};

/**
 * Schema for verifyPassword
 */
export const verifyPasswordParamsSchema = z.tuple([z.string(), z.string(), z.string()]);

export const verifyPasswordReturnSchema = z.unknown();

export const verifyPasswordSchema = {
  params: verifyPasswordParamsSchema,
  returns: verifyPasswordReturnSchema,
};

/**
 * Schema for getSecurityHeaders
 */
export const getSecurityHeadersParamsSchema = z.tuple([]);

export const getSecurityHeadersReturnSchema = z.unknown();

export const getSecurityHeadersSchema = {
  params: getSecurityHeadersParamsSchema,
  returns: getSecurityHeadersReturnSchema,
};

/**
 * Schema for validateInput
 */
export const validateInputParamsSchema = z.tuple([z.string()]);

export const validateInputReturnSchema = z.unknown();

export const validateInputSchema = {
  params: validateInputParamsSchema,
  returns: validateInputReturnSchema,
};

export default {
  sanitizeHTML: sanitizeHTMLSchema,
  sanitizeURL: sanitizeURLSchema,
  isPathSafe: isPathSafeSchema,
  generateSecureRandom: generateSecureRandomSchema,
  hashPassword: hashPasswordSchema,
  verifyPassword: verifyPasswordSchema,
  getSecurityHeaders: getSecurityHeadersSchema,
  validateInput: validateInputSchema
};
