/**
 * Auto-generated Zod schemas for security-schemas.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateInput
 */
export const validateInputParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const validateInputReturnSchema = z.unknown();

export const validateInputSchema = {
  params: validateInputParamsSchema,
  returns: validateInputReturnSchema,
};

/**
 * Schema for validateFields
 */
export const validateFieldsParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const validateFieldsReturnSchema = z.unknown();

export const validateFieldsSchema = {
  params: validateFieldsParamsSchema,
  returns: validateFieldsReturnSchema,
};

export default {
  validateInput: validateInputSchema,
  validateFields: validateFieldsSchema
};
