/**
 * Auto-generated Zod schemas for types.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createTerms
 */
export const createTermsParamsSchema = z.tuple([z.unknown()]);

export const createTermsReturnSchema = z.unknown();

export const createTermsSchema = {
  params: createTermsParamsSchema,
  returns: createTermsReturnSchema,
};

/**
 * Schema for createNamedNode
 */
export const createNamedNodeParamsSchema = z.tuple([z.string()]);

export const createNamedNodeReturnSchema = z.unknown();

export const createNamedNodeSchema = {
  params: createNamedNodeParamsSchema,
  returns: createNamedNodeReturnSchema,
};

/**
 * Schema for createLiteral
 */
export const createLiteralParamsSchema = z.tuple([z.string(), z.unknown().optional(), z.unknown().optional()]);

export const createLiteralReturnSchema = z.unknown();

export const createLiteralSchema = {
  params: createLiteralParamsSchema,
  returns: createLiteralReturnSchema,
};

/**
 * Schema for createBlankNode
 */
export const createBlankNodeParamsSchema = z.tuple([z.unknown()]);

export const createBlankNodeReturnSchema = z.unknown();

export const createBlankNodeSchema = {
  params: createBlankNodeParamsSchema,
  returns: createBlankNodeReturnSchema,
};

/**
 * Schema for createVariable
 */
export const createVariableParamsSchema = z.tuple([z.string()]);

export const createVariableReturnSchema = z.unknown();

export const createVariableSchema = {
  params: createVariableParamsSchema,
  returns: createVariableReturnSchema,
};

/**
 * Schema for createQuad
 */
export const createQuadParamsSchema = z.array(z.unknown()).length(4);

export const createQuadReturnSchema = z.unknown();

export const createQuadSchema = {
  params: createQuadParamsSchema,
  returns: createQuadReturnSchema,
};

export default {
  createTerms: createTermsSchema,
  createNamedNode: createNamedNodeSchema,
  createLiteral: createLiteralSchema,
  createBlankNode: createBlankNodeSchema,
  createVariable: createVariableSchema,
  createQuad: createQuadSchema
};
