/**
 * Auto-generated Zod schemas for error-sanitizer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createErrorSanitizer
 */
export const createErrorSanitizerParamsSchema = z.tuple([z.unknown().optional()]);

export const createErrorSanitizerReturnSchema = z.unknown();

export const createErrorSanitizerSchema = {
  params: createErrorSanitizerParamsSchema,
  returns: createErrorSanitizerReturnSchema,
};

/**
 * Schema for sanitizeError
 */
export const sanitizeErrorParamsSchema = z.tuple([z.unknown()]);

export const sanitizeErrorReturnSchema = z.string();

export const sanitizeErrorSchema = {
  params: sanitizeErrorParamsSchema,
  returns: sanitizeErrorReturnSchema,
};

export default {
  createErrorSanitizer: createErrorSanitizerSchema,
  sanitizeError: sanitizeErrorSchema
};
