/**
 * Auto-generated Zod schemas for sandbox-restrictions.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createSandboxRestrictions
 */
export const createSandboxRestrictionsParamsSchema = z.tuple([z.unknown().optional()]);

export const createSandboxRestrictionsReturnSchema = z.unknown();

export const createSandboxRestrictionsSchema = {
  params: createSandboxRestrictionsParamsSchema,
  returns: createSandboxRestrictionsReturnSchema,
};

export default {
  createSandboxRestrictions: createSandboxRestrictionsSchema
};
