/**
 * Auto-generated Zod schemas for useHookManager.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useHookManager
 */
export const useHookManagerParamsSchema = z.tuple([]);

export const useHookManagerReturnSchema = z.unknown();

export const useHookManagerSchema = {
  params: useHookManagerParamsSchema,
  returns: useHookManagerReturnSchema,
};

export default {
  useHookManager: useHookManagerSchema
};
