/**
 * Auto-generated Zod schemas for useHookExecution.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useHookExecution
 */
export const useHookExecutionParamsSchema = z.tuple([z.unknown().optional()]);

export const useHookExecutionReturnSchema = z.unknown();

export const useHookExecutionSchema = {
  params: useHookExecutionParamsSchema,
  returns: useHookExecutionReturnSchema,
};

export default {
  useHookExecution: useHookExecutionSchema
};
