/**
 * Auto-generated Zod schemas for useKnowledgeHook.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useKnowledgeHook
 */
export const useKnowledgeHookParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const useKnowledgeHookReturnSchema = z.unknown();

export const useKnowledgeHookSchema = {
  params: useKnowledgeHookParamsSchema,
  returns: useKnowledgeHookReturnSchema,
};

export default {
  useKnowledgeHook: useKnowledgeHookSchema
};
