/**
 * Auto-generated Zod schemas for useDebug.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useDebug
 */
export const useDebugParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const useDebugReturnSchema = z.unknown();

export const useDebugSchema = {
  params: useDebugParamsSchema,
  returns: useDebugReturnSchema,
};

export default {
  useDebug: useDebugSchema
};
