/**
 * Auto-generated Zod schemas for useNamespaces.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useNamespaces
 */
export const useNamespacesParamsSchema = z.tuple([z.unknown().optional()]);

export const useNamespacesReturnSchema = z.unknown();

export const useNamespacesSchema = {
  params: useNamespacesParamsSchema,
  returns: useNamespacesReturnSchema,
};

export default {
  useNamespaces: useNamespacesSchema
};
