/**
 * Auto-generated Zod schemas for usePerformanceTracking.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for usePerformanceTracking
 */
export const usePerformanceTrackingParamsSchema = z.tuple([]);

export const usePerformanceTrackingReturnSchema = z.unknown();

export const usePerformanceTrackingSchema = {
  params: usePerformanceTrackingParamsSchema,
  returns: usePerformanceTrackingReturnSchema,
};

export default {
  usePerformanceTracking: usePerformanceTrackingSchema
};
