/**
 * Auto-generated Zod schemas for useValidation.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useValidation
 */
export const useValidationParamsSchema = z.tuple([z.unknown()]);

export const useValidationReturnSchema = z.unknown();

export const useValidationSchema = {
  params: useValidationParamsSchema,
  returns: useValidationReturnSchema,
};

export default {
  useValidation: useValidationSchema
};
