/**
 * Auto-generated Zod schemas for use-quality-metrics.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useQualityMetrics
 */
export const useQualityMetricsParamsSchema = z.tuple([z.unknown().optional()]);

export const useQualityMetricsReturnSchema = z.unknown();

export const useQualityMetricsSchema = {
  params: useQualityMetricsParamsSchema,
  returns: useQualityMetricsReturnSchema,
};

export default {
  useQualityMetrics: useQualityMetricsSchema
};
