/**
 * Auto-generated Zod schemas for use-observability-manager.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useObservabilityManager
 */
export const useObservabilityManagerParamsSchema = z.tuple([z.unknown().optional()]);

export const useObservabilityManagerReturnSchema = z.unknown();

export const useObservabilityManagerSchema = {
  params: useObservabilityManagerParamsSchema,
  returns: useObservabilityManagerReturnSchema,
};

export default {
  useObservabilityManager: useObservabilityManagerSchema
};
