/**
 * Auto-generated Zod schemas for use-reasoning-session.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useReasoningSession
 */
export const useReasoningSessionParamsSchema = z.tuple([z.unknown().optional()]);

export const useReasoningSessionReturnSchema = z.unknown();

export const useReasoningSessionSchema = {
  params: useReasoningSessionParamsSchema,
  returns: useReasoningSessionReturnSchema,
};

export default {
  useReasoningSession: useReasoningSessionSchema
};
