/**
 * Auto-generated Zod schemas for use-graph-merge.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useGraphMerge
 */
export const useGraphMergeParamsSchema = z.tuple([z.unknown().optional()]);

export const useGraphMergeReturnSchema = z.unknown();

export const useGraphMergeSchema = {
  params: useGraphMergeParamsSchema,
  returns: useGraphMergeReturnSchema,
};

export default {
  useGraphMerge: useGraphMergeSchema
};
