/**
 * Auto-generated Zod schemas for use-graph-diff.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useGraphDiff
 */
export const useGraphDiffParamsSchema = z.tuple([z.unknown().optional()]);

export const useGraphDiffReturnSchema = z.unknown();

export const useGraphDiffSchema = {
  params: useGraphDiffParamsSchema,
  returns: useGraphDiffReturnSchema,
};

export default {
  useGraphDiff: useGraphDiffSchema
};
