/**
 * Auto-generated Zod schemas for admit.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for admitCommand
 */
export const admitCommandParamsSchema = z.tuple([z.unknown()]);

export const admitCommandReturnSchema = z.unknown();

export const admitCommandSchema = {
  params: admitCommandParamsSchema,
  returns: admitCommandReturnSchema,
};

export default {
  admitCommand: admitCommandSchema
};
