/**
 * Auto-generated Zod schemas for propose.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for proposeCommand
 */
export const proposeCommandParamsSchema = z.tuple([z.unknown()]);

export const proposeCommandReturnSchema = z.unknown();

export const proposeCommandSchema = {
  params: proposeCommandParamsSchema,
  returns: proposeCommandReturnSchema,
};

export default {
  proposeCommand: proposeCommandSchema
};
