/**
 * Auto-generated Zod schemas for validate.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateCommand
 */
export const validateCommandParamsSchema = z.tuple([z.unknown()]);

export const validateCommandReturnSchema = z.unknown();

export const validateCommandSchema = {
  params: validateCommandParamsSchema,
  returns: validateCommandReturnSchema,
};

export default {
  validateCommand: validateCommandSchema
};
