/**
 * @fileoverview Legacy hooks facade
 * Generated by Agent 8 - Domain Kit Generator
 */

import { createSubstrate } from '../../substrate/hooks-substrate.mjs';

/**
 * Legacy hooks facade
 * Wraps substrate and exposes legacy API
 */
class HooksFacade {
  constructor(config = {}) {
    this.substrate = createSubstrate(config);
    this.config = config;
  }

  /**
   * Register knowledge hook
   * @param {string} name - Hook name
   * @param {Function} handler - Hook handler
   * @returns {Object} Hook registration
   */
  async registerHook(name, handler) {
    // Adapt legacy params to substrate format
    const substrateInput = {
      name,
      handler
    };

    // Execute on substrate
    const result = await this.substrate.execute('registerHook', substrateInput);

    // Adapt substrate result to legacy format
    return result;
  }

  /**
   * Execute registered hook
   * @param {string} name - Hook name
   * @param {Object} context - Execution context
   * @returns {Object} Execution result
   */
  async executeHook(name, context) {
    // Adapt legacy params to substrate format
    const substrateInput = {
      name,
      context
    };

    // Execute on substrate
    const result = await this.substrate.execute('executeHook', substrateInput);

    // Adapt substrate result to legacy format
    return result;
  }

  /**
   * Apply policy pack to store
   * @param {Store} store - Store instance
   * @param {Object} policyPack - Policy pack
   * @returns {Object} Application result
   */
  async applyPolicyPack(store, policyPack) {
    // Adapt legacy params to substrate format
    const substrateInput = {
      store,
      policyPack
    };

    // Execute on substrate
    const result = await this.substrate.execute('applyPolicyPack', substrateInput);

    // Adapt substrate result to legacy format
    return result;
  }
}


/**
 * Create hooks facade instance
 *
 * @param {Object} config - Configuration
 * @returns {HooksFacade} Facade instance
 */
export function createHooksFacade(config = {}) {
  return new HooksFacade(config);
}

export default HooksFacade;
