/**
 * Auto-generated Zod schemas for KnowledgeEngineProvider.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for KnowledgeEngineProvider
 */
export const KnowledgeEngineProviderParamsSchema = z.tuple([z.unknown().optional(), z.unknown()]);

export const KnowledgeEngineProviderReturnSchema = z.unknown();

export const KnowledgeEngineProviderSchema = {
  params: KnowledgeEngineProviderParamsSchema,
  returns: KnowledgeEngineProviderReturnSchema,
};

export default {
  KnowledgeEngineProvider: KnowledgeEngineProviderSchema
};
