/**
 * Auto-generated Zod schemas for capacity-computer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createCapacityComputer
 */
export const createCapacityComputerParamsSchema = z.tuple([z.unknown().optional()]);

export const createCapacityComputerReturnSchema = z.unknown();

export const createCapacityComputerSchema = {
  params: createCapacityComputerParamsSchema,
  returns: createCapacityComputerReturnSchema,
};

/**
 * Schema for computeCapacity
 */
export const computeCapacityParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const computeCapacityReturnSchema = z.unknown();

export const computeCapacitySchema = {
  params: computeCapacityParamsSchema,
  returns: computeCapacityReturnSchema,
};

/**
 * Schema for checkCapacityHealth
 */
export const checkCapacityHealthParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const checkCapacityHealthReturnSchema = z.unknown();

export const checkCapacityHealthSchema = {
  params: checkCapacityHealthParamsSchema,
  returns: checkCapacityHealthReturnSchema,
};

export default {
  createCapacityComputer: createCapacityComputerSchema,
  computeCapacity: computeCapacitySchema,
  checkCapacityHealth: checkCapacityHealthSchema
};
