/**
 * Auto-generated Zod schemas for certificate-generator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createCertificateGenerator
 */
export const createCertificateGeneratorParamsSchema = z.tuple([z.unknown().optional()]);

export const createCertificateGeneratorReturnSchema = z.unknown();

export const createCertificateGeneratorSchema = {
  params: createCertificateGeneratorParamsSchema,
  returns: createCertificateGeneratorReturnSchema,
};

/**
 * Schema for generateCertificate
 */
export const generateCertificateParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const generateCertificateReturnSchema = z.unknown();

export const generateCertificateSchema = {
  params: generateCertificateParamsSchema,
  returns: generateCertificateReturnSchema,
};

export default {
  createCertificateGenerator: createCertificateGeneratorSchema,
  generateCertificate: generateCertificateSchema
};
