/**
 * Auto-generated Zod schemas for correlation-computer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createCorrelationComputer
 */
export const createCorrelationComputerParamsSchema = z.tuple([z.unknown().optional()]);

export const createCorrelationComputerReturnSchema = z.unknown();

export const createCorrelationComputerSchema = {
  params: createCorrelationComputerParamsSchema,
  returns: createCorrelationComputerReturnSchema,
};

/**
 * Schema for computeTotalCorrelation
 */
export const computeTotalCorrelationParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const computeTotalCorrelationReturnSchema = z.unknown();

export const computeTotalCorrelationSchema = {
  params: computeTotalCorrelationParamsSchema,
  returns: computeTotalCorrelationReturnSchema,
};

/**
 * Schema for checkCorrelationHealth
 */
export const checkCorrelationHealthParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const checkCorrelationHealthReturnSchema = z.unknown();

export const checkCorrelationHealthSchema = {
  params: checkCorrelationHealthParamsSchema,
  returns: checkCorrelationHealthReturnSchema,
};

export default {
  createCorrelationComputer: createCorrelationComputerSchema,
  computeTotalCorrelation: computeTotalCorrelationSchema,
  checkCorrelationHealth: checkCorrelationHealthSchema
};
