/**
 * Auto-generated Zod schemas for dimension-computer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createDimensionComputer
 */
export const createDimensionComputerParamsSchema = z.tuple([z.unknown().optional()]);

export const createDimensionComputerReturnSchema = z.unknown();

export const createDimensionComputerSchema = {
  params: createDimensionComputerParamsSchema,
  returns: createDimensionComputerReturnSchema,
};

/**
 * Schema for computeDimension
 */
export const computeDimensionParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const computeDimensionReturnSchema = z.unknown();

export const computeDimensionSchema = {
  params: computeDimensionParamsSchema,
  returns: computeDimensionReturnSchema,
};

/**
 * Schema for checkDimensionHealth
 */
export const checkDimensionHealthParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const checkDimensionHealthReturnSchema = z.unknown();

export const checkDimensionHealthSchema = {
  params: checkDimensionHealthParamsSchema,
  returns: checkDimensionHealthReturnSchema,
};

export default {
  createDimensionComputer: createDimensionComputerSchema,
  computeDimension: computeDimensionSchema,
  checkDimensionHealth: checkDimensionHealthSchema
};
