/**
 * Auto-generated Zod schemas for health-dashboard.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createHealthDashboard
 */
export const createHealthDashboardParamsSchema = z.tuple([z.unknown().optional()]);

export const createHealthDashboardReturnSchema = z.unknown();

export const createHealthDashboardSchema = {
  params: createHealthDashboardParamsSchema,
  returns: createHealthDashboardReturnSchema,
};

/**
 * Schema for startDashboard
 */
export const startDashboardParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const startDashboardReturnSchema = z.unknown();

export const startDashboardSchema = {
  params: startDashboardParamsSchema,
  returns: startDashboardReturnSchema,
};

export default {
  createHealthDashboard: createHealthDashboardSchema,
  startDashboard: startDashboardSchema
};
