/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createMeasurementSystem
 */
export const createMeasurementSystemParamsSchema = z.tuple([z.unknown().optional()]);

export const createMeasurementSystemReturnSchema = z.unknown();

export const createMeasurementSystemSchema = {
  params: createMeasurementSystemParamsSchema,
  returns: createMeasurementSystemReturnSchema,
};

export default {
  createMeasurementSystem: createMeasurementSystemSchema
};
