/**
 * Auto-generated Zod schemas for registry.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for buildDependencyGraph
 */
export const buildDependencyGraphParamsSchema = z.tuple([]);

export const buildDependencyGraphReturnSchema = z.unknown();

export const buildDependencyGraphSchema = {
  params: buildDependencyGraphParamsSchema,
  returns: buildDependencyGraphReturnSchema,
};

/**
 * Schema for buildReverseDependencyGraph
 */
export const buildReverseDependencyGraphParamsSchema = z.tuple([]);

export const buildReverseDependencyGraphReturnSchema = z.unknown();

export const buildReverseDependencyGraphSchema = {
  params: buildReverseDependencyGraphParamsSchema,
  returns: buildReverseDependencyGraphReturnSchema,
};

/**
 * Schema for topologicalSort
 */
export const topologicalSortParamsSchema = z.tuple([]);

export const topologicalSortReturnSchema = z.unknown();

export const topologicalSortSchema = {
  params: topologicalSortParamsSchema,
  returns: topologicalSortReturnSchema,
};

/**
 * Schema for getPackagesMeasuring
 */
export const getPackagesMeasuringParamsSchema = z.tuple([z.unknown()]);

export const getPackagesMeasuringReturnSchema = z.unknown();

export const getPackagesMeasuringSchema = {
  params: getPackagesMeasuringParamsSchema,
  returns: getPackagesMeasuringReturnSchema,
};

/**
 * Schema for getPolicyInfluencingPackages
 */
export const getPolicyInfluencingPackagesParamsSchema = z.tuple([]);

export const getPolicyInfluencingPackagesReturnSchema = z.unknown();

export const getPolicyInfluencingPackagesSchema = {
  params: getPolicyInfluencingPackagesParamsSchema,
  returns: getPolicyInfluencingPackagesReturnSchema,
};

/**
 * Schema for getPackagesByTier
 */
export const getPackagesByTierParamsSchema = z.tuple([z.number()]);

export const getPackagesByTierReturnSchema = z.unknown();

export const getPackagesByTierSchema = {
  params: getPackagesByTierParamsSchema,
  returns: getPackagesByTierReturnSchema,
};

/**
 * Schema for getPackagesByCriticality
 */
export const getPackagesByCriticalityParamsSchema = z.tuple([z.unknown()]);

export const getPackagesByCriticalityReturnSchema = z.unknown();

export const getPackagesByCriticalitySchema = {
  params: getPackagesByCriticalityParamsSchema,
  returns: getPackagesByCriticalityReturnSchema,
};

/**
 * Schema for applyRollupRules
 */
export const applyRollupRulesParamsSchema = z.tuple([z.unknown()]);

export const applyRollupRulesReturnSchema = z.unknown();

export const applyRollupRulesSchema = {
  params: applyRollupRulesParamsSchema,
  returns: applyRollupRulesReturnSchema,
};

/**
 * Schema for getPackageEntry
 */
export const getPackageEntryParamsSchema = z.tuple([z.string()]);

export const getPackageEntryReturnSchema = z.unknown();

export const getPackageEntrySchema = {
  params: getPackageEntryParamsSchema,
  returns: getPackageEntryReturnSchema,
};

/**
 * Schema for getAllPackageNames
 */
export const getAllPackageNamesParamsSchema = z.tuple([]);

export const getAllPackageNamesReturnSchema = z.unknown();

export const getAllPackageNamesSchema = {
  params: getAllPackageNamesParamsSchema,
  returns: getAllPackageNamesReturnSchema,
};

/**
 * Schema for getPackageCount
 */
export const getPackageCountParamsSchema = z.tuple([]);

export const getPackageCountReturnSchema = z.number();

export const getPackageCountSchema = {
  params: getPackageCountParamsSchema,
  returns: getPackageCountReturnSchema,
};

/**
 * Schema for hasPackage
 */
export const hasPackageParamsSchema = z.tuple([z.string()]);

export const hasPackageReturnSchema = z.boolean();

export const hasPackageSchema = {
  params: hasPackageParamsSchema,
  returns: hasPackageReturnSchema,
};

/**
 * Schema for getMeasurementConfig
 */
export const getMeasurementConfigParamsSchema = z.tuple([z.string()]);

export const getMeasurementConfigReturnSchema = z.unknown();

export const getMeasurementConfigSchema = {
  params: getMeasurementConfigParamsSchema,
  returns: getMeasurementConfigReturnSchema,
};

export default {
  buildDependencyGraph: buildDependencyGraphSchema,
  buildReverseDependencyGraph: buildReverseDependencyGraphSchema,
  topologicalSort: topologicalSortSchema,
  getPackagesMeasuring: getPackagesMeasuringSchema,
  getPolicyInfluencingPackages: getPolicyInfluencingPackagesSchema,
  getPackagesByTier: getPackagesByTierSchema,
  getPackagesByCriticality: getPackagesByCriticalitySchema,
  applyRollupRules: applyRollupRulesSchema,
  getPackageEntry: getPackageEntrySchema,
  getAllPackageNames: getAllPackageNamesSchema,
  getPackageCount: getPackageCountSchema,
  hasPackage: hasPackageSchema,
  getMeasurementConfig: getMeasurementConfigSchema
};
