/**
 * Auto-generated Zod schemas for schema.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for computeShannonContribution
 */
export const computeShannonContributionParamsSchema = z.tuple([z.number(), z.number()]);

export const computeShannonContributionReturnSchema = z.number();

export const computeShannonContributionSchema = {
  params: computeShannonContributionParamsSchema,
  returns: computeShannonContributionReturnSchema,
};

/**
 * Schema for computePackageEntropy
 */
export const computePackageEntropyParamsSchema = z.tuple([z.unknown()]);

export const computePackageEntropyReturnSchema = z.number();

export const computePackageEntropySchema = {
  params: computePackageEntropyParamsSchema,
  returns: computePackageEntropyReturnSchema,
};

/**
 * Schema for computeChangeCapacity
 */
export const computeChangeCapacityParamsSchema = z.tuple([z.number(), z.number()]);

export const computeChangeCapacityReturnSchema = z.number();

export const computeChangeCapacitySchema = {
  params: computeChangeCapacityParamsSchema,
  returns: computeChangeCapacityReturnSchema,
};

/**
 * Schema for computeTemporalCoupling
 */
export const computeTemporalCouplingParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const computeTemporalCouplingReturnSchema = z.number();

export const computeTemporalCouplingSchema = {
  params: computeTemporalCouplingParamsSchema,
  returns: computeTemporalCouplingReturnSchema,
};

/**
 * Schema for buildTCMatrix
 */
export const buildTCMatrixParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const buildTCMatrixReturnSchema = z.unknown();

export const buildTCMatrixSchema = {
  params: buildTCMatrixParamsSchema,
  returns: buildTCMatrixReturnSchema,
};

/**
 * Schema for computeTransitiveEntropy
 */
export const computeTransitiveEntropyParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const computeTransitiveEntropyReturnSchema = z.unknown();

export const computeTransitiveEntropySchema = {
  params: computeTransitiveEntropyParamsSchema,
  returns: computeTransitiveEntropyReturnSchema,
};

/**
 * Schema for aggregateToSystem
 */
export const aggregateToSystemParamsSchema = z.tuple([z.unknown()]);

export const aggregateToSystemReturnSchema = z.unknown();

export const aggregateToSystemSchema = {
  params: aggregateToSystemParamsSchema,
  returns: aggregateToSystemReturnSchema,
};

/**
 * Schema for flattenTCMatrix
 */
export const flattenTCMatrixParamsSchema = z.tuple([z.unknown()]);

export const flattenTCMatrixReturnSchema = z.unknown();

export const flattenTCMatrixSchema = {
  params: flattenTCMatrixParamsSchema,
  returns: flattenTCMatrixReturnSchema,
};

/**
 * Schema for unflattenTCMatrix
 */
export const unflattenTCMatrixParamsSchema = z.tuple([z.unknown(), z.number()]);

export const unflattenTCMatrixReturnSchema = z.unknown();

export const unflattenTCMatrixSchema = {
  params: unflattenTCMatrixParamsSchema,
  returns: unflattenTCMatrixReturnSchema,
};

/**
 * Schema for generateChecksum
 */
export const generateChecksumParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const generateChecksumReturnSchema = z.string();

export const generateChecksumSchema = {
  params: generateChecksumParamsSchema,
  returns: generateChecksumReturnSchema,
};

/**
 * Schema for createCertificate
 */
export const createCertificateParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const createCertificateReturnSchema = z.unknown();

export const createCertificateSchema = {
  params: createCertificateParamsSchema,
  returns: createCertificateReturnSchema,
};

/**
 * Schema for verifyCertificate
 */
export const verifyCertificateParamsSchema = z.tuple([z.unknown()]);

export const verifyCertificateReturnSchema = z.unknown();

export const verifyCertificateSchema = {
  params: verifyCertificateParamsSchema,
  returns: verifyCertificateReturnSchema,
};

/**
 * Schema for getExtractionTemplate
 */
export const getExtractionTemplateParamsSchema = z.tuple([z.number()]);

export const getExtractionTemplateReturnSchema = z.unknown();

export const getExtractionTemplateSchema = {
  params: getExtractionTemplateParamsSchema,
  returns: getExtractionTemplateReturnSchema,
};

/**
 * Schema for calculateEntropyTrend
 */
export const calculateEntropyTrendParamsSchema = z.tuple([z.unknown()]);

export const calculateEntropyTrendReturnSchema = z.unknown();

export const calculateEntropyTrendSchema = {
  params: calculateEntropyTrendParamsSchema,
  returns: calculateEntropyTrendReturnSchema,
};

/**
 * Schema for formatEntropy
 */
export const formatEntropyParamsSchema = z.tuple([z.number()]);

export const formatEntropyReturnSchema = z.string();

export const formatEntropySchema = {
  params: formatEntropyParamsSchema,
  returns: formatEntropyReturnSchema,
};

/**
 * Schema for getPackageHealth
 */
export const getPackageHealthParamsSchema = z.tuple([z.number(), z.number()]);

export const getPackageHealthReturnSchema = z.unknown();

export const getPackageHealthSchema = {
  params: getPackageHealthParamsSchema,
  returns: getPackageHealthReturnSchema,
};

/**
 * Schema for diffCertificates
 */
export const diffCertificatesParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const diffCertificatesReturnSchema = z.unknown();

export const diffCertificatesSchema = {
  params: diffCertificatesParamsSchema,
  returns: diffCertificatesReturnSchema,
};

export default {
  computeShannonContribution: computeShannonContributionSchema,
  computePackageEntropy: computePackageEntropySchema,
  computeChangeCapacity: computeChangeCapacitySchema,
  computeTemporalCoupling: computeTemporalCouplingSchema,
  buildTCMatrix: buildTCMatrixSchema,
  computeTransitiveEntropy: computeTransitiveEntropySchema,
  aggregateToSystem: aggregateToSystemSchema,
  flattenTCMatrix: flattenTCMatrixSchema,
  unflattenTCMatrix: unflattenTCMatrixSchema,
  generateChecksum: generateChecksumSchema,
  createCertificate: createCertificateSchema,
  verifyCertificate: verifyCertificateSchema,
  getExtractionTemplate: getExtractionTemplateSchema,
  calculateEntropyTrend: calculateEntropyTrendSchema,
  formatEntropy: formatEntropySchema,
  getPackageHealth: getPackageHealthSchema,
  diffCertificates: diffCertificatesSchema
};
