/**
 * Auto-generated Zod schemas for api-contract-validator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for generateAPISchema
 */
export const generateAPISchemaParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const generateAPISchemaReturnSchema = z.unknown();

export const generateAPISchemaSchema = {
  params: generateAPISchemaParamsSchema,
  returns: generateAPISchemaReturnSchema,
};

/**
 * Schema for generateAllAPISchemas
 */
export const generateAllAPISchemasParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const generateAllAPISchemasReturnSchema = z.unknown();

export const generateAllAPISchemasSchema = {
  params: generateAllAPISchemasParamsSchema,
  returns: generateAllAPISchemasReturnSchema,
};

/**
 * Schema for validateAPIFiles
 */
export const validateAPIFilesParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const validateAPIFilesReturnSchema = z.unknown();

export const validateAPIFilesSchema = {
  params: validateAPIFilesParamsSchema,
  returns: validateAPIFilesReturnSchema,
};

/**
 * Schema for detectContractBreaks
 */
export const detectContractBreaksParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const detectContractBreaksReturnSchema = z.unknown();

export const detectContractBreaksSchema = {
  params: detectContractBreaksParamsSchema,
  returns: detectContractBreaksReturnSchema,
};

/**
 * Schema for detectAllContractBreaks
 */
export const detectAllContractBreaksParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional(), z.unknown().optional()]);

export const detectAllContractBreaksReturnSchema = z.unknown();

export const detectAllContractBreaksSchema = {
  params: detectAllContractBreaksParamsSchema,
  returns: detectAllContractBreaksReturnSchema,
};

export default {
  generateAPISchema: generateAPISchemaSchema,
  generateAllAPISchemas: generateAllAPISchemasSchema,
  validateAPIFiles: validateAPIFilesSchema,
  detectContractBreaks: detectContractBreaksSchema,
  detectAllContractBreaks: detectAllContractBreaksSchema
};
