/**
 * Auto-generated Zod schemas for autonomic-mapek.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for runMapekIteration
 */
export const runMapekIterationParamsSchema = z.tuple([z.unknown()]);

export const runMapekIterationReturnSchema = z.unknown();

export const runMapekIterationSchema = {
  params: runMapekIterationParamsSchema,
  returns: runMapekIterationReturnSchema,
};

/**
 * Schema for createAutonomicHooks
 */
export const createAutonomicHooksParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const createAutonomicHooksReturnSchema = z.unknown();

export const createAutonomicHooksSchema = {
  params: createAutonomicHooksParamsSchema,
  returns: createAutonomicHooksReturnSchema,
};

/**
 * Schema for runContinuousMapekLoop
 */
export const runContinuousMapekLoopParamsSchema = z.tuple([z.unknown()]);

export const runContinuousMapekLoopReturnSchema = z.unknown();

export const runContinuousMapekLoopSchema = {
  params: runContinuousMapekLoopParamsSchema,
  returns: runContinuousMapekLoopReturnSchema,
};

/**
 * Schema for reportMapekStatus
 */
export const reportMapekStatusParamsSchema = z.tuple([z.unknown()]);

export const reportMapekStatusReturnSchema = z.string();

export const reportMapekStatusSchema = {
  params: reportMapekStatusParamsSchema,
  returns: reportMapekStatusReturnSchema,
};

export default {
  runMapekIteration: runMapekIterationSchema,
  createAutonomicHooks: createAutonomicHooksSchema,
  runContinuousMapekLoop: runContinuousMapekLoopSchema,
  reportMapekStatus: reportMapekStatusSchema
};
