/**
 * Auto-generated Zod schemas for auto-test-generator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for generateTestSuggestions
 */
export const generateTestSuggestionsParamsSchema = z.tuple([z.unknown()]);

export const generateTestSuggestionsReturnSchema = z.unknown();

export const generateTestSuggestionsSchema = {
  params: generateTestSuggestionsParamsSchema,
  returns: generateTestSuggestionsReturnSchema,
};

/**
 * Schema for inferTestPatterns
 */
export const inferTestPatternsParamsSchema = z.tuple([z.unknown()]);

export const inferTestPatternsReturnSchema = z.unknown();

export const inferTestPatternsSchema = {
  params: inferTestPatternsParamsSchema,
  returns: inferTestPatternsReturnSchema,
};

/**
 * Schema for generateTestSkeleton
 */
export const generateTestSkeletonParamsSchema = z.tuple([z.unknown()]);

export const generateTestSkeletonReturnSchema = z.unknown();

export const generateTestSkeletonSchema = {
  params: generateTestSkeletonParamsSchema,
  returns: generateTestSkeletonReturnSchema,
};

/**
 * Schema for scoreTestCoverage
 */
export const scoreTestCoverageParamsSchema = z.tuple([z.string()]);

export const scoreTestCoverageReturnSchema = z.unknown();

export const scoreTestCoverageSchema = {
  params: scoreTestCoverageParamsSchema,
  returns: scoreTestCoverageReturnSchema,
};

/**
 * Schema for generateTestFactory
 */
export const generateTestFactoryParamsSchema = z.tuple([z.string()]);

export const generateTestFactoryReturnSchema = z.string();

export const generateTestFactorySchema = {
  params: generateTestFactoryParamsSchema,
  returns: generateTestFactoryReturnSchema,
};

export default {
  generateTestSuggestions: generateTestSuggestionsSchema,
  inferTestPatterns: inferTestPatternsSchema,
  generateTestSkeleton: generateTestSkeletonSchema,
  scoreTestCoverage: scoreTestCoverageSchema,
  generateTestFactory: generateTestFactorySchema
};
