/**
 * Auto-generated Zod schemas for dependency-graph.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for buildDependencyGraph
 */
export const buildDependencyGraphParamsSchema = z.tuple([z.unknown()]);

export const buildDependencyGraphReturnSchema = z.unknown();

export const buildDependencyGraphSchema = {
  params: buildDependencyGraphParamsSchema,
  returns: buildDependencyGraphReturnSchema,
};

export default {
  buildDependencyGraph: buildDependencyGraphSchema
};
