/**
 * Auto-generated Zod schemas for doc-generator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for generateDocSuggestions
 */
export const generateDocSuggestionsParamsSchema = z.tuple([z.unknown()]);

export const generateDocSuggestionsReturnSchema = z.unknown();

export const generateDocSuggestionsSchema = {
  params: generateDocSuggestionsParamsSchema,
  returns: generateDocSuggestionsReturnSchema,
};

export default {
  generateDocSuggestions: generateDocSuggestionsSchema
};
