/**
 * Auto-generated Zod schemas for doc-drift-checker.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for checkDocDrift
 */
export const checkDocDriftParamsSchema = z.tuple([z.unknown()]);

export const checkDocDriftReturnSchema = z.unknown();

export const checkDocDriftSchema = {
  params: checkDocDriftParamsSchema,
  returns: checkDocDriftReturnSchema,
};

export default {
  checkDocDrift: checkDocDriftSchema
};
