/**
 * Auto-generated Zod schemas for domain-infer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for inferDomainModel
 */
export const inferDomainModelParamsSchema = z.tuple([z.unknown()]);

export const inferDomainModelReturnSchema = z.unknown();

export const inferDomainModelSchema = {
  params: inferDomainModelParamsSchema,
  returns: inferDomainModelReturnSchema,
};

/**
 * Schema for inferDomainModelFromPath
 */
export const inferDomainModelFromPathParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const inferDomainModelFromPathReturnSchema = z.unknown();

export const inferDomainModelFromPathSchema = {
  params: inferDomainModelFromPathParamsSchema,
  returns: inferDomainModelFromPathReturnSchema,
};

/**
 * Schema for DomainModelLens
 */
export const DomainModelLensParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const DomainModelLensReturnSchema = z.unknown();

export const DomainModelLensSchema = {
  params: DomainModelLensParamsSchema,
  returns: DomainModelLensReturnSchema,
};

export default {
  inferDomainModel: inferDomainModelSchema,
  inferDomainModelFromPath: inferDomainModelFromPathSchema,
  DomainModelLens: DomainModelLensSchema
};
