/**
 * Auto-generated Zod schemas for drift-snapshot.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createStructureSnapshot
 */
export const createStructureSnapshotParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const createStructureSnapshotReturnSchema = z.unknown();

export const createStructureSnapshotSchema = {
  params: createStructureSnapshotParamsSchema,
  returns: createStructureSnapshotReturnSchema,
};

/**
 * Schema for computeDrift
 */
export const computeDriftParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const computeDriftReturnSchema = z.unknown();

export const computeDriftSchema = {
  params: computeDriftParamsSchema,
  returns: computeDriftReturnSchema,
};

/**
 * Schema for createEmptyBaseline
 */
export const createEmptyBaselineParamsSchema = z.tuple([]);

export const createEmptyBaselineReturnSchema = z.unknown();

export const createEmptyBaselineSchema = {
  params: createEmptyBaselineParamsSchema,
  returns: createEmptyBaselineReturnSchema,
};

/**
 * Schema for serializeSnapshot
 */
export const serializeSnapshotParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const serializeSnapshotReturnSchema = z.string();

export const serializeSnapshotSchema = {
  params: serializeSnapshotParamsSchema,
  returns: serializeSnapshotReturnSchema,
};

/**
 * Schema for deserializeSnapshot
 */
export const deserializeSnapshotParamsSchema = z.tuple([z.string()]);

export const deserializeSnapshotReturnSchema = z.unknown();

export const deserializeSnapshotSchema = {
  params: deserializeSnapshotParamsSchema,
  returns: deserializeSnapshotReturnSchema,
};

export default {
  createStructureSnapshot: createStructureSnapshotSchema,
  computeDrift: computeDriftSchema,
  createEmptyBaseline: createEmptyBaselineSchema,
  serializeSnapshot: serializeSnapshotSchema,
  deserializeSnapshot: deserializeSnapshotSchema
};
