/**
 * Auto-generated Zod schemas for file-roles.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for classifyFiles
 */
export const classifyFilesParamsSchema = z.tuple([z.unknown()]);

export const classifyFilesReturnSchema = z.unknown();

export const classifyFilesSchema = {
  params: classifyFilesParamsSchema,
  returns: classifyFilesReturnSchema,
};

export default {
  classifyFiles: classifyFilesSchema
};
