/**
 * Auto-generated Zod schemas for fs-scan.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for scanFileSystemToStore
 */
export const scanFileSystemToStoreParamsSchema = z.tuple([z.string()]);

export const scanFileSystemToStoreReturnSchema = z.unknown();

export const scanFileSystemToStoreSchema = {
  params: scanFileSystemToStoreParamsSchema,
  returns: scanFileSystemToStoreReturnSchema,
};

export default {
  scanFileSystemToStore: scanFileSystemToStoreSchema
};
