/**
 * Auto-generated Zod schemas for gap-finder.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for findMissingRoles
 */
export const findMissingRolesParamsSchema = z.tuple([z.unknown()]);

export const findMissingRolesReturnSchema = z.unknown();

export const findMissingRolesSchema = {
  params: findMissingRolesParamsSchema,
  returns: findMissingRolesReturnSchema,
};

/**
 * Schema for scoreMissingRole
 */
export const scoreMissingRoleParamsSchema = z.tuple([z.string(), z.string(), z.unknown()]);

export const scoreMissingRoleReturnSchema = z.number();

export const scoreMissingRoleSchema = {
  params: scoreMissingRoleParamsSchema,
  returns: scoreMissingRoleReturnSchema,
};

export default {
  findMissingRoles: findMissingRolesSchema,
  scoreMissingRole: scoreMissingRoleSchema
};
