/**
 * Auto-generated Zod schemas for hotspot-analyzer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for analyzeHotspots
 */
export const analyzeHotspotsParamsSchema = z.tuple([z.unknown()]);

export const analyzeHotspotsReturnSchema = z.unknown();

export const analyzeHotspotsSchema = {
  params: analyzeHotspotsParamsSchema,
  returns: analyzeHotspotsReturnSchema,
};

/**
 * Schema for scoreFeature
 */
export const scoreFeatureParamsSchema = z.tuple([z.string(), z.unknown()]);

export const scoreFeatureReturnSchema = z.number();

export const scoreFeatureSchema = {
  params: scoreFeatureParamsSchema,
  returns: scoreFeatureReturnSchema,
};

export default {
  analyzeHotspots: analyzeHotspotsSchema,
  scoreFeature: scoreFeatureSchema
};
