/**
 * Auto-generated Zod schemas for initialize.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createProjectInitializationPipeline
 */
export const createProjectInitializationPipelineParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const createProjectInitializationPipelineReturnSchema = z.unknown();

export const createProjectInitializationPipelineSchema = {
  params: createProjectInitializationPipelineParamsSchema,
  returns: createProjectInitializationPipelineReturnSchema,
};

export default {
  createProjectInitializationPipeline: createProjectInitializationPipelineSchema
};
