/**
 * Auto-generated Zod schemas for mapek-orchestration.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for runInnovationsParallel
 */
export const runInnovationsParallelParamsSchema = z.tuple([z.unknown()]);

export const runInnovationsParallelReturnSchema = z.unknown();

export const runInnovationsParallelSchema = {
  params: runInnovationsParallelParamsSchema,
  returns: runInnovationsParallelReturnSchema,
};

/**
 * Schema for aggregateInnovationFindings
 */
export const aggregateInnovationFindingsParamsSchema = z.tuple([z.unknown()]);

export const aggregateInnovationFindingsReturnSchema = z.unknown();

export const aggregateInnovationFindingsSchema = {
  params: aggregateInnovationFindingsParamsSchema,
  returns: aggregateInnovationFindingsReturnSchema,
};

/**
 * Schema for runFullMapekWithAllInnovations
 */
export const runFullMapekWithAllInnovationsParamsSchema = z.tuple([z.unknown()]);

export const runFullMapekWithAllInnovationsReturnSchema = z.unknown();

export const runFullMapekWithAllInnovationsSchema = {
  params: runFullMapekWithAllInnovationsParamsSchema,
  returns: runFullMapekWithAllInnovationsReturnSchema,
};

export default {
  runInnovationsParallel: runInnovationsParallelSchema,
  aggregateInnovationFindings: aggregateInnovationFindingsSchema,
  runFullMapekWithAllInnovations: runFullMapekWithAllInnovationsSchema
};
