/**
 * Auto-generated Zod schemas for materialize.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for materializeArtifacts
 */
export const materializeArtifactsParamsSchema = z.tuple([z.unknown()]);

export const materializeArtifactsReturnSchema = z.unknown();

export const materializeArtifactsSchema = {
  params: materializeArtifactsParamsSchema,
  returns: materializeArtifactsReturnSchema,
};

export default {
  materializeArtifacts: materializeArtifactsSchema
};
