/**
 * Auto-generated Zod schemas for materialize-plan.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for planMaterialization
 */
export const planMaterializationParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const planMaterializationReturnSchema = z.unknown();

export const planMaterializationSchema = {
  params: planMaterializationParamsSchema,
  returns: planMaterializationReturnSchema,
};

/**
 * Schema for validatePlan
 */
export const validatePlanParamsSchema = z.tuple([z.unknown()]);

export const validatePlanReturnSchema = z.unknown();

export const validatePlanSchema = {
  params: validatePlanParamsSchema,
  returns: validatePlanReturnSchema,
};

/**
 * Schema for createEmptyPlan
 */
export const createEmptyPlanParamsSchema = z.tuple([]);

export const createEmptyPlanReturnSchema = z.unknown();

export const createEmptyPlanSchema = {
  params: createEmptyPlanParamsSchema,
  returns: createEmptyPlanReturnSchema,
};

/**
 * Schema for mergePlans
 */
export const mergePlansParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const mergePlansReturnSchema = z.unknown();

export const mergePlansSchema = {
  params: mergePlansParamsSchema,
  returns: mergePlansReturnSchema,
};

export default {
  planMaterialization: planMaterializationSchema,
  validatePlan: validatePlanSchema,
  createEmptyPlan: createEmptyPlanSchema,
  mergePlans: mergePlansSchema
};
