/**
 * Auto-generated Zod schemas for materialize-apply.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for applyMaterializationPlan
 */
export const applyMaterializationPlanParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const applyMaterializationPlanReturnSchema = z.unknown();

export const applyMaterializationPlanSchema = {
  params: applyMaterializationPlanParamsSchema,
  returns: applyMaterializationPlanReturnSchema,
};

/**
 * Schema for rollbackMaterialization
 */
export const rollbackMaterializationParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const rollbackMaterializationReturnSchema = z.unknown();

export const rollbackMaterializationSchema = {
  params: rollbackMaterializationParamsSchema,
  returns: rollbackMaterializationReturnSchema,
};

/**
 * Schema for previewPlan
 */
export const previewPlanParamsSchema = z.tuple([z.unknown()]);

export const previewPlanReturnSchema = z.unknown();

export const previewPlanSchema = {
  params: previewPlanParamsSchema,
  returns: previewPlanReturnSchema,
};

/**
 * Schema for checkPlanApplicability
 */
export const checkPlanApplicabilityParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const checkPlanApplicabilityReturnSchema = z.unknown();

export const checkPlanApplicabilitySchema = {
  params: checkPlanApplicabilityParamsSchema,
  returns: checkPlanApplicabilityReturnSchema,
};

export default {
  applyMaterializationPlan: applyMaterializationPlanSchema,
  rollbackMaterialization: rollbackMaterializationSchema,
  previewPlan: previewPlanSchema,
  checkPlanApplicability: checkPlanApplicabilitySchema
};
