/**
 * Auto-generated Zod schemas for policy-derivation.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for deriveHooksFromStructure
 */
export const deriveHooksFromStructureParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const deriveHooksFromStructureReturnSchema = z.unknown();

export const deriveHooksFromStructureSchema = {
  params: deriveHooksFromStructureParamsSchema,
  returns: deriveHooksFromStructureReturnSchema,
};

/**
 * Schema for analyzePatternViolations
 */
export const analyzePatternViolationsParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const analyzePatternViolationsReturnSchema = z.unknown();

export const analyzePatternViolationsSchema = {
  params: analyzePatternViolationsParamsSchema,
  returns: analyzePatternViolationsReturnSchema,
};

/**
 * Schema for createCustomPatternHook
 */
export const createCustomPatternHookParamsSchema = z.tuple([z.unknown()]);

export const createCustomPatternHookReturnSchema = z.unknown();

export const createCustomPatternHookSchema = {
  params: createCustomPatternHookParamsSchema,
  returns: createCustomPatternHookReturnSchema,
};

export default {
  deriveHooksFromStructure: deriveHooksFromStructureSchema,
  analyzePatternViolations: analyzePatternViolationsSchema,
  createCustomPatternHook: createCustomPatternHookSchema
};
