/**
 * Auto-generated Zod schemas for project-config.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for getProjectEngineConfig
 */
export const getProjectEngineConfigParamsSchema = z.tuple([z.unknown().optional()]);

export const getProjectEngineConfigReturnSchema = z.unknown();

export const getProjectEngineConfigSchema = {
  params: getProjectEngineConfigParamsSchema,
  returns: getProjectEngineConfigReturnSchema,
};

export default {
  getProjectEngineConfig: getProjectEngineConfigSchema
};
