/**
 * Auto-generated Zod schemas for project-model.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for buildProjectModelFromFs
 */
export const buildProjectModelFromFsParamsSchema = z.tuple([z.unknown()]);

export const buildProjectModelFromFsReturnSchema = z.unknown();

export const buildProjectModelFromFsSchema = {
  params: buildProjectModelFromFsParamsSchema,
  returns: buildProjectModelFromFsReturnSchema,
};

export default {
  buildProjectModelFromFs: buildProjectModelFromFsSchema
};
