/**
 * Auto-generated Zod schemas for project-report.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for buildProjectReport
 */
export const buildProjectReportParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const buildProjectReportReturnSchema = z.unknown();

export const buildProjectReportSchema = {
  params: buildProjectReportParamsSchema,
  returns: buildProjectReportReturnSchema,
};

export default {
  buildProjectReport: buildProjectReportSchema
};
