/**
 * Auto-generated Zod schemas for refactoring-guide.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for generateRefactoringGuide
 */
export const generateRefactoringGuideParamsSchema = z.tuple([z.unknown()]);

export const generateRefactoringGuideReturnSchema = z.unknown();

export const generateRefactoringGuideSchema = {
  params: generateRefactoringGuideParamsSchema,
  returns: generateRefactoringGuideReturnSchema,
};

export default {
  generateRefactoringGuide: generateRefactoringGuideSchema
};
