/**
 * Auto-generated Zod schemas for stack-detect.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for detectStackFromFs
 */
export const detectStackFromFsParamsSchema = z.tuple([z.unknown()]);

export const detectStackFromFsReturnSchema = z.unknown();

export const detectStackFromFsSchema = {
  params: detectStackFromFsParamsSchema,
  returns: detectStackFromFsReturnSchema,
};

export default {
  detectStackFromFs: detectStackFromFsSchema
};
