/**
 * Auto-generated Zod schemas for type-auditor.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for compareTypes
 */
export const compareTypesParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const compareTypesReturnSchema = z.unknown();

export const compareTypesSchema = {
  params: compareTypesParamsSchema,
  returns: compareTypesReturnSchema,
};

/**
 * Schema for auditTypeConsistency
 */
export const auditTypeConsistencyParamsSchema = z.tuple([z.unknown()]);

export const auditTypeConsistencyReturnSchema = z.unknown();

export const auditTypeConsistencySchema = {
  params: auditTypeConsistencyParamsSchema,
  returns: auditTypeConsistencyReturnSchema,
};

/**
 * Schema for auditEntityTypes
 */
export const auditEntityTypesParamsSchema = z.tuple([z.string(), z.string(), z.string()]);

export const auditEntityTypesReturnSchema = z.unknown();

export const auditEntityTypesSchema = {
  params: auditEntityTypesParamsSchema,
  returns: auditEntityTypesReturnSchema,
};

export default {
  compareTypes: compareTypesSchema,
  auditTypeConsistency: auditTypeConsistencySchema,
  auditEntityTypes: auditEntityTypesSchema
};
