/**
 * Auto-generated Zod schemas for use-embeddings-manager.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useEmbeddingsManager
 */
export const useEmbeddingsManagerParamsSchema = z.tuple([z.unknown().optional()]);

export const useEmbeddingsManagerReturnSchema = z.unknown();

export const useEmbeddingsManagerSchema = {
  params: useEmbeddingsManagerParamsSchema,
  returns: useEmbeddingsManagerReturnSchema,
};

export default {
  useEmbeddingsManager: useEmbeddingsManagerSchema
};
