/**
 * Auto-generated Zod schemas for use-semantic-analyzer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useSemanticAnalyzer
 */
export const useSemanticAnalyzerParamsSchema = z.tuple([z.unknown().optional()]);

export const useSemanticAnalyzerReturnSchema = z.unknown();

export const useSemanticAnalyzerSchema = {
  params: useSemanticAnalyzerParamsSchema,
  returns: useSemanticAnalyzerReturnSchema,
};

export default {
  useSemanticAnalyzer: useSemanticAnalyzerSchema
};
