/**
 * Auto-generated Zod schemas for base-receipt.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for generateUUID
 */
export const generateUUIDParamsSchema = z.tuple([]);

export const generateUUIDReturnSchema = z.string();

export const generateUUIDSchema = {
  params: generateUUIDParamsSchema,
  returns: generateUUIDReturnSchema,
};

/**
 * Schema for deterministicSerialize
 */
export const deterministicSerializeParamsSchema = z.tuple([z.unknown()]);

export const deterministicSerializeReturnSchema = z.string();

export const deterministicSerializeSchema = {
  params: deterministicSerializeParamsSchema,
  returns: deterministicSerializeReturnSchema,
};

/**
 * Schema for computeBlake3
 */
export const computeBlake3ParamsSchema = z.tuple([z.unknown()]);

export const computeBlake3ReturnSchema = z.unknown();

export const computeBlake3Schema = {
  params: computeBlake3ParamsSchema,
  returns: computeBlake3ReturnSchema,
};

/**
 * Schema for computeChainHash
 */
export const computeChainHashParamsSchema = z.tuple([z.unknown(), z.string()]);

export const computeChainHashReturnSchema = z.unknown();

export const computeChainHashSchema = {
  params: computeChainHashParamsSchema,
  returns: computeChainHashReturnSchema,
};

/**
 * Schema for verifyBaseReceipt
 */
export const verifyBaseReceiptParamsSchema = z.tuple([z.unknown()]);

export const verifyBaseReceiptReturnSchema = z.unknown();

export const verifyBaseReceiptSchema = {
  params: verifyBaseReceiptParamsSchema,
  returns: verifyBaseReceiptReturnSchema,
};

export default {
  generateUUID: generateUUIDSchema,
  deterministicSerialize: deterministicSerializeSchema,
  computeBlake3: computeBlake3Schema,
  computeChainHash: computeChainHashSchema,
  verifyBaseReceipt: verifyBaseReceiptSchema
};
