/**
 * Auto-generated Zod schemas for indexing-receipts.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for testIndexingDeterminism
 */
export const testIndexingDeterminismParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const testIndexingDeterminismReturnSchema = z.unknown();

export const testIndexingDeterminismSchema = {
  params: testIndexingDeterminismParamsSchema,
  returns: testIndexingDeterminismReturnSchema,
};

export default {
  testIndexingDeterminism: testIndexingDeterminismSchema
};
