/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createReceipt
 */
export const createReceiptParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const createReceiptReturnSchema = z.unknown();

export const createReceiptSchema = {
  params: createReceiptParamsSchema,
  returns: createReceiptReturnSchema,
};

/**
 * Schema for verifyReceipt
 */
export const verifyReceiptParamsSchema = z.tuple([z.unknown()]);

export const verifyReceiptReturnSchema = z.unknown();

export const verifyReceiptSchema = {
  params: verifyReceiptParamsSchema,
  returns: verifyReceiptReturnSchema,
};

/**
 * Schema for verifyChainLink
 */
export const verifyChainLinkParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const verifyChainLinkReturnSchema = z.unknown();

export const verifyChainLinkSchema = {
  params: verifyChainLinkParamsSchema,
  returns: verifyChainLinkReturnSchema,
};

export default {
  createReceipt: createReceiptSchema,
  verifyReceipt: verifyReceiptSchema,
  verifyChainLink: verifyChainLinkSchema
};
