/**
 * Auto-generated Zod schemas for with-receipt.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for withReceipt
 */
export const withReceiptParamsSchema = z.tuple([z.unknown(), z.string().optional()]);

export const withReceiptReturnSchema = z.unknown();

export const withReceiptSchema = {
  params: withReceiptParamsSchema,
  returns: withReceiptReturnSchema,
};

/**
 * Schema for createReceiptChain
 */
export const createReceiptChainParamsSchema = z.tuple([z.unknown()]);

export const createReceiptChainReturnSchema = z.unknown();

export const createReceiptChainSchema = {
  params: createReceiptChainParamsSchema,
  returns: createReceiptChainReturnSchema,
};

/**
 * Schema for verifyIdempotency
 */
export const verifyIdempotencyParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const verifyIdempotencyReturnSchema = z.unknown();

export const verifyIdempotencySchema = {
  params: verifyIdempotencyParamsSchema,
  returns: verifyIdempotencyReturnSchema,
};

export default {
  withReceipt: withReceiptSchema,
  createReceiptChain: createReceiptChainSchema,
  verifyIdempotency: verifyIdempotencySchema
};
