/**
 * Auto-generated Zod schemas for browser-shim.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for isBrowser
 */
export const isBrowserParamsSchema = z.tuple([]);

export const isBrowserReturnSchema = z.boolean();

export const isBrowserSchema = {
  params: isBrowserParamsSchema,
  returns: isBrowserReturnSchema,
};

/**
 * Schema for getEnvironmentShims
 */
export const getEnvironmentShimsParamsSchema = z.tuple([]);

export const getEnvironmentShimsReturnSchema = z.unknown();

export const getEnvironmentShimsSchema = {
  params: getEnvironmentShimsParamsSchema,
  returns: getEnvironmentShimsReturnSchema,
};

export default {
  isBrowser: isBrowserSchema,
  getEnvironmentShims: getEnvironmentShimsSchema
};
