/**
 * Auto-generated Zod schemas for comunica-browser-adapter.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createBrowserQueryExecutor
 */
export const createBrowserQueryExecutorParamsSchema = z.tuple([z.unknown()]);

export const createBrowserQueryExecutorReturnSchema = z.unknown();

export const createBrowserQueryExecutorSchema = {
  params: createBrowserQueryExecutorParamsSchema,
  returns: createBrowserQueryExecutorReturnSchema,
};

export default {
  createBrowserQueryExecutor: createBrowserQueryExecutorSchema
};
