/**
 * Auto-generated Zod schemas for fs-adapter.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createFsAdapter
 */
export const createFsAdapterParamsSchema = z.tuple([]);

export const createFsAdapterReturnSchema = z.unknown();

export const createFsAdapterSchema = {
  params: createFsAdapterParamsSchema,
  returns: createFsAdapterReturnSchema,
};

/**
 * Schema for getPath
 */
export const getPathParamsSchema = z.tuple([]);

export const getPathReturnSchema = z.unknown();

export const getPathSchema = {
  params: getPathParamsSchema,
  returns: getPathReturnSchema,
};

export default {
  createFsAdapter: createFsAdapterSchema,
  getPath: getPathSchema
};
