/**
 * Auto-generated Zod schemas for latency-profiler.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for measureLatency
 */
export const measureLatencyParamsSchema = z.tuple([z.string(), z.unknown()]);

export const measureLatencyReturnSchema = z.unknown();

export const measureLatencySchema = {
  params: measureLatencyParamsSchema,
  returns: measureLatencyReturnSchema,
};

export default {
  measureLatency: measureLatencySchema
};
