/**
 * Auto-generated Zod schemas for useGraphs.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useGraphs
 */
export const useGraphsParamsSchema = z.tuple([z.unknown().optional()]);

export const useGraphsReturnSchema = z.unknown();

export const useGraphsSchema = {
  params: useGraphsParamsSchema,
  returns: useGraphsReturnSchema,
};

export default {
  useGraphs: useGraphsSchema
};
