/**
 * Auto-generated Zod schemas for useKnowledgeEngine.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useKnowledgeEngine
 */
export const useKnowledgeEngineParamsSchema = z.tuple([z.unknown().optional()]);

export const useKnowledgeEngineReturnSchema = z.unknown();

export const useKnowledgeEngineSchema = {
  params: useKnowledgeEngineParamsSchema,
  returns: useKnowledgeEngineReturnSchema,
};

export default {
  useKnowledgeEngine: useKnowledgeEngineSchema
};
