/**
 * Auto-generated Zod schemas for useStore.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useStore
 */
export const useStoreParamsSchema = z.tuple([z.unknown().optional()]);

export const useStoreReturnSchema = z.unknown();

export const useStoreSchema = {
  params: useStoreParamsSchema,
  returns: useStoreReturnSchema,
};

export default {
  useStore: useStoreSchema
};
