/**
 * Auto-generated Zod schemas for useTriples.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useTriples
 */
export const useTriplesParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional()]);

export const useTriplesReturnSchema = z.unknown();

export const useTriplesSchema = {
  params: useTriplesParamsSchema,
  returns: useTriplesReturnSchema,
};

export default {
  useTriples: useTriplesSchema
};
