/**
 * Auto-generated Zod schemas for graphql-adapter.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createGraphQLAdapter
 */
export const createGraphQLAdapterParamsSchema = z.tuple([z.unknown().optional()]);

export const createGraphQLAdapterReturnSchema = z.unknown();

export const createGraphQLAdapterSchema = {
  params: createGraphQLAdapterParamsSchema,
  returns: createGraphQLAdapterReturnSchema,
};

export default {
  createGraphQLAdapter: createGraphQLAdapterSchema
};
