/**
 * Auto-generated Zod schemas for workflow-adapter.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createWorkflowAdapter
 */
export const createWorkflowAdapterParamsSchema = z.tuple([z.unknown().optional()]);

export const createWorkflowAdapterReturnSchema = z.unknown();

export const createWorkflowAdapterSchema = {
  params: createWorkflowAdapterParamsSchema,
  returns: createWorkflowAdapterReturnSchema,
};

export default {
  createWorkflowAdapter: createWorkflowAdapterSchema
};
