/**
 * Auto-generated Zod schemas for use-change-feed.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useChangeFeed
 */
export const useChangeFeedParamsSchema = z.tuple([z.unknown().optional()]);

export const useChangeFeedReturnSchema = z.unknown();

export const useChangeFeedSchema = {
  params: useChangeFeedParamsSchema,
  returns: useChangeFeedReturnSchema,
};

export default {
  useChangeFeed: useChangeFeedSchema
};
