/**
 * Auto-generated Zod schemas for use-real-time-validator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useRealTimeValidator
 */
export const useRealTimeValidatorParamsSchema = z.tuple([z.unknown().optional()]);

export const useRealTimeValidatorReturnSchema = z.unknown();

export const useRealTimeValidatorSchema = {
  params: useRealTimeValidatorParamsSchema,
  returns: useRealTimeValidatorReturnSchema,
};

export default {
  useRealTimeValidator: useRealTimeValidatorSchema
};
