/**
 * Auto-generated Zod schemas for use-subscription-manager.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useSubscriptionManager
 */
export const useSubscriptionManagerParamsSchema = z.tuple([z.unknown().optional()]);

export const useSubscriptionManagerReturnSchema = z.unknown();

export const useSubscriptionManagerSchema = {
  params: useSubscriptionManagerParamsSchema,
  returns: useSubscriptionManagerReturnSchema,
};

export default {
  useSubscriptionManager: useSubscriptionManagerSchema
};
