/**
 * Auto-generated Zod schemas for use-streaming-pipeline.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useStreamingPipeline
 */
export const useStreamingPipelineParamsSchema = z.tuple([z.unknown().optional()]);

export const useStreamingPipelineReturnSchema = z.unknown();

export const useStreamingPipelineSchema = {
  params: useStreamingPipelineParamsSchema,
  returns: useStreamingPipelineReturnSchema,
};

export default {
  useStreamingPipeline: useStreamingPipelineSchema
};
