/**
 * Auto-generated Zod schemas for use-stream-processor.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useStreamProcessor
 */
export const useStreamProcessorParamsSchema = z.tuple([z.unknown().optional()]);

export const useStreamProcessorReturnSchema = z.unknown();

export const useStreamProcessorSchema = {
  params: useStreamProcessorParamsSchema,
  returns: useStreamProcessorReturnSchema,
};

export default {
  useStreamProcessor: useStreamProcessorSchema
};
