server:
  persistentVolume:
    enabled: true
    size: 20Gi

  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb

alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
    size: 5Gi

kubeStateMetrics:
  enabled: true

prometheusNodeExporter:
  enabled: true

prometheusPushgateway:
  enabled: false
