/**
 * Auto-generated Zod schemas for circuit-breaker.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createCircuitBreaker
 */
export const createCircuitBreakerParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const createCircuitBreakerReturnSchema = z.unknown();

export const createCircuitBreakerSchema = {
  params: createCircuitBreakerParamsSchema,
  returns: createCircuitBreakerReturnSchema,
};

/**
 * Schema for withCircuitBreaker
 */
export const withCircuitBreakerParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const withCircuitBreakerReturnSchema = z.unknown();

export const withCircuitBreakerSchema = {
  params: withCircuitBreakerParamsSchema,
  returns: withCircuitBreakerReturnSchema,
};

export default {
  createCircuitBreaker: createCircuitBreakerSchema,
  withCircuitBreaker: withCircuitBreakerSchema
};
