/**
 * Auto-generated Zod schemas for enhanced-errors.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for enhanceZodError
 */
export const enhanceZodErrorParamsSchema = z.tuple([z.unknown(), z.unknown().optional(), z.unknown().optional()]);

export const enhanceZodErrorReturnSchema = z.unknown();

export const enhanceZodErrorSchema = {
  params: enhanceZodErrorParamsSchema,
  returns: enhanceZodErrorReturnSchema,
};

/**
 * Schema for safeImport
 */
export const safeImportParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const safeImportReturnSchema = z.unknown();

export const safeImportSchema = {
  params: safeImportParamsSchema,
  returns: safeImportReturnSchema,
};

/**
 * Schema for resetDebugMode
 */
export const resetDebugModeParamsSchema = z.tuple([]);

export const resetDebugModeReturnSchema = z.unknown();

export const resetDebugModeSchema = {
  params: resetDebugModeParamsSchema,
  returns: resetDebugModeReturnSchema,
};

/**
 * Schema for initializeDebugMode
 */
export const initializeDebugModeParamsSchema = z.tuple([]);

export const initializeDebugModeReturnSchema = z.unknown();

export const initializeDebugModeSchema = {
  params: initializeDebugModeParamsSchema,
  returns: initializeDebugModeReturnSchema,
};

/**
 * Schema for isDebugEnabled
 */
export const isDebugEnabledParamsSchema = z.tuple([z.string()]);

export const isDebugEnabledReturnSchema = z.boolean();

export const isDebugEnabledSchema = {
  params: isDebugEnabledParamsSchema,
  returns: isDebugEnabledReturnSchema,
};

/**
 * Schema for createDebugger
 */
export const createDebuggerParamsSchema = z.tuple([z.string()]);

export const createDebuggerReturnSchema = z.unknown();

export const createDebuggerSchema = {
  params: createDebuggerParamsSchema,
  returns: createDebuggerReturnSchema,
};

/**
 * Schema for traceWorkflowStep
 */
export const traceWorkflowStepParamsSchema = z.tuple([z.string(), z.unknown()]);

export const traceWorkflowStepReturnSchema = z.unknown();

export const traceWorkflowStepSchema = {
  params: traceWorkflowStepParamsSchema,
  returns: traceWorkflowStepReturnSchema,
};

/**
 * Schema for getErrorRecoveryGuide
 */
export const getErrorRecoveryGuideParamsSchema = z.tuple([z.unknown()]);

export const getErrorRecoveryGuideReturnSchema = z.string();

export const getErrorRecoveryGuideSchema = {
  params: getErrorRecoveryGuideParamsSchema,
  returns: getErrorRecoveryGuideReturnSchema,
};

export default {
  enhanceZodError: enhanceZodErrorSchema,
  safeImport: safeImportSchema,
  resetDebugMode: resetDebugModeSchema,
  initializeDebugMode: initializeDebugModeSchema,
  isDebugEnabled: isDebugEnabledSchema,
  createDebugger: createDebuggerSchema,
  traceWorkflowStep: traceWorkflowStepSchema,
  getErrorRecoveryGuide: getErrorRecoveryGuideSchema
};
