/**
 * Auto-generated Zod schemas for lockchain-writer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createLockchainWriter
 */
export const createLockchainWriterParamsSchema = z.tuple([z.unknown().optional()]);

export const createLockchainWriterReturnSchema = z.unknown();

export const createLockchainWriterSchema = {
  params: createLockchainWriterParamsSchema,
  returns: createLockchainWriterReturnSchema,
};

export default {
  createLockchainWriter: createLockchainWriterSchema
};
