/**
 * Auto-generated Zod schemas for performance-optimizer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createPerformanceOptimizer
 */
export const createPerformanceOptimizerParamsSchema = z.tuple([z.unknown().optional()]);

export const createPerformanceOptimizerReturnSchema = z.unknown();

export const createPerformanceOptimizerSchema = {
  params: createPerformanceOptimizerParamsSchema,
  returns: createPerformanceOptimizerReturnSchema,
};

export default {
  createPerformanceOptimizer: createPerformanceOptimizerSchema
};
