/**
 * Auto-generated Zod schemas for transaction.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for printReceipt
 */
export const printReceiptParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const printReceiptReturnSchema = z.unknown();

export const printReceiptSchema = {
  params: printReceiptParamsSchema,
  returns: printReceiptReturnSchema,
};

export default {
  printReceipt: printReceiptSchema
};
