apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowd.fullname" . }}
  labels:
    {{- include "knowd.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "knowd.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowd.fullname" . }}-headless
  labels:
    {{- include "knowd.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: cluster
  selector:
    {{- include "knowd.selectorLabels" . | nindent 4 }}
