/**
 * Auto-generated Zod schemas for useCacheStats.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useCacheStats
 */
export const useCacheStatsParamsSchema = z.tuple([]);

export const useCacheStatsReturnSchema = z.unknown();

export const useCacheStatsSchema = {
  params: useCacheStatsParamsSchema,
  returns: useCacheStatsReturnSchema,
};

export default {
  useCacheStats: useCacheStatsSchema
};
