/**
 * Auto-generated Zod schemas for useQueryCache.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useQueryCache
 */
export const useQueryCacheParamsSchema = z.tuple([z.unknown().optional()]);

export const useQueryCacheReturnSchema = z.unknown();

export const useQueryCacheSchema = {
  params: useQueryCacheParamsSchema,
  returns: useQueryCacheReturnSchema,
};

export default {
  useQueryCache: useQueryCacheSchema
};
