/**
 * Auto-generated Zod schemas for admission-engine.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createAdmissionEngine
 */
export const createAdmissionEngineParamsSchema = z.tuple([z.unknown().optional()]);

export const createAdmissionEngineReturnSchema = z.unknown();

export const createAdmissionEngineSchema = {
  params: createAdmissionEngineParamsSchema,
  returns: createAdmissionEngineReturnSchema,
};

/**
 * Schema for wouldAdmit
 */
export const wouldAdmitParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const wouldAdmitReturnSchema = z.unknown();

export const wouldAdmitSchema = {
  params: wouldAdmitParamsSchema,
  returns: wouldAdmitReturnSchema,
};

export default {
  createAdmissionEngine: createAdmissionEngineSchema,
  wouldAdmit: wouldAdmitSchema
};
