/**
 * Auto-generated Zod schemas for invariants.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for Q_typing
 */
export const Q_typingParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const Q_typingReturnSchema = z.unknown();

export const Q_typingSchema = {
  params: Q_typingParamsSchema,
  returns: Q_typingReturnSchema,
};

/**
 * Schema for Q_noncollision
 */
export const Q_noncollisionParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const Q_noncollisionReturnSchema = z.unknown();

export const Q_noncollisionSchema = {
  params: Q_noncollisionParamsSchema,
  returns: Q_noncollisionReturnSchema,
};

/**
 * Schema for Q_monotone
 */
export const Q_monotoneParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const Q_monotoneReturnSchema = z.unknown();

export const Q_monotoneSchema = {
  params: Q_monotoneParamsSchema,
  returns: Q_monotoneReturnSchema,
};

/**
 * Schema for Q_determinism
 */
export const Q_determinismParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const Q_determinismReturnSchema = z.unknown();

export const Q_determinismSchema = {
  params: Q_determinismParamsSchema,
  returns: Q_determinismReturnSchema,
};

/**
 * Schema for Q_provenance
 */
export const Q_provenanceParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const Q_provenanceReturnSchema = z.unknown();

export const Q_provenanceSchema = {
  params: Q_provenanceParamsSchema,
  returns: Q_provenanceReturnSchema,
};

/**
 * Schema for Q_bounds
 */
export const Q_boundsParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const Q_boundsReturnSchema = z.unknown();

export const Q_boundsSchema = {
  params: Q_boundsParamsSchema,
  returns: Q_boundsReturnSchema,
};

/**
 * Schema for checkAllInvariants
 */
export const checkAllInvariantsParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const checkAllInvariantsReturnSchema = z.unknown();

export const checkAllInvariantsSchema = {
  params: checkAllInvariantsParamsSchema,
  returns: checkAllInvariantsReturnSchema,
};

export default {
  Q_typing: Q_typingSchema,
  Q_noncollision: Q_noncollisionSchema,
  Q_monotone: Q_monotoneSchema,
  Q_determinism: Q_determinismSchema,
  Q_provenance: Q_provenanceSchema,
  Q_bounds: Q_boundsSchema,
  checkAllInvariants: checkAllInvariantsSchema
};
