/**
 * Auto-generated Zod schemas for validation-utils.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateIRI
 */
export const validateIRIParamsSchema = z.tuple([z.string()]);

export const validateIRIReturnSchema = z.boolean();

export const validateIRISchema = {
  params: validateIRIParamsSchema,
  returns: validateIRIReturnSchema,
};

/**
 * Schema for validateLiteral
 */
export const validateLiteralParamsSchema = z.tuple([z.unknown()]);

export const validateLiteralReturnSchema = z.boolean();

export const validateLiteralSchema = {
  params: validateLiteralParamsSchema,
  returns: validateLiteralReturnSchema,
};

/**
 * Schema for validateNamedNode
 */
export const validateNamedNodeParamsSchema = z.tuple([z.unknown()]);

export const validateNamedNodeReturnSchema = z.boolean();

export const validateNamedNodeSchema = {
  params: validateNamedNodeParamsSchema,
  returns: validateNamedNodeReturnSchema,
};

/**
 * Schema for validateBlankNode
 */
export const validateBlankNodeParamsSchema = z.tuple([z.unknown()]);

export const validateBlankNodeReturnSchema = z.boolean();

export const validateBlankNodeSchema = {
  params: validateBlankNodeParamsSchema,
  returns: validateBlankNodeReturnSchema,
};

/**
 * Schema for validateTerm
 */
export const validateTermParamsSchema = z.tuple([z.unknown()]);

export const validateTermReturnSchema = z.boolean();

export const validateTermSchema = {
  params: validateTermParamsSchema,
  returns: validateTermReturnSchema,
};

/**
 * Schema for validateQuad
 */
export const validateQuadParamsSchema = z.tuple([z.unknown()]);

export const validateQuadReturnSchema = z.boolean();

export const validateQuadSchema = {
  params: validateQuadParamsSchema,
  returns: validateQuadReturnSchema,
};

/**
 * Schema for validateQuadJSON
 */
export const validateQuadJSONParamsSchema = z.tuple([z.unknown()]);

export const validateQuadJSONReturnSchema = z.boolean();

export const validateQuadJSONSchema = {
  params: validateQuadJSONParamsSchema,
  returns: validateQuadJSONReturnSchema,
};

/**
 * Schema for validateTurtle
 */
export const validateTurtleParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const validateTurtleReturnSchema = z.unknown();

export const validateTurtleSchema = {
  params: validateTurtleParamsSchema,
  returns: validateTurtleReturnSchema,
};

/**
 * Schema for validateNQuads
 */
export const validateNQuadsParamsSchema = z.tuple([z.string()]);

export const validateNQuadsReturnSchema = z.unknown();

export const validateNQuadsSchema = {
  params: validateNQuadsParamsSchema,
  returns: validateNQuadsReturnSchema,
};

/**
 * Schema for validateJSONLD
 */
export const validateJSONLDParamsSchema = z.tuple([z.unknown()]);

export const validateJSONLDReturnSchema = z.unknown();

export const validateJSONLDSchema = {
  params: validateJSONLDParamsSchema,
  returns: validateJSONLDReturnSchema,
};

/**
 * Schema for validateSPARQL
 */
export const validateSPARQLParamsSchema = z.tuple([z.string()]);

export const validateSPARQLReturnSchema = z.unknown();

export const validateSPARQLSchema = {
  params: validateSPARQLParamsSchema,
  returns: validateSPARQLReturnSchema,
};

/**
 * Schema for validateSHACL
 */
export const validateSHACLParamsSchema = z.tuple([z.string()]);

export const validateSHACLReturnSchema = z.unknown();

export const validateSHACLSchema = {
  params: validateSHACLParamsSchema,
  returns: validateSHACLReturnSchema,
};

/**
 * Schema for validateStore
 */
export const validateStoreParamsSchema = z.tuple([z.unknown()]);

export const validateStoreReturnSchema = z.unknown();

export const validateStoreSchema = {
  params: validateStoreParamsSchema,
  returns: validateStoreReturnSchema,
};

/**
 * Schema for validateRDFConstraints
 */
export const validateRDFConstraintsParamsSchema = z.tuple([z.unknown()]);

export const validateRDFConstraintsReturnSchema = z.unknown();

export const validateRDFConstraintsSchema = {
  params: validateRDFConstraintsParamsSchema,
  returns: validateRDFConstraintsReturnSchema,
};

/**
 * Schema for validateCommonPatterns
 */
export const validateCommonPatternsParamsSchema = z.tuple([z.unknown()]);

export const validateCommonPatternsReturnSchema = z.unknown();

export const validateCommonPatternsSchema = {
  params: validateCommonPatternsParamsSchema,
  returns: validateCommonPatternsReturnSchema,
};

/**
 * Schema for createValidationPipeline
 */
export const createValidationPipelineParamsSchema = z.tuple([z.unknown()]);

export const createValidationPipelineReturnSchema = z.unknown();

export const createValidationPipelineSchema = {
  params: createValidationPipelineParamsSchema,
  returns: createValidationPipelineReturnSchema,
};

export default {
  validateIRI: validateIRISchema,
  validateLiteral: validateLiteralSchema,
  validateNamedNode: validateNamedNodeSchema,
  validateBlankNode: validateBlankNodeSchema,
  validateTerm: validateTermSchema,
  validateQuad: validateQuadSchema,
  validateQuadJSON: validateQuadJSONSchema,
  validateTurtle: validateTurtleSchema,
  validateNQuads: validateNQuadsSchema,
  validateJSONLD: validateJSONLDSchema,
  validateSPARQL: validateSPARQLSchema,
  validateSHACL: validateSHACLSchema,
  validateStore: validateStoreSchema,
  validateRDFConstraints: validateRDFConstraintsSchema,
  validateCommonPatterns: validateCommonPatternsSchema,
  createValidationPipeline: createValidationPipelineSchema
};
