/**
 * Auto-generated Zod schemas for use-reasoner.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useReasoner
 */
export const useReasonerParamsSchema = z.tuple([z.unknown().optional()]);

export const useReasonerReturnSchema = z.unknown();

export const useReasonerSchema = {
  params: useReasonerParamsSchema,
  returns: useReasonerReturnSchema,
};

export default {
  useReasoner: useReasonerSchema
};
