/**
 * Auto-generated Zod schemas for use-validator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useValidator
 */
export const useValidatorParamsSchema = z.tuple([z.unknown().optional()]);

export const useValidatorReturnSchema = z.unknown();

export const useValidatorSchema = {
  params: useValidatorParamsSchema,
  returns: useValidatorReturnSchema,
};

export default {
  useValidator: useValidatorSchema
};
