/**
 * Auto-generated Zod schemas for use-turtle.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useTurtle
 */
export const useTurtleParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional()]);

export const useTurtleReturnSchema = z.unknown();

export const useTurtleSchema = {
  params: useTurtleParamsSchema,
  returns: useTurtleReturnSchema,
};

export default {
  useTurtle: useTurtleSchema
};
