/**
 * Auto-generated Zod schemas for use-graph.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useGraph
 */
export const useGraphParamsSchema = z.tuple([]);

export const useGraphReturnSchema = z.unknown();

export const useGraphSchema = {
  params: useGraphParamsSchema,
  returns: useGraphReturnSchema,
};

export default {
  useGraph: useGraphSchema
};
