/**
 * Auto-generated Zod schemas for use-terms.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useTerms
 */
export const useTermsParamsSchema = z.tuple([z.unknown().optional()]);

export const useTermsReturnSchema = z.unknown();

export const useTermsSchema = {
  params: useTermsParamsSchema,
  returns: useTermsReturnSchema,
};

export default {
  useTerms: useTermsSchema
};
