/**
 * Auto-generated Zod schemas for use-zod.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useZod
 */
export const useZodParamsSchema = z.tuple([z.unknown().optional()]);

export const useZodReturnSchema = z.unknown();

export const useZodSchema = {
  params: useZodParamsSchema,
  returns: useZodReturnSchema,
};

export default {
  useZod: useZodSchema
};
