/**
 * Auto-generated Zod schemas for use-prefixes.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for usePrefixes
 */
export const usePrefixesParamsSchema = z.tuple([z.unknown()]);

export const usePrefixesReturnSchema = z.unknown();

export const usePrefixesSchema = {
  params: usePrefixesParamsSchema,
  returns: usePrefixesReturnSchema,
};

export default {
  usePrefixes: usePrefixesSchema
};
