/**
 * Auto-generated Zod schemas for use-canon.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useCanon
 */
export const useCanonParamsSchema = z.tuple([z.unknown().optional()]);

export const useCanonReturnSchema = z.unknown();

export const useCanonSchema = {
  params: useCanonParamsSchema,
  returns: useCanonReturnSchema,
};

export default {
  useCanon: useCanonSchema
};
