/**
 * Auto-generated Zod schemas for executor-sync.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for executeQuerySync
 */
export const executeQuerySyncParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const executeQuerySyncReturnSchema = z.unknown();

export const executeQuerySyncSchema = {
  params: executeQuerySyncParamsSchema,
  returns: executeQuerySyncReturnSchema,
};

/**
 * Schema for executeSelectSync
 */
export const executeSelectSyncParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const executeSelectSyncReturnSchema = z.unknown();

export const executeSelectSyncSchema = {
  params: executeSelectSyncParamsSchema,
  returns: executeSelectSyncReturnSchema,
};

/**
 * Schema for executeConstructSync
 */
export const executeConstructSyncParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const executeConstructSyncReturnSchema = z.unknown();

export const executeConstructSyncSchema = {
  params: executeConstructSyncParamsSchema,
  returns: executeConstructSyncReturnSchema,
};

/**
 * Schema for executeAskSync
 */
export const executeAskSyncParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const executeAskSyncReturnSchema = z.boolean();

export const executeAskSyncSchema = {
  params: executeAskSyncParamsSchema,
  returns: executeAskSyncReturnSchema,
};

/**
 * Schema for prepareQuerySync
 */
export const prepareQuerySyncParamsSchema = z.tuple([z.string()]);

export const prepareQuerySyncReturnSchema = z.unknown();

export const prepareQuerySyncSchema = {
  params: prepareQuerySyncParamsSchema,
  returns: prepareQuerySyncReturnSchema,
};

export default {
  executeQuerySync: executeQuerySyncSchema,
  executeSelectSync: executeSelectSyncSchema,
  executeConstructSync: executeConstructSyncSchema,
  executeAskSync: executeAskSyncSchema,
  prepareQuerySync: prepareQuerySyncSchema
};
