/**
 * Auto-generated Zod schemas for executor.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for executeQuery
 */
export const executeQueryParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const executeQueryReturnSchema = z.unknown();

export const executeQuerySchema = {
  params: executeQueryParamsSchema,
  returns: executeQueryReturnSchema,
};

/**
 * Schema for prepareQuery
 */
export const prepareQueryParamsSchema = z.tuple([z.string()]);

export const prepareQueryReturnSchema = z.unknown();

export const prepareQuerySchema = {
  params: prepareQueryParamsSchema,
  returns: prepareQueryReturnSchema,
};

/**
 * Schema for executeSelect
 */
export const executeSelectParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const executeSelectReturnSchema = z.unknown();

export const executeSelectSchema = {
  params: executeSelectParamsSchema,
  returns: executeSelectReturnSchema,
};

/**
 * Schema for executeConstruct
 */
export const executeConstructParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const executeConstructReturnSchema = z.unknown();

export const executeConstructSchema = {
  params: executeConstructParamsSchema,
  returns: executeConstructReturnSchema,
};

/**
 * Schema for executeAsk
 */
export const executeAskParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const executeAskReturnSchema = z.unknown();

export const executeAskSchema = {
  params: executeAskParamsSchema,
  returns: executeAskReturnSchema,
};

export default {
  executeQuery: executeQuerySchema,
  prepareQuery: prepareQuerySchema,
  executeSelect: executeSelectSchema,
  executeConstruct: executeConstructSchema,
  executeAsk: executeAskSchema
};
