# Fish completion for playground CLI
# Generated by papers-thesis-cli completions generator
#
# Installation:
#   1. Copy to ~/.config/fish/completions/playground.fish
#   2. Or copy to /usr/local/share/fish/vendor_completions.d/playground.fish

# Disable file completions by default
complete -c playground -f

# Helper function to check if we're in a specific command context
function __fish_playground_using_command
    set -l cmd (commandline -opc)
    set -l expected_cmd $argv[1]

    if test (count $cmd) -gt 1
        if test $cmd[2] = $expected_cmd
            return 0
        end
    end
    return 1
end

# Helper function to check if we're in a subcommand context
function __fish_playground_using_subcommand
    set -l cmd (commandline -opc)
    set -l expected_cmd $argv[1]
    set -l expected_subcmd $argv[2]

    if test (count $cmd) -gt 2
        if test $cmd[2] = $expected_cmd -a $cmd[3] = $expected_subcmd
            return 0
        end
    end
    return 1
end

# Helper function to check if no command is given yet
function __fish_playground_needs_command
    set -l cmd (commandline -opc)
    if test (count $cmd) -eq 1
        return 0
    end
    return 1
end

# Helper function to check if command needs subcommand
function __fish_playground_needs_subcommand
    set -l cmd (commandline -opc)
    set -l expected_cmd $argv[1]

    if test (count $cmd) -eq 2
        if test $cmd[2] = $expected_cmd
            return 0
        end
    end
    return 1
end

# =====================================
# Global options (available everywhere)
# =====================================

complete -c playground -s h -l help -d "Show help information"
complete -c playground -s v -l verbose -d "Enable verbose output"
complete -c playground -s q -l quiet -d "Suppress non-essential output"
complete -c playground -s f -l format -d "Output format" -xa "json json-pretty yaml table latex csv"
complete -c playground -s o -l output -d "Output file path" -r
complete -c playground -s c -l config -d "Configuration file" -r
complete -c playground -l version -d "Show version information"

# =====================================
# Main commands
# =====================================

complete -c playground -n "__fish_playground_needs_command" -a "papers" -d "Manage research papers"
complete -c playground -n "__fish_playground_needs_command" -a "thesis" -d "Manage thesis documents"
complete -c playground -n "__fish_playground_needs_command" -a "config" -d "Manage CLI configuration"
complete -c playground -n "__fish_playground_needs_command" -a "meta" -d "Metadata and introspection"

# =====================================
# Subcommands and arguments
# =====================================

# papers subcommands
complete -c playground -n "__fish_playground_needs_subcommand papers" -a "generate" -d "Generate paper from template"
complete -c playground -n "__fish_playground_needs_subcommand papers" -a "list" -d "List available paper families"
complete -c playground -n "__fish_playground_needs_subcommand papers" -a "validate" -d "Validate paper structure"

# papers generate arguments
complete -c playground -n "__fish_playground_using_subcommand papers generate" -s F -l family -d "Paper family/structure type" -xa "imrad dsr argument contribution"
complete -c playground -n "__fish_playground_using_subcommand papers generate" -s t -l title -d "Paper title"
complete -c playground -n "__fish_playground_using_subcommand papers generate" -s a -l author -d "Author name"
complete -c playground -n "__fish_playground_using_subcommand papers generate" -l affiliation -d "Author affiliation"
complete -c playground -n "__fish_playground_using_subcommand papers generate" -l abstract -d "Paper abstract"
complete -c playground -n "__fish_playground_using_subcommand papers generate" -s o -l output -d "Output file path" -r
complete -c playground -n "__fish_playground_using_subcommand papers generate" -s f -l format -d "Output format" -xa "json latex yaml"

# papers list arguments
complete -c playground -n "__fish_playground_using_subcommand papers list" -s v -l verbose -d "Show detailed information"
complete -c playground -n "__fish_playground_using_subcommand papers list" -s f -l format -d "Output format" -xa "json yaml table"

# papers validate arguments
complete -c playground -n "__fish_playground_using_subcommand papers validate" -l strict -d "Enable strict validation"
complete -c playground -n "__fish_playground_using_subcommand papers validate" -s f -l format -d "Output format" -xa "json table"

# thesis subcommands
complete -c playground -n "__fish_playground_needs_subcommand thesis" -a "generate" -d "Generate thesis from template"
complete -c playground -n "__fish_playground_needs_subcommand thesis" -a "list" -d "List available thesis types"
complete -c playground -n "__fish_playground_needs_subcommand thesis" -a "schedule" -d "Manage thesis schedule"

# thesis generate arguments
complete -c playground -n "__fish_playground_using_subcommand thesis generate" -s T -l type -d "Thesis type" -xa "masters phd doctoral"
complete -c playground -n "__fish_playground_using_subcommand thesis generate" -s t -l title -d "Thesis title"
complete -c playground -n "__fish_playground_using_subcommand thesis generate" -s a -l author -d "Author name"
complete -c playground -n "__fish_playground_using_subcommand thesis generate" -l advisor -d "Advisor name"
complete -c playground -n "__fish_playground_using_subcommand thesis generate" -l institution -d "Institution name"
complete -c playground -n "__fish_playground_using_subcommand thesis generate" -l department -d "Department name"
complete -c playground -n "__fish_playground_using_subcommand thesis generate" -s o -l output -d "Output file path" -r
complete -c playground -n "__fish_playground_using_subcommand thesis generate" -s f -l format -d "Output format" -xa "json latex yaml"

# thesis list arguments
complete -c playground -n "__fish_playground_using_subcommand thesis list" -s v -l verbose -d "Show detailed information"
complete -c playground -n "__fish_playground_using_subcommand thesis list" -s f -l format -d "Output format" -xa "json yaml table"

# thesis schedule arguments
complete -c playground -n "__fish_playground_using_subcommand thesis schedule" -l milestone -d "Milestone name"
complete -c playground -n "__fish_playground_using_subcommand thesis schedule" -l date -d "Target date"

# config subcommands
complete -c playground -n "__fish_playground_needs_subcommand config" -a "list" -d "List all configuration values"
complete -c playground -n "__fish_playground_needs_subcommand config" -a "get" -d "Get a configuration value"
complete -c playground -n "__fish_playground_needs_subcommand config" -a "set" -d "Set a configuration value"
complete -c playground -n "__fish_playground_needs_subcommand config" -a "reset" -d "Reset configuration to defaults"

# config reset arguments
complete -c playground -n "__fish_playground_using_subcommand config reset" -l all -d "Reset all values"

# meta subcommands
complete -c playground -n "__fish_playground_needs_subcommand meta" -a "sparql" -d "Execute SPARQL query"
complete -c playground -n "__fish_playground_needs_subcommand meta" -a "schema" -d "Show schema information"
complete -c playground -n "__fish_playground_needs_subcommand meta" -a "version" -d "Show version information"
complete -c playground -n "__fish_playground_needs_subcommand meta" -a "completions" -d "Generate shell completions"

# meta sparql arguments
complete -c playground -n "__fish_playground_using_subcommand meta sparql" -s f -l format -d "Output format" -xa "json table csv"
complete -c playground -n "__fish_playground_using_subcommand meta sparql" -l file -d "Query file" -r

# meta schema arguments
complete -c playground -n "__fish_playground_using_subcommand meta schema" -s f -l format -d "Output format" -xa "json yaml turtle"

# meta completions arguments
complete -c playground -n "__fish_playground_using_subcommand meta completions" -l shell -d "Target shell" -xa "bash zsh fish powershell"
complete -c playground -n "__fish_playground_using_subcommand meta completions" -s o -l output -d "Output file" -r

# =====================================
# Dynamic completions (customizable)
# =====================================

# Function to get available paper families dynamically
function __fish_playground_paper_families
    echo "imrad"
    echo "dsr"
    echo "argument"
    echo "contribution"
end

# Function to get available thesis types dynamically
function __fish_playground_thesis_types
    echo "masters"
    echo "phd"
    echo "doctoral"
end

# Function to list available templates
function __fish_playground_templates
    # Can be customized to load from filesystem or knowledge graph
    __fish_playground_paper_families
    __fish_playground_thesis_types
end
