name: Integration Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: packages/integration-tests

      - name: Run integration tests
        run: timeout 300s pnpm test
        working-directory: packages/integration-tests
        env:
          NODE_ENV: test

      - name: Generate coverage report
        if: always()
        run: pnpm run test:coverage
        working-directory: packages/integration-tests

      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v3
        with:
          files: ./packages/integration-tests/coverage/lcov.info
          flags: integration-tests
          name: integration-coverage

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results-node-${{ matrix.node-version }}
          path: |
            packages/integration-tests/coverage/
            packages/integration-tests/.vitest/

      - name: Report test metrics
        if: always()
        run: |
          echo "## Integration Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Node Version: ${{ matrix.node-version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          pnpm test -- --reporter=json > test-results.json || true
          if [ -f test-results.json ]; then
            echo "Tests completed. See artifacts for details." >> $GITHUB_STEP_SUMMARY
          fi
        working-directory: packages/integration-tests

  performance-benchmarks:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    needs: integration-tests
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: packages/integration-tests

      - name: Run performance tests
        run: timeout 600s pnpm run test:performance
        working-directory: packages/integration-tests

      - name: Upload performance results
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: packages/integration-tests/coverage/

  notify:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [integration-tests, performance-benchmarks]
    if: failure()

    steps:
      - name: Send notification
        run: |
          echo "Integration tests failed for ${{ github.ref }}"
          echo "Check the workflow run for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
