/**
 * Auto-generated Zod schemas for browser.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createBrowserHookExecutor
 */
export const createBrowserHookExecutorParamsSchema = z.tuple([z.unknown().optional()]);

export const createBrowserHookExecutorReturnSchema = z.unknown();

export const createBrowserHookExecutorSchema = {
  params: createBrowserHookExecutorParamsSchema,
  returns: createBrowserHookExecutorReturnSchema,
};

/**
 * Schema for createBrowserConditionEvaluator
 */
export const createBrowserConditionEvaluatorParamsSchema = z.tuple([z.unknown().optional()]);

export const createBrowserConditionEvaluatorReturnSchema = z.unknown();

export const createBrowserConditionEvaluatorSchema = {
  params: createBrowserConditionEvaluatorParamsSchema,
  returns: createBrowserConditionEvaluatorReturnSchema,
};

/**
 * Schema for createBrowserPolicyPackManager
 */
export const createBrowserPolicyPackManagerParamsSchema = z.tuple([z.unknown().optional()]);

export const createBrowserPolicyPackManagerReturnSchema = z.unknown();

export const createBrowserPolicyPackManagerSchema = {
  params: createBrowserPolicyPackManagerParamsSchema,
  returns: createBrowserPolicyPackManagerReturnSchema,
};

/**
 * Schema for createBrowserFileResolver
 */
export const createBrowserFileResolverParamsSchema = z.tuple([z.unknown().optional()]);

export const createBrowserFileResolverReturnSchema = z.unknown();

export const createBrowserFileResolverSchema = {
  params: createBrowserFileResolverParamsSchema,
  returns: createBrowserFileResolverReturnSchema,
};

/**
 * Schema for createBrowserResolutionLayer
 */
export const createBrowserResolutionLayerParamsSchema = z.tuple([z.unknown().optional()]);

export const createBrowserResolutionLayerReturnSchema = z.unknown();

export const createBrowserResolutionLayerSchema = {
  params: createBrowserResolutionLayerParamsSchema,
  returns: createBrowserResolutionLayerReturnSchema,
};

/**
 * Schema for createBrowserKnowledgeHookManager
 */
export const createBrowserKnowledgeHookManagerParamsSchema = z.tuple([z.unknown().optional()]);

export const createBrowserKnowledgeHookManagerReturnSchema = z.unknown();

export const createBrowserKnowledgeHookManagerSchema = {
  params: createBrowserKnowledgeHookManagerParamsSchema,
  returns: createBrowserKnowledgeHookManagerReturnSchema,
};

export default {
  createBrowserHookExecutor: createBrowserHookExecutorSchema,
  createBrowserConditionEvaluator: createBrowserConditionEvaluatorSchema,
  createBrowserPolicyPackManager: createBrowserPolicyPackManagerSchema,
  createBrowserFileResolver: createBrowserFileResolverSchema,
  createBrowserResolutionLayer: createBrowserResolutionLayerSchema,
  createBrowserKnowledgeHookManager: createBrowserKnowledgeHookManagerSchema
};
