/**
 * Auto-generated Zod schemas for canonicalize.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for canonicalize
 */
export const canonicalizeParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const canonicalizeReturnSchema = z.unknown();

export const canonicalizeSchema = {
  params: canonicalizeParamsSchema,
  returns: canonicalizeReturnSchema,
};

/**
 * Schema for isIsomorphic
 */
export const isIsomorphicParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const isIsomorphicReturnSchema = z.unknown();

export const isIsomorphicSchema = {
  params: isIsomorphicParamsSchema,
  returns: isIsomorphicReturnSchema,
};

/**
 * Schema for getCanonicalHash
 */
export const getCanonicalHashParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const getCanonicalHashReturnSchema = z.unknown();

export const getCanonicalHashSchema = {
  params: getCanonicalHashParamsSchema,
  returns: getCanonicalHashReturnSchema,
};

/**
 * Schema for groupByIsomorphism
 */
export const groupByIsomorphismParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const groupByIsomorphismReturnSchema = z.unknown();

export const groupByIsomorphismSchema = {
  params: groupByIsomorphismParamsSchema,
  returns: groupByIsomorphismReturnSchema,
};

/**
 * Schema for findDuplicates
 */
export const findDuplicatesParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const findDuplicatesReturnSchema = z.unknown();

export const findDuplicatesSchema = {
  params: findDuplicatesParamsSchema,
  returns: findDuplicatesReturnSchema,
};

/**
 * Schema for getCanonicalizationStats
 */
export const getCanonicalizationStatsParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const getCanonicalizationStatsReturnSchema = z.unknown();

export const getCanonicalizationStatsSchema = {
  params: getCanonicalizationStatsParamsSchema,
  returns: getCanonicalizationStatsReturnSchema,
};

/**
 * Schema for createCanonicalizationSession
 */
export const createCanonicalizationSessionParamsSchema = z.tuple([z.unknown().optional()]);

export const createCanonicalizationSessionReturnSchema = z.unknown();

export const createCanonicalizationSessionSchema = {
  params: createCanonicalizationSessionParamsSchema,
  returns: createCanonicalizationSessionReturnSchema,
};

export default {
  canonicalize: canonicalizeSchema,
  isIsomorphic: isIsomorphicSchema,
  getCanonicalHash: getCanonicalHashSchema,
  groupByIsomorphism: groupByIsomorphismSchema,
  findDuplicates: findDuplicatesSchema,
  getCanonicalizationStats: getCanonicalizationStatsSchema,
  createCanonicalizationSession: createCanonicalizationSessionSchema
};
