/**
 * Auto-generated Zod schemas for dark-matter-core.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createKnowledgeSubstrateCore
 */
export const createKnowledgeSubstrateCoreParamsSchema = z.tuple([z.unknown().optional()]);

export const createKnowledgeSubstrateCoreReturnSchema = z.unknown();

export const createKnowledgeSubstrateCoreSchema = {
  params: createKnowledgeSubstrateCoreParamsSchema,
  returns: createKnowledgeSubstrateCoreReturnSchema,
};

/**
 * Schema for createDarkMatterCore
 */
export const createDarkMatterCoreParamsSchema = z.tuple([z.unknown().optional()]);

export const createDarkMatterCoreReturnSchema = z.unknown();

export const createDarkMatterCoreSchema = {
  params: createDarkMatterCoreParamsSchema,
  returns: createDarkMatterCoreReturnSchema,
};

export default {
  createKnowledgeSubstrateCore: createKnowledgeSubstrateCoreSchema,
  createDarkMatterCore: createDarkMatterCoreSchema
};
