/**
 * Auto-generated Zod schemas for effect-sandbox.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createSandboxedHook
 */
export const createSandboxedHookParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const createSandboxedHookReturnSchema = z.unknown();

export const createSandboxedHookSchema = {
  params: createSandboxedHookParamsSchema,
  returns: createSandboxedHookReturnSchema,
};

/**
 * Schema for createEffectSandbox
 */
export const createEffectSandboxParamsSchema = z.tuple([z.unknown().optional()]);

export const createEffectSandboxReturnSchema = z.unknown();

export const createEffectSandboxSchema = {
  params: createEffectSandboxParamsSchema,
  returns: createEffectSandboxReturnSchema,
};

export default {
  createSandboxedHook: createSandboxedHookSchema,
  createEffectSandbox: createEffectSandboxSchema
};
