/**
 * Auto-generated Zod schemas for hook-management.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for registerHook
 */
export const registerHookParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const registerHookReturnSchema = z.unknown();

export const registerHookSchema = {
  params: registerHookParamsSchema,
  returns: registerHookReturnSchema,
};

/**
 * Schema for deregisterHook
 */
export const deregisterHookParamsSchema = z.tuple([z.string()]);

export const deregisterHookReturnSchema = z.boolean();

export const deregisterHookSchema = {
  params: deregisterHookParamsSchema,
  returns: deregisterHookReturnSchema,
};

/**
 * Schema for evaluateHook
 */
export const evaluateHookParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const evaluateHookReturnSchema = z.unknown();

export const evaluateHookSchema = {
  params: evaluateHookParamsSchema,
  returns: evaluateHookReturnSchema,
};

/**
 * Schema for getRegisteredHooks
 */
export const getRegisteredHooksParamsSchema = z.tuple([]);

export const getRegisteredHooksReturnSchema = z.unknown();

export const getRegisteredHooksSchema = {
  params: getRegisteredHooksParamsSchema,
  returns: getRegisteredHooksReturnSchema,
};

/**
 * Schema for resetGlobalHookManager
 */
export const resetGlobalHookManagerParamsSchema = z.tuple([]);

export const resetGlobalHookManagerReturnSchema = z.unknown();

export const resetGlobalHookManagerSchema = {
  params: resetGlobalHookManagerParamsSchema,
  returns: resetGlobalHookManagerReturnSchema,
};

export default {
  registerHook: registerHookSchema,
  deregisterHook: deregisterHookSchema,
  evaluateHook: evaluateHookSchema,
  getRegisteredHooks: getRegisteredHooksSchema,
  resetGlobalHookManager: resetGlobalHookManagerSchema
};
