/**
 * Auto-generated Zod schemas for hook-executor.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for executeHook
 */
export const executeHookParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const executeHookReturnSchema = z.unknown();

export const executeHookSchema = {
  params: executeHookParamsSchema,
  returns: executeHookReturnSchema,
};

/**
 * Schema for createHookExecutor
 */
export const createHookExecutorParamsSchema = z.tuple([z.unknown().optional()]);

export const createHookExecutorReturnSchema = z.unknown();

export const createHookExecutorSchema = {
  params: createHookExecutorParamsSchema,
  returns: createHookExecutorReturnSchema,
};

/**
 * Schema for validateHookForExecution
 */
export const validateHookForExecutionParamsSchema = z.tuple([z.unknown()]);

export const validateHookForExecutionReturnSchema = z.unknown();

export const validateHookForExecutionSchema = {
  params: validateHookForExecutionParamsSchema,
  returns: validateHookForExecutionReturnSchema,
};

export default {
  executeHook: executeHookSchema,
  createHookExecutor: createHookExecutorSchema,
  validateHookForExecution: validateHookForExecutionSchema
};
