/**
 * Auto-generated Zod schemas for lite.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for parseTurtle
 */
export const parseTurtleParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const parseTurtleReturnSchema = z.unknown();

export const parseTurtleSchema = {
  params: parseTurtleParamsSchema,
  returns: parseTurtleReturnSchema,
};

/**
 * Schema for toTurtle
 */
export const toTurtleParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const toTurtleReturnSchema = z.unknown();

export const toTurtleSchema = {
  params: toTurtleParamsSchema,
  returns: toTurtleReturnSchema,
};

/**
 * Schema for toNQuads
 */
export const toNQuadsParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const toNQuadsReturnSchema = z.unknown();

export const toNQuadsSchema = {
  params: toNQuadsParamsSchema,
  returns: toNQuadsReturnSchema,
};

/**
 * Schema for createQuad
 */
export const createQuadParamsSchema = z.tuple([z.string(), z.string(), z.unknown(), z.unknown()]);

export const createQuadReturnSchema = z.unknown();

export const createQuadSchema = {
  params: createQuadParamsSchema,
  returns: createQuadReturnSchema,
};

export default {
  parseTurtle: parseTurtleSchema,
  toTurtle: toTurtleSchema,
  toNQuads: toNQuadsSchema,
  createQuad: createQuadSchema
};
