/**
 * Auto-generated Zod schemas for lockchain-writer-browser.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createBrowserLockchainWriter
 */
export const createBrowserLockchainWriterParamsSchema = z.tuple([z.unknown().optional()]);

export const createBrowserLockchainWriterReturnSchema = z.unknown();

export const createBrowserLockchainWriterSchema = {
  params: createBrowserLockchainWriterParamsSchema,
  returns: createBrowserLockchainWriterReturnSchema,
};

export default {
  createBrowserLockchainWriter: createBrowserLockchainWriterSchema
};
