/**
 * Auto-generated Zod schemas for observability.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createObservabilityManager
 */
export const createObservabilityManagerParamsSchema = z.tuple([z.unknown().optional()]);

export const createObservabilityManagerReturnSchema = z.unknown();

export const createObservabilityManagerSchema = {
  params: createObservabilityManagerParamsSchema,
  returns: createObservabilityManagerReturnSchema,
};

export default {
  createObservabilityManager: createObservabilityManagerSchema
};
