/**
 * Auto-generated Zod schemas for parse.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for parseTurtle
 */
export const parseTurtleParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const parseTurtleReturnSchema = z.unknown();

export const parseTurtleSchema = {
  params: parseTurtleParamsSchema,
  returns: parseTurtleReturnSchema,
};

/**
 * Schema for toTurtle
 */
export const toTurtleParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const toTurtleReturnSchema = z.unknown();

export const toTurtleSchema = {
  params: toTurtleParamsSchema,
  returns: toTurtleReturnSchema,
};

/**
 * Schema for toNQuads
 */
export const toNQuadsParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const toNQuadsReturnSchema = z.unknown();

export const toNQuadsSchema = {
  params: toNQuadsParamsSchema,
  returns: toNQuadsReturnSchema,
};

/**
 * Schema for parseJsonLd
 */
export const parseJsonLdParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const parseJsonLdReturnSchema = z.unknown();

export const parseJsonLdSchema = {
  params: parseJsonLdParamsSchema,
  returns: parseJsonLdReturnSchema,
};

/**
 * Schema for toJsonLd
 */
export const toJsonLdParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const toJsonLdReturnSchema = z.unknown();

export const toJsonLdSchema = {
  params: toJsonLdParamsSchema,
  returns: toJsonLdReturnSchema,
};

export default {
  parseTurtle: parseTurtleSchema,
  toTurtle: toTurtleSchema,
  toNQuads: toNQuadsSchema,
  parseJsonLd: parseJsonLdSchema,
  toJsonLd: toJsonLdSchema
};
