/**
 * Auto-generated Zod schemas for policy-pack.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createPolicyPackFromDirectory
 */
export const createPolicyPackFromDirectoryParamsSchema = z.tuple([z.string()]);

export const createPolicyPackFromDirectoryReturnSchema = z.unknown();

export const createPolicyPackFromDirectorySchema = {
  params: createPolicyPackFromDirectoryParamsSchema,
  returns: createPolicyPackFromDirectoryReturnSchema,
};

/**
 * Schema for createPolicyPackManifest
 */
export const createPolicyPackManifestParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const createPolicyPackManifestReturnSchema = z.unknown();

export const createPolicyPackManifestSchema = {
  params: createPolicyPackManifestParamsSchema,
  returns: createPolicyPackManifestReturnSchema,
};

export default {
  createPolicyPackFromDirectory: createPolicyPackFromDirectorySchema,
  createPolicyPackManifest: createPolicyPackManifestSchema
};
