/**
 * Auto-generated Zod schemas for query-cache.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for getQueryEngine
 */
export const getQueryEngineParamsSchema = z.tuple([z.unknown().optional()]);

export const getQueryEngineReturnSchema = z.unknown();

export const getQueryEngineSchema = {
  params: getQueryEngineParamsSchema,
  returns: getQueryEngineReturnSchema,
};

/**
 * Schema for getQueryEngineAsync
 */
export const getQueryEngineAsyncParamsSchema = z.tuple([z.unknown().optional()]);

export const getQueryEngineAsyncReturnSchema = z.unknown();

export const getQueryEngineAsyncSchema = {
  params: getQueryEngineAsyncParamsSchema,
  returns: getQueryEngineAsyncReturnSchema,
};

/**
 * Schema for isQueryEngineHealthy
 */
export const isQueryEngineHealthyParamsSchema = z.tuple([]);

export const isQueryEngineHealthyReturnSchema = z.boolean();

export const isQueryEngineHealthySchema = {
  params: isQueryEngineHealthyParamsSchema,
  returns: isQueryEngineHealthyReturnSchema,
};

/**
 * Schema for getInitializationStatus
 */
export const getInitializationStatusParamsSchema = z.tuple([]);

export const getInitializationStatusReturnSchema = z.unknown();

export const getInitializationStatusSchema = {
  params: getInitializationStatusParamsSchema,
  returns: getInitializationStatusReturnSchema,
};

/**
 * Schema for resetQueryEngine
 */
export const resetQueryEngineParamsSchema = z.tuple([]);

export const resetQueryEngineReturnSchema = z.unknown();

export const resetQueryEngineSchema = {
  params: resetQueryEngineParamsSchema,
  returns: resetQueryEngineReturnSchema,
};

/**
 * Schema for getQueryHash
 */
export const getQueryHashParamsSchema = z.tuple([z.string()]);

export const getQueryHashReturnSchema = z.string();

export const getQueryHashSchema = {
  params: getQueryHashParamsSchema,
  returns: getQueryHashReturnSchema,
};

/**
 * Schema for isQueryCached
 */
export const isQueryCachedParamsSchema = z.tuple([z.string()]);

export const isQueryCachedReturnSchema = z.boolean();

export const isQueryCachedSchema = {
  params: isQueryCachedParamsSchema,
  returns: isQueryCachedReturnSchema,
};

/**
 * Schema for cacheFileContent
 */
export const cacheFileContentParamsSchema = z.tuple([z.string(), z.string()]);

export const cacheFileContentReturnSchema = z.unknown();

export const cacheFileContentSchema = {
  params: cacheFileContentParamsSchema,
  returns: cacheFileContentReturnSchema,
};

/**
 * Schema for getCachedFileContent
 */
export const getCachedFileContentParamsSchema = z.tuple([z.string()]);

export const getCachedFileContentReturnSchema = z.unknown();

export const getCachedFileContentSchema = {
  params: getCachedFileContentParamsSchema,
  returns: getCachedFileContentReturnSchema,
};

/**
 * Schema for getCacheStats
 */
export const getCacheStatsParamsSchema = z.tuple([]);

export const getCacheStatsReturnSchema = z.unknown();

export const getCacheStatsSchema = {
  params: getCacheStatsParamsSchema,
  returns: getCacheStatsReturnSchema,
};

/**
 * Schema for clearCaches
 */
export const clearCachesParamsSchema = z.tuple([]);

export const clearCachesReturnSchema = z.unknown();

export const clearCachesSchema = {
  params: clearCachesParamsSchema,
  returns: clearCachesReturnSchema,
};

/**
 * Schema for shutdown
 */
export const shutdownParamsSchema = z.tuple([]);

export const shutdownReturnSchema = z.unknown();

export const shutdownSchema = {
  params: shutdownParamsSchema,
  returns: shutdownReturnSchema,
};

export default {
  getQueryEngine: getQueryEngineSchema,
  getQueryEngineAsync: getQueryEngineAsyncSchema,
  isQueryEngineHealthy: isQueryEngineHealthySchema,
  getInitializationStatus: getInitializationStatusSchema,
  resetQueryEngine: resetQueryEngineSchema,
  getQueryHash: getQueryHashSchema,
  isQueryCached: isQueryCachedSchema,
  cacheFileContent: cacheFileContentSchema,
  getCachedFileContent: getCachedFileContentSchema,
  getCacheStats: getCacheStatsSchema,
  clearCaches: clearCachesSchema,
  shutdown: shutdownSchema
};
