/**
 * Auto-generated Zod schemas for query-optimizer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createQueryOptimizer
 */
export const createQueryOptimizerParamsSchema = z.tuple([z.unknown().optional()]);

export const createQueryOptimizerReturnSchema = z.unknown();

export const createQueryOptimizerSchema = {
  params: createQueryOptimizerParamsSchema,
  returns: createQueryOptimizerReturnSchema,
};

export default {
  createQueryOptimizer: createQueryOptimizerSchema
};
