/**
 * Auto-generated Zod schemas for query.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for query
 */
export const queryParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const queryReturnSchema = z.unknown();

export const querySchema = {
  params: queryParamsSchema,
  returns: queryReturnSchema,
};

/**
 * Schema for select
 */
export const selectParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const selectReturnSchema = z.unknown();

export const selectSchema = {
  params: selectParamsSchema,
  returns: selectReturnSchema,
};

/**
 * Schema for ask
 */
export const askParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const askReturnSchema = z.unknown();

export const askSchema = {
  params: askParamsSchema,
  returns: askReturnSchema,
};

/**
 * Schema for construct
 */
export const constructParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const constructReturnSchema = z.unknown();

export const constructSchema = {
  params: constructParamsSchema,
  returns: constructReturnSchema,
};

/**
 * Schema for describe
 */
export const describeParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const describeReturnSchema = z.unknown();

export const describeSchema = {
  params: describeParamsSchema,
  returns: describeReturnSchema,
};

/**
 * Schema for update
 */
export const updateParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const updateReturnSchema = z.unknown();

export const updateSchema = {
  params: updateParamsSchema,
  returns: updateReturnSchema,
};

/**
 * Schema for getQueryStats
 */
export const getQueryStatsParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const getQueryStatsReturnSchema = z.unknown();

export const getQueryStatsSchema = {
  params: getQueryStatsParamsSchema,
  returns: getQueryStatsReturnSchema,
};

export default {
  query: querySchema,
  select: selectSchema,
  ask: askSchema,
  construct: constructSchema,
  describe: describeSchema,
  update: updateSchema,
  getQueryStats: getQueryStatsSchema
};
