/**
 * Auto-generated Zod schemas for reason.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for reason
 */
export const reasonParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const reasonReturnSchema = z.unknown();

export const reasonSchema = {
  params: reasonParamsSchema,
  returns: reasonReturnSchema,
};

/**
 * Schema for reasonMultiple
 */
export const reasonMultipleParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const reasonMultipleReturnSchema = z.unknown();

export const reasonMultipleSchema = {
  params: reasonMultipleParamsSchema,
  returns: reasonMultipleReturnSchema,
};

/**
 * Schema for extractInferred
 */
export const extractInferredParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const extractInferredReturnSchema = z.unknown();

export const extractInferredSchema = {
  params: extractInferredParamsSchema,
  returns: extractInferredReturnSchema,
};

/**
 * Schema for getReasoningStats
 */
export const getReasoningStatsParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const getReasoningStatsReturnSchema = z.unknown();

export const getReasoningStatsSchema = {
  params: getReasoningStatsParamsSchema,
  returns: getReasoningStatsReturnSchema,
};

/**
 * Schema for validateRules
 */
export const validateRulesParamsSchema = z.tuple([z.unknown()]);

export const validateRulesReturnSchema = z.unknown();

export const validateRulesSchema = {
  params: validateRulesParamsSchema,
  returns: validateRulesReturnSchema,
};

/**
 * Schema for createReasoningSession
 */
export const createReasoningSessionParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const createReasoningSessionReturnSchema = z.unknown();

export const createReasoningSessionSchema = {
  params: createReasoningSessionParamsSchema,
  returns: createReasoningSessionReturnSchema,
};

export default {
  reason: reasonSchema,
  reasonMultiple: reasonMultipleSchema,
  extractInferred: extractInferredSchema,
  getReasoningStats: getReasoningStatsSchema,
  validateRules: validateRulesSchema,
  createReasoningSession: createReasoningSessionSchema
};
