/**
 * Auto-generated Zod schemas for resolution-layer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createResolutionLayer
 */
export const createResolutionLayerParamsSchema = z.tuple([z.unknown().optional()]);

export const createResolutionLayerReturnSchema = z.unknown();

export const createResolutionLayerSchema = {
  params: createResolutionLayerParamsSchema,
  returns: createResolutionLayerReturnSchema,
};

export default {
  createResolutionLayer: createResolutionLayerSchema
};
