/**
 * Auto-generated Zod schemas for schemas.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateKnowledgeHook
 */
export const validateKnowledgeHookParamsSchema = z.tuple([z.any()]);

export const validateKnowledgeHookReturnSchema = z.unknown();

export const validateKnowledgeHookSchema = {
  params: validateKnowledgeHookParamsSchema,
  returns: validateKnowledgeHookReturnSchema,
};

/**
 * Schema for validateHookEvent
 */
export const validateHookEventParamsSchema = z.tuple([z.any()]);

export const validateHookEventReturnSchema = z.unknown();

export const validateHookEventSchema = {
  params: validateHookEventParamsSchema,
  returns: validateHookEventReturnSchema,
};

/**
 * Schema for validateCondition
 */
export const validateConditionParamsSchema = z.tuple([z.any()]);

export const validateConditionReturnSchema = z.unknown();

export const validateConditionSchema = {
  params: validateConditionParamsSchema,
  returns: validateConditionReturnSchema,
};

/**
 * Schema for validateManagerConfig
 */
export const validateManagerConfigParamsSchema = z.tuple([z.any()]);

export const validateManagerConfigReturnSchema = z.unknown();

export const validateManagerConfigSchema = {
  params: validateManagerConfigParamsSchema,
  returns: validateManagerConfigReturnSchema,
};

/**
 * Schema for validateTransactionDelta
 */
export const validateTransactionDeltaParamsSchema = z.tuple([z.any()]);

export const validateTransactionDeltaReturnSchema = z.unknown();

export const validateTransactionDeltaSchema = {
  params: validateTransactionDeltaParamsSchema,
  returns: validateTransactionDeltaReturnSchema,
};

/**
 * Schema for createKnowledgeHook
 */
export const createKnowledgeHookParamsSchema = z.tuple([z.any()]);

export const createKnowledgeHookReturnSchema = z.unknown();

export const createKnowledgeHookSchema = {
  params: createKnowledgeHookParamsSchema,
  returns: createKnowledgeHookReturnSchema,
};

/**
 * Schema for createHookEvent
 */
export const createHookEventParamsSchema = z.tuple([z.any()]);

export const createHookEventReturnSchema = z.unknown();

export const createHookEventSchema = {
  params: createHookEventParamsSchema,
  returns: createHookEventReturnSchema,
};

/**
 * Schema for createCondition
 */
export const createConditionParamsSchema = z.tuple([z.any()]);

export const createConditionReturnSchema = z.unknown();

export const createConditionSchema = {
  params: createConditionParamsSchema,
  returns: createConditionReturnSchema,
};

export default {
  validateKnowledgeHook: validateKnowledgeHookSchema,
  validateHookEvent: validateHookEventSchema,
  validateCondition: validateConditionSchema,
  validateManagerConfig: validateManagerConfigSchema,
  validateTransactionDelta: validateTransactionDeltaSchema,
  createKnowledgeHook: createKnowledgeHookSchema,
  createHookEvent: createHookEventSchema,
  createCondition: createConditionSchema
};
