/**
 * Auto-generated Zod schemas for security-validator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createSecurityValidator
 */
export const createSecurityValidatorParamsSchema = z.tuple([z.unknown().optional()]);

export const createSecurityValidatorReturnSchema = z.unknown();

export const createSecurityValidatorSchema = {
  params: createSecurityValidatorParamsSchema,
  returns: createSecurityValidatorReturnSchema,
};

export default {
  createSecurityValidator: createSecurityValidatorSchema
};
