/**
 * Auto-generated Zod schemas for validate.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateShacl
 */
export const validateShaclParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const validateShaclReturnSchema = z.unknown();

export const validateShaclSchema = {
  params: validateShaclParamsSchema,
  returns: validateShaclReturnSchema,
};

/**
 * Schema for validateShaclMultiple
 */
export const validateShaclMultipleParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const validateShaclMultipleReturnSchema = z.unknown();

export const validateShaclMultipleSchema = {
  params: validateShaclMultipleParamsSchema,
  returns: validateShaclMultipleReturnSchema,
};

/**
 * Schema for formatValidationReport
 */
export const formatValidationReportParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const formatValidationReportReturnSchema = z.unknown();

export const formatValidationReportSchema = {
  params: formatValidationReportParamsSchema,
  returns: formatValidationReportReturnSchema,
};

/**
 * Schema for hasValidationErrors
 */
export const hasValidationErrorsParamsSchema = z.tuple([z.unknown()]);

export const hasValidationErrorsReturnSchema = z.boolean();

export const hasValidationErrorsSchema = {
  params: hasValidationErrorsParamsSchema,
  returns: hasValidationErrorsReturnSchema,
};

/**
 * Schema for getValidationErrors
 */
export const getValidationErrorsParamsSchema = z.tuple([z.unknown()]);

export const getValidationErrorsReturnSchema = z.unknown();

export const getValidationErrorsSchema = {
  params: getValidationErrorsParamsSchema,
  returns: getValidationErrorsReturnSchema,
};

/**
 * Schema for getValidationWarnings
 */
export const getValidationWarningsParamsSchema = z.tuple([z.unknown()]);

export const getValidationWarningsReturnSchema = z.unknown();

export const getValidationWarningsSchema = {
  params: getValidationWarningsParamsSchema,
  returns: getValidationWarningsReturnSchema,
};

export default {
  validateShacl: validateShaclSchema,
  validateShaclMultiple: validateShaclMultipleSchema,
  formatValidationReport: formatValidationReportSchema,
  hasValidationErrors: hasValidationErrorsSchema,
  getValidationErrors: getValidationErrorsSchema,
  getValidationWarnings: getValidationWarningsSchema
};
