apiVersion: v1
kind: ConfigMap
metadata:
  name: knowd-config
  labels:
    app: knowd
data:
  config.yaml: |
    server:
      addr: ":8090"
      dataDir: "/data"
      coreURL: "native://"
      store: "disk"
      packs: "/data/packs"
      watchPacks: true

    telemetry:
      serviceName: "knowd"
      serviceVersion: "1.0.0"
      environment: "production"
      traceEnabled: true
      metricsEnabled: true
      sampleRatio: 1.0

    policy:
      hotReload: true
      validateOnLoad: true

    hooks:
      enabled: true
      maxConcurrency: 10
      timeout: "30s"

    cluster:
      mode: "follower"
      peerAddrs: ""
      mTLSCert: ""
      mTLSKey: ""
      mTLSCA: ""

    vector:
      enabled: true
      dimensions: 384
      indexType: "hnsw"

    wasm:
      enabled: true
      maxMemoryMB: 128
      enableWASI: true

    security:
      mTLSEnabled: false
      jwtEnabled: false
      corsEnabled: true
      corsOrigins: ["*"]

    logging:
      level: "info"
      format: "json"
      output: "stdout"
