apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowd-data-pvc
  labels:
    app: knowd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd  # Use appropriate storage class for your cloud provider
