/**
 * Auto-generated Zod schemas for reconcile.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for reconcile
 */
export const reconcileParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const reconcileReturnSchema = z.unknown();

export const reconcileSchema = {
  params: reconcileParamsSchema,
  returns: reconcileReturnSchema,
};

/**
 * Schema for defaultConflictResolver
 */
export const defaultConflictResolverParamsSchema = z.tuple([z.unknown()]);

export const defaultConflictResolverReturnSchema = z.string();

export const defaultConflictResolverSchema = {
  params: defaultConflictResolverParamsSchema,
  returns: defaultConflictResolverReturnSchema,
};

/**
 * Schema for currentWinsResolver
 */
export const currentWinsResolverParamsSchema = z.tuple([]);

export const currentWinsResolverReturnSchema = z.unknown();

export const currentWinsResolverSchema = {
  params: currentWinsResolverParamsSchema,
  returns: currentWinsResolverReturnSchema,
};

/**
 * Schema for strictResolver
 */
export const strictResolverParamsSchema = z.tuple([]);

export const strictResolverReturnSchema = z.unknown();

export const strictResolverSchema = {
  params: strictResolverParamsSchema,
  returns: strictResolverReturnSchema,
};

/**
 * Schema for customResolver
 */
export const customResolverParamsSchema = z.tuple([z.unknown()]);

export const customResolverReturnSchema = z.unknown();

export const customResolverSchema = {
  params: customResolverParamsSchema,
  returns: customResolverReturnSchema,
};

export default {
  reconcile: reconcileSchema,
  defaultConflictResolver: defaultConflictResolverSchema,
  currentWinsResolver: currentWinsResolverSchema,
  strictResolver: strictResolverSchema,
  customResolver: customResolverSchema
};
