/**
 * Auto-generated Zod schemas for schema.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateDelta
 */
export const validateDeltaParamsSchema = z.tuple([z.any()]);

export const validateDeltaReturnSchema = z.unknown();

export const validateDeltaSchema = {
  params: validateDeltaParamsSchema,
  returns: validateDeltaReturnSchema,
};

/**
 * Schema for validateDeltaOperation
 */
export const validateDeltaOperationParamsSchema = z.tuple([z.any()]);

export const validateDeltaOperationReturnSchema = z.unknown();

export const validateDeltaOperationSchema = {
  params: validateDeltaOperationParamsSchema,
  returns: validateDeltaOperationReturnSchema,
};

/**
 * Schema for validateDeltaReceipt
 */
export const validateDeltaReceiptParamsSchema = z.tuple([z.any()]);

export const validateDeltaReceiptReturnSchema = z.unknown();

export const validateDeltaReceiptSchema = {
  params: validateDeltaReceiptParamsSchema,
  returns: validateDeltaReceiptReturnSchema,
};

/**
 * Schema for validateDeltaConflict
 */
export const validateDeltaConflictParamsSchema = z.tuple([z.any()]);

export const validateDeltaConflictReturnSchema = z.unknown();

export const validateDeltaConflictSchema = {
  params: validateDeltaConflictParamsSchema,
  returns: validateDeltaConflictReturnSchema,
};

export default {
  validateDelta: validateDeltaSchema,
  validateDeltaOperation: validateDeltaOperationSchema,
  validateDeltaReceipt: validateDeltaReceiptSchema,
  validateDeltaConflict: validateDeltaConflictSchema
};
