/**
 * Auto-generated Zod schemas for project-structure.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for ProjectStructureLens
 */
export const ProjectStructureLensParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const ProjectStructureLensReturnSchema = z.unknown();

export const ProjectStructureLensSchema = {
  params: ProjectStructureLensParamsSchema,
  returns: ProjectStructureLensReturnSchema,
};

export default {
  ProjectStructureLens: ProjectStructureLensSchema
};
