/**
 * Auto-generated Zod schemas for consensus-manager.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createConsensusManager
 */
export const createConsensusManagerParamsSchema = z.tuple([z.unknown()]);

export const createConsensusManagerReturnSchema = z.unknown();

export const createConsensusManagerSchema = {
  params: createConsensusManagerParamsSchema,
  returns: createConsensusManagerReturnSchema,
};

export default {
  createConsensusManager: createConsensusManagerSchema
};
