/**
 * Auto-generated Zod schemas for data-replication.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createDataReplicationManager
 */
export const createDataReplicationManagerParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const createDataReplicationManagerReturnSchema = z.unknown();

export const createDataReplicationManagerSchema = {
  params: createDataReplicationManagerParamsSchema,
  returns: createDataReplicationManagerReturnSchema,
};

export default {
  createDataReplicationManager: createDataReplicationManagerSchema
};
