/**
 * Auto-generated Zod schemas for distributed-query-engine.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createDistributedQueryEngine
 */
export const createDistributedQueryEngineParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const createDistributedQueryEngineReturnSchema = z.unknown();

export const createDistributedQueryEngineSchema = {
  params: createDistributedQueryEngineParamsSchema,
  returns: createDistributedQueryEngineReturnSchema,
};

export default {
  createDistributedQueryEngine: createDistributedQueryEngineSchema
};
