/**
 * Auto-generated Zod schemas for federation-coordinator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createFederationCoordinator
 */
export const createFederationCoordinatorParamsSchema = z.tuple([z.unknown()]);

export const createFederationCoordinatorReturnSchema = z.unknown();

export const createFederationCoordinatorSchema = {
  params: createFederationCoordinatorParamsSchema,
  returns: createFederationCoordinatorReturnSchema,
};

export default {
  createFederationCoordinator: createFederationCoordinatorSchema
};
