/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createFederatedSystem
 */
export const createFederatedSystemParamsSchema = z.tuple([z.unknown().optional()]);

export const createFederatedSystemReturnSchema = z.unknown();

export const createFederatedSystemSchema = {
  params: createFederatedSystemParamsSchema,
  returns: createFederatedSystemReturnSchema,
};

export default {
  createFederatedSystem: createFederatedSystemSchema
};
