/**
 * Auto-generated Zod schemas for config.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for getRuntimeConfig
 */
export const getRuntimeConfigParamsSchema = z.tuple([]);

export const getRuntimeConfigReturnSchema = z.unknown();

export const getRuntimeConfigSchema = {
  params: getRuntimeConfigParamsSchema,
  returns: getRuntimeConfigReturnSchema,
};

export default {
  getRuntimeConfig: getRuntimeConfigSchema
};
