/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createStoreContext
 */
export const createStoreContextParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional()]);

export const createStoreContextReturnSchema = z.unknown();

export const createStoreContextSchema = {
  params: createStoreContextParamsSchema,
  returns: createStoreContextReturnSchema,
};

/**
 * Schema for initStore
 */
export const initStoreParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional()]);

export const initStoreReturnSchema = z.unknown();

export const initStoreSchema = {
  params: initStoreParamsSchema,
  returns: initStoreReturnSchema,
};

/**
 * Schema for setStoreContext
 */
export const setStoreContextParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional()]);

export const setStoreContextReturnSchema = z.unknown();

export const setStoreContextSchema = {
  params: setStoreContextParamsSchema,
  returns: setStoreContextReturnSchema,
};

export default {
  createStoreContext: createStoreContextSchema,
  initStore: initStoreSchema,
  setStoreContext: setStoreContextSchema
};
