/**
 * Auto-generated Zod schemas for detector.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for detectEnvironment
 */
export const detectEnvironmentParamsSchema = z.tuple([]);

export const detectEnvironmentReturnSchema = z.unknown();

export const detectEnvironmentSchema = {
  params: detectEnvironmentParamsSchema,
  returns: detectEnvironmentReturnSchema,
};

/**
 * Schema for checkIsolatedVm
 */
export const checkIsolatedVmParamsSchema = z.tuple([]);

export const checkIsolatedVmReturnSchema = z.unknown();

export const checkIsolatedVmSchema = {
  params: checkIsolatedVmParamsSchema,
  returns: checkIsolatedVmReturnSchema,
};

/**
 * Schema for checkWorkerThreads
 */
export const checkWorkerThreadsParamsSchema = z.tuple([]);

export const checkWorkerThreadsReturnSchema = z.unknown();

export const checkWorkerThreadsSchema = {
  params: checkWorkerThreadsParamsSchema,
  returns: checkWorkerThreadsReturnSchema,
};

/**
 * Schema for checkVm2
 */
export const checkVm2ParamsSchema = z.tuple([]);

export const checkVm2ReturnSchema = z.unknown();

export const checkVm2Schema = {
  params: checkVm2ParamsSchema,
  returns: checkVm2ReturnSchema,
};

/**
 * Schema for detectBestExecutor
 */
export const detectBestExecutorParamsSchema = z.tuple([z.unknown().optional()]);

export const detectBestExecutorReturnSchema = z.unknown();

export const detectBestExecutorSchema = {
  params: detectBestExecutorParamsSchema,
  returns: detectBestExecutorReturnSchema,
};

/**
 * Schema for createExecutor
 */
export const createExecutorParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const createExecutorReturnSchema = z.unknown();

export const createExecutorSchema = {
  params: createExecutorParamsSchema,
  returns: createExecutorReturnSchema,
};

/**
 * Schema for createBestExecutor
 */
export const createBestExecutorParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional()]);

export const createBestExecutorReturnSchema = z.unknown();

export const createBestExecutorSchema = {
  params: createBestExecutorParamsSchema,
  returns: createBestExecutorReturnSchema,
};

/**
 * Schema for getExecutorCapabilities
 */
export const getExecutorCapabilitiesParamsSchema = z.tuple([z.string()]);

export const getExecutorCapabilitiesReturnSchema = z.unknown();

export const getExecutorCapabilitiesSchema = {
  params: getExecutorCapabilitiesParamsSchema,
  returns: getExecutorCapabilitiesReturnSchema,
};

export default {
  detectEnvironment: detectEnvironmentSchema,
  checkIsolatedVm: checkIsolatedVmSchema,
  checkWorkerThreads: checkWorkerThreadsSchema,
  checkVm2: checkVm2Schema,
  detectBestExecutor: detectBestExecutorSchema,
  createExecutor: createExecutorSchema,
  createBestExecutor: createBestExecutorSchema,
  getExecutorCapabilities: getExecutorCapabilitiesSchema
};
