/**
 * Auto-generated Zod schemas for audit-trail-validator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateReceipt
 */
export const validateReceiptParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const validateReceiptReturnSchema = z.unknown();

export const validateReceiptSchema = {
  params: validateReceiptParamsSchema,
  returns: validateReceiptReturnSchema,
};

/**
 * Schema for computeReceiptHash
 */
export const computeReceiptHashParamsSchema = z.tuple([z.unknown()]);

export const computeReceiptHashReturnSchema = z.string();

export const computeReceiptHashSchema = {
  params: computeReceiptHashParamsSchema,
  returns: computeReceiptHashReturnSchema,
};

/**
 * Schema for validateReceiptChain
 */
export const validateReceiptChainParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const validateReceiptChainReturnSchema = z.unknown();

export const validateReceiptChainSchema = {
  params: validateReceiptChainParamsSchema,
  returns: validateReceiptChainReturnSchema,
};

/**
 * Schema for loadReceipts
 */
export const loadReceiptsParamsSchema = z.tuple([z.string()]);

export const loadReceiptsReturnSchema = z.unknown();

export const loadReceiptsSchema = {
  params: loadReceiptsParamsSchema,
  returns: loadReceiptsReturnSchema,
};

/**
 * Schema for validateDirectory
 */
export const validateDirectoryParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const validateDirectoryReturnSchema = z.unknown();

export const validateDirectorySchema = {
  params: validateDirectoryParamsSchema,
  returns: validateDirectoryReturnSchema,
};

/**
 * Schema for validateRequiredOperations
 */
export const validateRequiredOperationsParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const validateRequiredOperationsReturnSchema = z.unknown();

export const validateRequiredOperationsSchema = {
  params: validateRequiredOperationsParamsSchema,
  returns: validateRequiredOperationsReturnSchema,
};

/**
 * Schema for createReceipt
 */
export const createReceiptParamsSchema = z.tuple([z.unknown()]);

export const createReceiptReturnSchema = z.unknown();

export const createReceiptSchema = {
  params: createReceiptParamsSchema,
  returns: createReceiptReturnSchema,
};

/**
 * Schema for formatReport
 */
export const formatReportParamsSchema = z.tuple([z.unknown()]);

export const formatReportReturnSchema = z.string();

export const formatReportSchema = {
  params: formatReportParamsSchema,
  returns: formatReportReturnSchema,
};

/**
 * Schema for calculateCoverage
 */
export const calculateCoverageParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const calculateCoverageReturnSchema = z.unknown();

export const calculateCoverageSchema = {
  params: calculateCoverageParamsSchema,
  returns: calculateCoverageReturnSchema,
};

export default {
  validateReceipt: validateReceiptSchema,
  computeReceiptHash: computeReceiptHashSchema,
  validateReceiptChain: validateReceiptChainSchema,
  loadReceipts: loadReceiptsSchema,
  validateDirectory: validateDirectorySchema,
  validateRequiredOperations: validateRequiredOperationsSchema,
  createReceipt: createReceiptSchema,
  formatReport: formatReportSchema,
  calculateCoverage: calculateCoverageSchema
};
