/**
 * Auto-generated Zod schemas for dashboard.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for generateDashboard
 */
export const generateDashboardParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const generateDashboardReturnSchema = z.unknown();

export const generateDashboardSchema = {
  params: generateDashboardParamsSchema,
  returns: generateDashboardReturnSchema,
};

/**
 * Schema for formatTextReport
 */
export const formatTextReportParamsSchema = z.tuple([z.unknown()]);

export const formatTextReportReturnSchema = z.string();

export const formatTextReportSchema = {
  params: formatTextReportParamsSchema,
  returns: formatTextReportReturnSchema,
};

/**
 * Schema for formatJsonReport
 */
export const formatJsonReportParamsSchema = z.tuple([z.unknown()]);

export const formatJsonReportReturnSchema = z.string();

export const formatJsonReportSchema = {
  params: formatJsonReportParamsSchema,
  returns: formatJsonReportReturnSchema,
};

/**
 * Schema for formatHtmlReport
 */
export const formatHtmlReportParamsSchema = z.tuple([z.unknown()]);

export const formatHtmlReportReturnSchema = z.string();

export const formatHtmlReportSchema = {
  params: formatHtmlReportParamsSchema,
  returns: formatHtmlReportReturnSchema,
};

/**
 * Schema for exportDashboard
 */
export const exportDashboardParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const exportDashboardReturnSchema = z.unknown();

export const exportDashboardSchema = {
  params: exportDashboardParamsSchema,
  returns: exportDashboardReturnSchema,
};

/**
 * Schema for generateSecurityReceipt
 */
export const generateSecurityReceiptParamsSchema = z.tuple([z.unknown()]);

export const generateSecurityReceiptReturnSchema = z.unknown();

export const generateSecurityReceiptSchema = {
  params: generateSecurityReceiptParamsSchema,
  returns: generateSecurityReceiptReturnSchema,
};

export default {
  generateDashboard: generateDashboardSchema,
  formatTextReport: formatTextReportSchema,
  formatJsonReport: formatJsonReportSchema,
  formatHtmlReport: formatHtmlReportSchema,
  exportDashboard: exportDashboardSchema,
  generateSecurityReceipt: generateSecurityReceiptSchema
};
