/**
 * Auto-generated Zod schemas for dependency-auditor.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for auditPackage
 */
export const auditPackageParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const auditPackageReturnSchema = z.unknown();

export const auditPackageSchema = {
  params: auditPackageParamsSchema,
  returns: auditPackageReturnSchema,
};

/**
 * Schema for auditDirectory
 */
export const auditDirectoryParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const auditDirectoryReturnSchema = z.unknown();

export const auditDirectorySchema = {
  params: auditDirectoryParamsSchema,
  returns: auditDirectoryReturnSchema,
};

/**
 * Schema for formatReport
 */
export const formatReportParamsSchema = z.tuple([z.unknown()]);

export const formatReportReturnSchema = z.string();

export const formatReportSchema = {
  params: formatReportParamsSchema,
  returns: formatReportReturnSchema,
};

/**
 * Schema for getRemediationCommands
 */
export const getRemediationCommandsParamsSchema = z.tuple([z.unknown()]);

export const getRemediationCommandsReturnSchema = z.unknown();

export const getRemediationCommandsSchema = {
  params: getRemediationCommandsParamsSchema,
  returns: getRemediationCommandsReturnSchema,
};

export default {
  auditPackage: auditPackageSchema,
  auditDirectory: auditDirectorySchema,
  formatReport: formatReportSchema,
  getRemediationCommands: getRemediationCommandsSchema
};
