/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for checkAllInvariants
 */
export const checkAllInvariantsParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const checkAllInvariantsReturnSchema = z.unknown();

export const checkAllInvariantsSchema = {
  params: checkAllInvariantsParamsSchema,
  returns: checkAllInvariantsReturnSchema,
};

/**
 * Schema for quickCheck
 */
export const quickCheckParamsSchema = z.tuple([z.string()]);

export const quickCheckReturnSchema = z.unknown();

export const quickCheckSchema = {
  params: quickCheckParamsSchema,
  returns: quickCheckReturnSchema,
};

/**
 * Schema for generateSecurityDashboard
 */
export const generateSecurityDashboardParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const generateSecurityDashboardReturnSchema = z.unknown();

export const generateSecurityDashboardSchema = {
  params: generateSecurityDashboardParamsSchema,
  returns: generateSecurityDashboardReturnSchema,
};

/**
 * Schema for formatReport
 */
export const formatReportParamsSchema = z.tuple([z.unknown()]);

export const formatReportReturnSchema = z.string();

export const formatReportSchema = {
  params: formatReportParamsSchema,
  returns: formatReportReturnSchema,
};

/**
 * Schema for integrateWithAdmission
 */
export const integrateWithAdmissionParamsSchema = z.tuple([z.unknown()]);

export const integrateWithAdmissionReturnSchema = z.unknown();

export const integrateWithAdmissionSchema = {
  params: integrateWithAdmissionParamsSchema,
  returns: integrateWithAdmissionReturnSchema,
};

export default {
  checkAllInvariants: checkAllInvariantsSchema,
  quickCheck: quickCheckSchema,
  generateSecurityDashboard: generateSecurityDashboardSchema,
  formatReport: formatReportSchema,
  integrateWithAdmission: integrateWithAdmissionSchema
};
