/**
 * Auto-generated Zod schemas for injection-checker.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for scanFile
 */
export const scanFileParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const scanFileReturnSchema = z.unknown();

export const scanFileSchema = {
  params: scanFileParamsSchema,
  returns: scanFileReturnSchema,
};

/**
 * Schema for scanDirectory
 */
export const scanDirectoryParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const scanDirectoryReturnSchema = z.unknown();

export const scanDirectorySchema = {
  params: scanDirectoryParamsSchema,
  returns: scanDirectoryReturnSchema,
};

/**
 * Schema for formatReport
 */
export const formatReportParamsSchema = z.tuple([z.unknown()]);

export const formatReportReturnSchema = z.string();

export const formatReportSchema = {
  params: formatReportParamsSchema,
  returns: formatReportReturnSchema,
};

/**
 * Schema for getRules
 */
export const getRulesParamsSchema = z.tuple([]);

export const getRulesReturnSchema = z.unknown();

export const getRulesSchema = {
  params: getRulesParamsSchema,
  returns: getRulesReturnSchema,
};

export default {
  scanFile: scanFileSchema,
  scanDirectory: scanDirectorySchema,
  formatReport: formatReportSchema,
  getRules: getRulesSchema
};
