/**
 * Auto-generated Zod schemas for license-checker.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for normalizeLicense
 */
export const normalizeLicenseParamsSchema = z.tuple([z.string()]);

export const normalizeLicenseReturnSchema = z.string();

export const normalizeLicenseSchema = {
  params: normalizeLicenseParamsSchema,
  returns: normalizeLicenseReturnSchema,
};

/**
 * Schema for isPermissive
 */
export const isPermissiveParamsSchema = z.tuple([z.string()]);

export const isPermissiveReturnSchema = z.boolean();

export const isPermissiveSchema = {
  params: isPermissiveParamsSchema,
  returns: isPermissiveReturnSchema,
};

/**
 * Schema for isCopyleft
 */
export const isCopyleftParamsSchema = z.tuple([z.string()]);

export const isCopyleftReturnSchema = z.boolean();

export const isCopyleftSchema = {
  params: isCopyleftParamsSchema,
  returns: isCopyleftReturnSchema,
};

/**
 * Schema for getLicenseCategory
 */
export const getLicenseCategoryParamsSchema = z.tuple([z.string()]);

export const getLicenseCategoryReturnSchema = z.string();

export const getLicenseCategorySchema = {
  params: getLicenseCategoryParamsSchema,
  returns: getLicenseCategoryReturnSchema,
};

/**
 * Schema for checkLicensePolicy
 */
export const checkLicensePolicyParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const checkLicensePolicyReturnSchema = z.unknown();

export const checkLicensePolicySchema = {
  params: checkLicensePolicyParamsSchema,
  returns: checkLicensePolicyReturnSchema,
};

/**
 * Schema for checkPackage
 */
export const checkPackageParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const checkPackageReturnSchema = z.unknown();

export const checkPackageSchema = {
  params: checkPackageParamsSchema,
  returns: checkPackageReturnSchema,
};

/**
 * Schema for checkDirectory
 */
export const checkDirectoryParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const checkDirectoryReturnSchema = z.unknown();

export const checkDirectorySchema = {
  params: checkDirectoryParamsSchema,
  returns: checkDirectoryReturnSchema,
};

/**
 * Schema for formatReport
 */
export const formatReportParamsSchema = z.tuple([z.unknown()]);

export const formatReportReturnSchema = z.string();

export const formatReportSchema = {
  params: formatReportParamsSchema,
  returns: formatReportReturnSchema,
};

/**
 * Schema for generateCompatibilityMatrix
 */
export const generateCompatibilityMatrixParamsSchema = z.tuple([z.unknown()]);

export const generateCompatibilityMatrixReturnSchema = z.unknown();

export const generateCompatibilityMatrixSchema = {
  params: generateCompatibilityMatrixParamsSchema,
  returns: generateCompatibilityMatrixReturnSchema,
};

export default {
  normalizeLicense: normalizeLicenseSchema,
  isPermissive: isPermissiveSchema,
  isCopyleft: isCopyleftSchema,
  getLicenseCategory: getLicenseCategorySchema,
  checkLicensePolicy: checkLicensePolicySchema,
  checkPackage: checkPackageSchema,
  checkDirectory: checkDirectorySchema,
  formatReport: formatReportSchema,
  generateCompatibilityMatrix: generateCompatibilityMatrixSchema
};
