/**
 * Auto-generated Zod schemas for sandbox-adapter.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createSandboxAdapter
 */
export const createSandboxAdapterParamsSchema = z.tuple([z.unknown().optional()]);

export const createSandboxAdapterReturnSchema = z.unknown();

export const createSandboxAdapterSchema = {
  params: createSandboxAdapterParamsSchema,
  returns: createSandboxAdapterReturnSchema,
};

export default {
  createSandboxAdapter: createSandboxAdapterSchema
};
