/**
 * Auto-generated Zod schemas for secret-detector.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for calculateEntropy
 */
export const calculateEntropyParamsSchema = z.tuple([z.string()]);

export const calculateEntropyReturnSchema = z.number();

export const calculateEntropySchema = {
  params: calculateEntropyParamsSchema,
  returns: calculateEntropyReturnSchema,
};

/**
 * Schema for maskSecret
 */
export const maskSecretParamsSchema = z.tuple([z.string()]);

export const maskSecretReturnSchema = z.string();

export const maskSecretSchema = {
  params: maskSecretParamsSchema,
  returns: maskSecretReturnSchema,
};

/**
 * Schema for scanFile
 */
export const scanFileParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const scanFileReturnSchema = z.unknown();

export const scanFileSchema = {
  params: scanFileParamsSchema,
  returns: scanFileReturnSchema,
};

/**
 * Schema for scanDirectory
 */
export const scanDirectoryParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const scanDirectoryReturnSchema = z.unknown();

export const scanDirectorySchema = {
  params: scanDirectoryParamsSchema,
  returns: scanDirectoryReturnSchema,
};

/**
 * Schema for getConfigHash
 */
export const getConfigHashParamsSchema = z.tuple([z.unknown().optional()]);

export const getConfigHashReturnSchema = z.string();

export const getConfigHashSchema = {
  params: getConfigHashParamsSchema,
  returns: getConfigHashReturnSchema,
};

/**
 * Schema for formatReport
 */
export const formatReportParamsSchema = z.tuple([z.unknown()]);

export const formatReportReturnSchema = z.string();

export const formatReportSchema = {
  params: formatReportParamsSchema,
  returns: formatReportReturnSchema,
};

export default {
  calculateEntropy: calculateEntropySchema,
  maskSecret: maskSecretSchema,
  scanFile: scanFileSchema,
  scanDirectory: scanDirectorySchema,
  getConfigHash: getConfigHashSchema,
  formatReport: formatReportSchema
};
