/**
 * Auto-generated Zod schemas for use-knowledge-stack.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useKnowledgeStack
 */
export const useKnowledgeStackParamsSchema = z.tuple([z.unknown().optional()]);

export const useKnowledgeStackReturnSchema = z.unknown();

export const useKnowledgeStackSchema = {
  params: useKnowledgeStackParamsSchema,
  returns: useKnowledgeStackReturnSchema,
};

/**
 * Schema for useCRUDStack
 */
export const useCRUDStackParamsSchema = z.tuple([z.unknown().optional()]);

export const useCRUDStackReturnSchema = z.unknown();

export const useCRUDStackSchema = {
  params: useCRUDStackParamsSchema,
  returns: useCRUDStackReturnSchema,
};

/**
 * Schema for useDashboardStack
 */
export const useDashboardStackParamsSchema = z.tuple([z.unknown().optional()]);

export const useDashboardStackReturnSchema = z.unknown();

export const useDashboardStackSchema = {
  params: useDashboardStackParamsSchema,
  returns: useDashboardStackReturnSchema,
};

/**
 * Schema for useProductionStack
 */
export const useProductionStackParamsSchema = z.tuple([z.unknown().optional()]);

export const useProductionStackReturnSchema = z.unknown();

export const useProductionStackSchema = {
  params: useProductionStackParamsSchema,
  returns: useProductionStackReturnSchema,
};

export default {
  useKnowledgeStack: useKnowledgeStackSchema,
  useCRUDStack: useCRUDStackSchema,
  useDashboardStack: useDashboardStackSchema,
  useProductionStack: useProductionStackSchema
};
