/**
 * Auto-generated Zod schemas for compiler.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for compileGrammar
 */
export const compileGrammarParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const compileGrammarReturnSchema = z.unknown();

export const compileGrammarSchema = {
  params: compileGrammarParamsSchema,
  returns: compileGrammarReturnSchema,
};

/**
 * Schema for rejectIfTooComplex
 */
export const rejectIfTooComplexParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const rejectIfTooComplexReturnSchema = z.unknown();

export const rejectIfTooComplexSchema = {
  params: rejectIfTooComplexParamsSchema,
  returns: rejectIfTooComplexReturnSchema,
};

/**
 * Schema for emitDenialReceipt
 */
export const emitDenialReceiptParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const emitDenialReceiptReturnSchema = z.unknown();

export const emitDenialReceiptSchema = {
  params: emitDenialReceiptParamsSchema,
  returns: emitDenialReceiptReturnSchema,
};

/**
 * Schema for emitCompileReceipt
 */
export const emitCompileReceiptParamsSchema = z.tuple([z.unknown(), z.unknown(), z.string()]);

export const emitCompileReceiptReturnSchema = z.unknown();

export const emitCompileReceiptSchema = {
  params: emitCompileReceiptParamsSchema,
  returns: emitCompileReceiptReturnSchema,
};

export default {
  compileGrammar: compileGrammarSchema,
  rejectIfTooComplex: rejectIfTooComplexSchema,
  emitDenialReceipt: emitDenialReceiptSchema,
  emitCompileReceipt: emitCompileReceiptSchema
};
