/**
 * Auto-generated Zod schemas for grammar-receipts.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for testGrammarDeterminism
 */
export const testGrammarDeterminismParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const testGrammarDeterminismReturnSchema = z.unknown();

export const testGrammarDeterminismSchema = {
  params: testGrammarDeterminismParamsSchema,
  returns: testGrammarDeterminismReturnSchema,
};

export default {
  testGrammarDeterminism: testGrammarDeterminismSchema
};
