/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for grammarClosurePipeline
 */
export const grammarClosurePipelineParamsSchema = z.tuple([z.string(), z.string(), z.unknown(), z.unknown(), z.unknown().optional()]);

export const grammarClosurePipelineReturnSchema = z.unknown();

export const grammarClosurePipelineSchema = {
  params: grammarClosurePipelineParamsSchema,
  returns: grammarClosurePipelineReturnSchema,
};

export default {
  grammarClosurePipeline: grammarClosurePipelineSchema
};
