/**
 * Auto-generated Zod schemas for runtime-gate.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for checkRuntimeComplexity
 */
export const checkRuntimeComplexityParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const checkRuntimeComplexityReturnSchema = z.unknown();

export const checkRuntimeComplexitySchema = {
  params: checkRuntimeComplexityParamsSchema,
  returns: checkRuntimeComplexityReturnSchema,
};

/**
 * Schema for wrapWithTimeout
 */
export const wrapWithTimeoutParamsSchema = z.tuple([z.unknown(), z.number(), z.unknown().optional()]);

export const wrapWithTimeoutReturnSchema = z.unknown();

export const wrapWithTimeoutSchema = {
  params: wrapWithTimeoutParamsSchema,
  returns: wrapWithTimeoutReturnSchema,
};

/**
 * Schema for emitDenialReceipt
 */
export const emitDenialReceiptParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const emitDenialReceiptReturnSchema = z.unknown();

export const emitDenialReceiptSchema = {
  params: emitDenialReceiptParamsSchema,
  returns: emitDenialReceiptReturnSchema,
};

/**
 * Schema for executeWithGate
 */
export const executeWithGateParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown(), z.unknown().optional()]);

export const executeWithGateReturnSchema = z.unknown();

export const executeWithGateSchema = {
  params: executeWithGateParamsSchema,
  returns: executeWithGateReturnSchema,
};

/**
 * Schema for getRuntimeBounds
 */
export const getRuntimeBoundsParamsSchema = z.tuple([z.string()]);

export const getRuntimeBoundsReturnSchema = z.unknown();

export const getRuntimeBoundsSchema = {
  params: getRuntimeBoundsParamsSchema,
  returns: getRuntimeBoundsReturnSchema,
};

export default {
  checkRuntimeComplexity: checkRuntimeComplexitySchema,
  wrapWithTimeout: wrapWithTimeoutSchema,
  emitDenialReceipt: emitDenialReceiptSchema,
  executeWithGate: executeWithGateSchema,
  getRuntimeBounds: getRuntimeBoundsSchema
};
