/**
 * Auto-generated Zod schemas for use-federation-health.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useFederationHealth
 */
export const useFederationHealthParamsSchema = z.tuple([z.unknown().optional()]);

export const useFederationHealthReturnSchema = z.unknown();

export const useFederationHealthSchema = {
  params: useFederationHealthParamsSchema,
  returns: useFederationHealthReturnSchema,
};

export default {
  useFederationHealth: useFederationHealthSchema
};
