/**
 * Auto-generated Zod schemas for use-distributed-query.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useDistributedQuery
 */
export const useDistributedQueryParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional()]);

export const useDistributedQueryReturnSchema = z.unknown();

export const useDistributedQuerySchema = {
  params: useDistributedQueryParamsSchema,
  returns: useDistributedQueryReturnSchema,
};

export default {
  useDistributedQuery: useDistributedQuerySchema
};
