/**
 * Auto-generated Zod schemas for use-consensus-manager.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useConsensusManager
 */
export const useConsensusManagerParamsSchema = z.tuple([z.unknown().optional()]);

export const useConsensusManagerReturnSchema = z.unknown();

export const useConsensusManagerSchema = {
  params: useConsensusManagerParamsSchema,
  returns: useConsensusManagerReturnSchema,
};

export default {
  useConsensusManager: useConsensusManagerSchema
};
