/**
 * Auto-generated Zod schemas for use-federated-system.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useFederatedSystem
 */
export const useFederatedSystemParamsSchema = z.tuple([z.unknown().optional()]);

export const useFederatedSystemReturnSchema = z.unknown();

export const useFederatedSystemSchema = {
  params: useFederatedSystemParamsSchema,
  returns: useFederatedSystemReturnSchema,
};

export default {
  useFederatedSystem: useFederatedSystemSchema
};
