/**
 * Auto-generated Zod schemas for cross-package-guards.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for H_core_signature_break
 */
export const H_core_signature_breakParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const H_core_signature_breakReturnSchema = z.unknown();

export const H_core_signature_breakSchema = {
  params: H_core_signature_breakParamsSchema,
  returns: H_core_signature_breakReturnSchema,
};

/**
 * Schema for H_internal_api_external_export
 */
export const H_internal_api_external_exportParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const H_internal_api_external_exportReturnSchema = z.unknown();

export const H_internal_api_external_exportSchema = {
  params: H_internal_api_external_exportParamsSchema,
  returns: H_internal_api_external_exportReturnSchema,
};

/**
 * Schema for H_circular_dependency
 */
export const H_circular_dependencyParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const H_circular_dependencyReturnSchema = z.unknown();

export const H_circular_dependencySchema = {
  params: H_circular_dependencyParamsSchema,
  returns: H_circular_dependencyReturnSchema,
};

/**
 * Schema for H_license_incompatible
 */
export const H_license_incompatibleParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const H_license_incompatibleReturnSchema = z.unknown();

export const H_license_incompatibleSchema = {
  params: H_license_incompatibleParamsSchema,
  returns: H_license_incompatibleReturnSchema,
};

/**
 * Schema for H_protected_package_delete
 */
export const H_protected_package_deleteParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const H_protected_package_deleteReturnSchema = z.unknown();

export const H_protected_package_deleteSchema = {
  params: H_protected_package_deleteParamsSchema,
  returns: H_protected_package_deleteReturnSchema,
};

/**
 * Schema for H_cross_category_break
 */
export const H_cross_category_breakParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const H_cross_category_breakReturnSchema = z.unknown();

export const H_cross_category_breakSchema = {
  params: H_cross_category_breakParamsSchema,
  returns: H_cross_category_breakReturnSchema,
};

/**
 * Schema for checkAllCrossPackageGuards
 */
export const checkAllCrossPackageGuardsParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const checkAllCrossPackageGuardsReturnSchema = z.unknown();

export const checkAllCrossPackageGuardsSchema = {
  params: checkAllCrossPackageGuardsParamsSchema,
  returns: checkAllCrossPackageGuardsReturnSchema,
};

export default {
  H_core_signature_break: H_core_signature_breakSchema,
  H_internal_api_external_export: H_internal_api_external_exportSchema,
  H_circular_dependency: H_circular_dependencySchema,
  H_license_incompatible: H_license_incompatibleSchema,
  H_protected_package_delete: H_protected_package_deleteSchema,
  H_cross_category_break: H_cross_category_breakSchema,
  checkAllCrossPackageGuards: checkAllCrossPackageGuardsSchema
};
