/**
 * Auto-generated Zod schemas for cross-package-invariants.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for Q_version_consistency
 */
export const Q_version_consistencyParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const Q_version_consistencyReturnSchema = z.unknown();

export const Q_version_consistencySchema = {
  params: Q_version_consistencyParamsSchema,
  returns: Q_version_consistencyReturnSchema,
};

/**
 * Schema for Q_api_stability
 */
export const Q_api_stabilityParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const Q_api_stabilityReturnSchema = z.unknown();

export const Q_api_stabilitySchema = {
  params: Q_api_stabilityParamsSchema,
  returns: Q_api_stabilityReturnSchema,
};

/**
 * Schema for Q_dependency_acyclic
 */
export const Q_dependency_acyclicParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const Q_dependency_acyclicReturnSchema = z.unknown();

export const Q_dependency_acyclicSchema = {
  params: Q_dependency_acyclicParamsSchema,
  returns: Q_dependency_acyclicReturnSchema,
};

/**
 * Schema for Q_license_compliance
 */
export const Q_license_complianceParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const Q_license_complianceReturnSchema = z.unknown();

export const Q_license_complianceSchema = {
  params: Q_license_complianceParamsSchema,
  returns: Q_license_complianceReturnSchema,
};

/**
 * Schema for Q_documentation_coverage
 */
export const Q_documentation_coverageParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const Q_documentation_coverageReturnSchema = z.unknown();

export const Q_documentation_coverageSchema = {
  params: Q_documentation_coverageParamsSchema,
  returns: Q_documentation_coverageReturnSchema,
};

/**
 * Schema for Q_test_coverage
 */
export const Q_test_coverageParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const Q_test_coverageReturnSchema = z.unknown();

export const Q_test_coverageSchema = {
  params: Q_test_coverageParamsSchema,
  returns: Q_test_coverageReturnSchema,
};

/**
 * Schema for checkAllCrossPackageInvariants
 */
export const checkAllCrossPackageInvariantsParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown().optional()]);

export const checkAllCrossPackageInvariantsReturnSchema = z.unknown();

export const checkAllCrossPackageInvariantsSchema = {
  params: checkAllCrossPackageInvariantsParamsSchema,
  returns: checkAllCrossPackageInvariantsReturnSchema,
};

export default {
  Q_version_consistency: Q_version_consistencySchema,
  Q_api_stability: Q_api_stabilitySchema,
  Q_dependency_acyclic: Q_dependency_acyclicSchema,
  Q_license_compliance: Q_license_complianceSchema,
  Q_documentation_coverage: Q_documentation_coverageSchema,
  Q_test_coverage: Q_test_coverageSchema,
  checkAllCrossPackageInvariants: checkAllCrossPackageInvariantsSchema
};
