/**
 * Auto-generated Zod schemas for monorepo-universe.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createMonorepoUniverse
 */
export const createMonorepoUniverseParamsSchema = z.tuple([z.unknown()]);

export const createMonorepoUniverseReturnSchema = z.unknown();

export const createMonorepoUniverseSchema = {
  params: createMonorepoUniverseParamsSchema,
  returns: createMonorepoUniverseReturnSchema,
};

export default {
  createMonorepoUniverse: createMonorepoUniverseSchema
};
