/**
 * Auto-generated Zod schemas for monorepo-admission-engine.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createMonorepoAdmissionEngine
 */
export const createMonorepoAdmissionEngineParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const createMonorepoAdmissionEngineReturnSchema = z.unknown();

export const createMonorepoAdmissionEngineSchema = {
  params: createMonorepoAdmissionEngineParamsSchema,
  returns: createMonorepoAdmissionEngineReturnSchema,
};

export default {
  createMonorepoAdmissionEngine: createMonorepoAdmissionEngineSchema
};
