/**
 * Auto-generated Zod schemas for package-partition.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for getCategoryForPackage
 */
export const getCategoryForPackageParamsSchema = z.tuple([z.string()]);

export const getCategoryForPackageReturnSchema = z.string();

export const getCategoryForPackageSchema = {
  params: getCategoryForPackageParamsSchema,
  returns: getCategoryForPackageReturnSchema,
};

/**
 * Schema for isProtectedPackage
 */
export const isProtectedPackageParamsSchema = z.tuple([z.string()]);

export const isProtectedPackageReturnSchema = z.boolean();

export const isProtectedPackageSchema = {
  params: isProtectedPackageParamsSchema,
  returns: isProtectedPackageReturnSchema,
};

/**
 * Schema for getPackagesInCategory
 */
export const getPackagesInCategoryParamsSchema = z.tuple([z.string()]);

export const getPackagesInCategoryReturnSchema = z.unknown();

export const getPackagesInCategorySchema = {
  params: getPackagesInCategoryParamsSchema,
  returns: getPackagesInCategoryReturnSchema,
};

export default {
  getCategoryForPackage: getCategoryForPackageSchema,
  isProtectedPackage: isProtectedPackageSchema,
  getPackagesInCategory: getPackagesInCategorySchema
};
