/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createStreamingPipeline
 */
export const createStreamingPipelineParamsSchema = z.tuple([z.unknown().optional()]);

export const createStreamingPipelineReturnSchema = z.unknown();

export const createStreamingPipelineSchema = {
  params: createStreamingPipelineParamsSchema,
  returns: createStreamingPipelineReturnSchema,
};

export default {
  createStreamingPipeline: createStreamingPipelineSchema
};
