/**
 * Auto-generated Zod schemas for real-time-validator.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createRealTimeValidator
 */
export const createRealTimeValidatorParamsSchema = z.tuple([z.unknown().optional()]);

export const createRealTimeValidatorReturnSchema = z.unknown();

export const createRealTimeValidatorSchema = {
  params: createRealTimeValidatorParamsSchema,
  returns: createRealTimeValidatorReturnSchema,
};

export default {
  createRealTimeValidator: createRealTimeValidatorSchema
};
