/**
 * Auto-generated Zod schemas for stream-processor.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createStreamProcessor
 */
export const createStreamProcessorParamsSchema = z.tuple([z.unknown().optional()]);

export const createStreamProcessorReturnSchema = z.unknown();

export const createStreamProcessorSchema = {
  params: createStreamProcessorParamsSchema,
  returns: createStreamProcessorReturnSchema,
};

export default {
  createStreamProcessor: createStreamProcessorSchema
};
