/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validate
 */
export const validateParamsSchema = z.tuple([z.unknown(), z.any(), z.unknown().optional()]);

export const validateReturnSchema = z.unknown();

export const validateSchema = {
  params: validateParamsSchema,
  returns: validateReturnSchema,
};

/**
 * Schema for validateOrThrow
 */
export const validateOrThrowParamsSchema = z.tuple([z.unknown(), z.any(), z.unknown().optional()]);

export const validateOrThrowReturnSchema = z.any();

export const validateOrThrowSchema = {
  params: validateOrThrowParamsSchema,
  returns: validateOrThrowReturnSchema,
};

/**
 * Schema for createValidator
 */
export const createValidatorParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const createValidatorReturnSchema = z.unknown();

export const createValidatorSchema = {
  params: createValidatorParamsSchema,
  returns: createValidatorReturnSchema,
};

/**
 * Schema for createThrowingValidator
 */
export const createThrowingValidatorParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const createThrowingValidatorReturnSchema = z.unknown();

export const createThrowingValidatorSchema = {
  params: createThrowingValidatorParamsSchema,
  returns: createThrowingValidatorReturnSchema,
};

export default {
  validate: validateSchema,
  validateOrThrow: validateOrThrowSchema,
  createValidator: createValidatorSchema,
  createThrowingValidator: createThrowingValidatorSchema
};
