/**
 * Auto-generated Zod schemas for diff.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for quadToDiffTriple
 */
export const quadToDiffTripleParamsSchema = z.tuple([z.unknown()]);

export const quadToDiffTripleReturnSchema = z.unknown();

export const quadToDiffTripleSchema = {
  params: quadToDiffTripleParamsSchema,
  returns: quadToDiffTripleReturnSchema,
};

/**
 * Schema for diffTripleKey
 */
export const diffTripleKeyParamsSchema = z.tuple([z.unknown()]);

export const diffTripleKeyReturnSchema = z.string();

export const diffTripleKeySchema = {
  params: diffTripleKeyParamsSchema,
  returns: diffTripleKeyReturnSchema,
};

/**
 * Schema for collectDiffTriplesFromStore
 */
export const collectDiffTriplesFromStoreParamsSchema = z.tuple([z.unknown()]);

export const collectDiffTriplesFromStoreReturnSchema = z.unknown();

export const collectDiffTriplesFromStoreSchema = {
  params: collectDiffTriplesFromStoreParamsSchema,
  returns: collectDiffTriplesFromStoreReturnSchema,
};

/**
 * Schema for diffGraphFromStores
 */
export const diffGraphFromStoresParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const diffGraphFromStoresReturnSchema = z.unknown();

export const diffGraphFromStoresSchema = {
  params: diffGraphFromStoresParamsSchema,
  returns: diffGraphFromStoresReturnSchema,
};

/**
 * Schema for diffGraphFromDelta
 */
export const diffGraphFromDeltaParamsSchema = z.tuple([z.unknown()]);

export const diffGraphFromDeltaReturnSchema = z.unknown();

export const diffGraphFromDeltaSchema = {
  params: diffGraphFromDeltaParamsSchema,
  returns: diffGraphFromDeltaReturnSchema,
};

/**
 * Schema for diffOntologyFromGraphDiff
 */
export const diffOntologyFromGraphDiffParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const diffOntologyFromGraphDiffReturnSchema = z.unknown();

export const diffOntologyFromGraphDiffSchema = {
  params: diffOntologyFromGraphDiffParamsSchema,
  returns: diffOntologyFromGraphDiffReturnSchema,
};

/**
 * Schema for diffOntologyFromStores
 */
export const diffOntologyFromStoresParamsSchema = z.tuple([z.unknown(), z.unknown(), z.unknown()]);

export const diffOntologyFromStoresReturnSchema = z.unknown();

export const diffOntologyFromStoresSchema = {
  params: diffOntologyFromStoresParamsSchema,
  returns: diffOntologyFromStoresReturnSchema,
};

/**
 * Schema for diffOntologyFromDelta
 */
export const diffOntologyFromDeltaParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const diffOntologyFromDeltaReturnSchema = z.unknown();

export const diffOntologyFromDeltaSchema = {
  params: diffOntologyFromDeltaParamsSchema,
  returns: diffOntologyFromDeltaReturnSchema,
};

/**
 * Schema for summarizeChangesByKind
 */
export const summarizeChangesByKindParamsSchema = z.tuple([z.unknown()]);

export const summarizeChangesByKindReturnSchema = z.unknown();

export const summarizeChangesByKindSchema = {
  params: summarizeChangesByKindParamsSchema,
  returns: summarizeChangesByKindReturnSchema,
};

/**
 * Schema for changesForEntity
 */
export const changesForEntityParamsSchema = z.tuple([z.unknown(), z.string()]);

export const changesForEntityReturnSchema = z.unknown();

export const changesForEntitySchema = {
  params: changesForEntityParamsSchema,
  returns: changesForEntityReturnSchema,
};

export default {
  quadToDiffTriple: quadToDiffTripleSchema,
  diffTripleKey: diffTripleKeySchema,
  collectDiffTriplesFromStore: collectDiffTriplesFromStoreSchema,
  diffGraphFromStores: diffGraphFromStoresSchema,
  diffGraphFromDelta: diffGraphFromDeltaSchema,
  diffOntologyFromGraphDiff: diffOntologyFromGraphDiffSchema,
  diffOntologyFromStores: diffOntologyFromStoresSchema,
  diffOntologyFromDelta: diffOntologyFromDeltaSchema,
  summarizeChangesByKind: summarizeChangesByKindSchema,
  changesForEntity: changesForEntitySchema
};
