/**
 * Auto-generated Zod schemas for knowledge-engine.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createKnowledgeEngine
 */
export const createKnowledgeEngineParamsSchema = z.tuple([z.unknown().optional()]);

export const createKnowledgeEngineReturnSchema = z.unknown();

export const createKnowledgeEngineSchema = {
  params: createKnowledgeEngineParamsSchema,
  returns: createKnowledgeEngineReturnSchema,
};

/**
 * Schema for createSimpleEngine
 */
export const createSimpleEngineParamsSchema = z.tuple([z.unknown().optional()]);

export const createSimpleEngineReturnSchema = z.unknown();

export const createSimpleEngineSchema = {
  params: createSimpleEngineParamsSchema,
  returns: createSimpleEngineReturnSchema,
};

/**
 * Schema for createStrictEngine
 */
export const createStrictEngineParamsSchema = z.tuple([z.unknown().optional()]);

export const createStrictEngineReturnSchema = z.unknown();

export const createStrictEngineSchema = {
  params: createStrictEngineParamsSchema,
  returns: createStrictEngineReturnSchema,
};

export default {
  createKnowledgeEngine: createKnowledgeEngineSchema,
  createSimpleEngine: createSimpleEngineSchema,
  createStrictEngine: createStrictEngineSchema
};
