/**
 * Auto-generated Zod schemas for anchor.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for anchorToChain
 */
export const anchorToChainParamsSchema = z.tuple([z.string(), z.unknown(), z.unknown().optional()]);

export const anchorToChainReturnSchema = z.unknown();

export const anchorToChainSchema = {
  params: anchorToChainParamsSchema,
  returns: anchorToChainReturnSchema,
};

/**
 * Schema for verifyAnchor
 */
export const verifyAnchorParamsSchema = z.tuple([z.string(), z.unknown()]);

export const verifyAnchorReturnSchema = z.unknown();

export const verifyAnchorSchema = {
  params: verifyAnchorParamsSchema,
  returns: verifyAnchorReturnSchema,
};

/**
 * Schema for createAnchorReceipt
 */
export const createAnchorReceiptParamsSchema = z.tuple([z.string(), z.string(), z.unknown().optional(), z.unknown().optional()]);

export const createAnchorReceiptReturnSchema = z.unknown();

export const createAnchorReceiptSchema = {
  params: createAnchorReceiptParamsSchema,
  returns: createAnchorReceiptReturnSchema,
};

export default {
  anchorToChain: anchorToChainSchema,
  verifyAnchor: verifyAnchorSchema,
  createAnchorReceipt: createAnchorReceiptSchema
};
