/**
 * Auto-generated Zod schemas for proofchain.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for verifyChain
 */
export const verifyChainParamsSchema = z.tuple([z.unknown()]);

export const verifyChainReturnSchema = z.unknown();

export const verifyChainSchema = {
  params: verifyChainParamsSchema,
  returns: verifyChainReturnSchema,
};

/**
 * Schema for findTamperedReceipts
 */
export const findTamperedReceiptsParamsSchema = z.tuple([z.unknown()]);

export const findTamperedReceiptsReturnSchema = z.unknown();

export const findTamperedReceiptsSchema = {
  params: findTamperedReceiptsParamsSchema,
  returns: findTamperedReceiptsReturnSchema,
};

/**
 * Schema for reconstructChainState
 */
export const reconstructChainStateParamsSchema = z.tuple([z.unknown()]);

export const reconstructChainStateReturnSchema = z.unknown();

export const reconstructChainStateSchema = {
  params: reconstructChainStateParamsSchema,
  returns: reconstructChainStateReturnSchema,
};

export default {
  verifyChain: verifyChainSchema,
  findTamperedReceipts: findTamperedReceiptsSchema,
  reconstructChainState: reconstructChainStateSchema
};
