/**
 * Auto-generated Zod schemas for tree.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for buildMerkleTree
 */
export const buildMerkleTreeParamsSchema = z.tuple([z.unknown()]);

export const buildMerkleTreeReturnSchema = z.unknown();

export const buildMerkleTreeSchema = {
  params: buildMerkleTreeParamsSchema,
  returns: buildMerkleTreeReturnSchema,
};

/**
 * Schema for getMerkleRoot
 */
export const getMerkleRootParamsSchema = z.tuple([z.unknown()]);

export const getMerkleRootReturnSchema = z.string();

export const getMerkleRootSchema = {
  params: getMerkleRootParamsSchema,
  returns: getMerkleRootReturnSchema,
};

/**
 * Schema for getProofPath
 */
export const getProofPathParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown()]);

export const getProofPathReturnSchema = z.unknown();

export const getProofPathSchema = {
  params: getProofPathParamsSchema,
  returns: getProofPathReturnSchema,
};

/**
 * Schema for verifyInclusion
 */
export const verifyInclusionParamsSchema = z.tuple([z.string(), z.unknown(), z.unknown()]);

export const verifyInclusionReturnSchema = z.unknown();

export const verifyInclusionSchema = {
  params: verifyInclusionParamsSchema,
  returns: verifyInclusionReturnSchema,
};

/**
 * Schema for getTreeInfo
 */
export const getTreeInfoParamsSchema = z.tuple([z.unknown()]);

export const getTreeInfoReturnSchema = z.unknown();

export const getTreeInfoSchema = {
  params: getTreeInfoParamsSchema,
  returns: getTreeInfoReturnSchema,
};

export default {
  buildMerkleTree: buildMerkleTreeSchema,
  getMerkleRoot: getMerkleRootSchema,
  getProofPath: getProofPathSchema,
  verifyInclusion: verifyInclusionSchema,
  getTreeInfo: getTreeInfoSchema
};
