apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "unrdf-observability.fullname" .) "minio" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unrdf-observability.componentLabels" . | nindent 4 }}
  {{- $component := "minio" }}
spec:
  replicas: {{ .Values.minio.replicas }}
  selector:
    matchLabels:
      {{- include "unrdf-observability.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      labels:
        {{- include "unrdf-observability.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
        {{- include "unrdf-observability.podSecurityLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ printf "%s-%s" (include "unrdf-observability.fullname" .) $component }}
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $component }}
          image: "{{ .Values.minio.imageRepo }}:{{ .Values.minio.imageTag }}"
          securityContext:
            {{- toYaml (index .Values "minio" "securityContext" | default .Values.security.containerSecurityContext) | nindent 12 }}
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-minio" (include "unrdf-observability.fullname" .) }}
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-minio" (include "unrdf-observability.fullname" .) }}
                  key: MINIO_ROOT_PASSWORD
          ports:
            - name: api
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ printf "%s-minio-data" (include "unrdf-observability.fullname" .) }}
