apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "unrdf-observability.fullname" .) "promtail" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unrdf-observability.componentLabels" . | nindent 4 }}
  {{- $component := "promtail" }}
spec:
  replicas: {{ .Values.promtail.replicas }}
  selector:
    matchLabels:
      {{- include "unrdf-observability.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  template:
    metadata:
      labels:
        {{- include "unrdf-observability.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component }}
        {{- include "unrdf-observability.podSecurityLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ printf "%s-promtail" (include "unrdf-observability.fullname" .) }}
      securityContext:
        {{- toYaml .Values.security.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $component }}
          image: "{{ .Values.promtail.imageRepo }}:{{ .Values.promtail.imageTag }}"
          securityContext:
            {{- toYaml (index .Values "promtail" "securityContext" | default .Values.security.containerSecurityContext) | nindent 12 }}
          args:
            - -config.file=/etc/promtail/promtail.yaml
          ports:
            - name: http
              containerPort: 9080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: pods
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: tmp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.promtail.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /ready
              port: 9080
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 10
      volumes:
        - name: config
          configMap:
            name: {{ printf "%s-promtail" (include "unrdf-observability.fullname" .) }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: pods
          hostPath:
            path: /var/lib/docker/containers
        - name: tmp
          emptyDir:
            medium: Memory
