apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-grafana" (include "unrdf-observability.fullname" .) }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unrdf-observability.componentLabels" . | nindent 4 }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.adminPassword | quote }}
