apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "unrdf-observability.fullname" .) "grafana" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unrdf-observability.componentLabels" . | nindent 4 }}
  {{- $component := "grafana" }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30001
      protocol: TCP
  selector:
    {{- include "unrdf-observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
