apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "unrdf-observability.fullname" .) "tempo" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unrdf-observability.componentLabels" . | nindent 4 }}
  {{- $component := "tempo" }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 3200
      targetPort: 3200
      nodePort: 30200
      protocol: TCP
    - name: otlp-grpc
      port: 4319
      targetPort: 4319
      protocol: TCP
    - name: otlp-http
      port: 4320
      targetPort: 4320
      protocol: TCP
  selector:
    {{- include "unrdf-observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
