apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "unrdf-observability.fullname" .) "node-exporter" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unrdf-observability.componentLabels" . | nindent 4 }}
  {{- $component := "node-exporter" }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 9100
      targetPort: 9100
      nodePort: 30100
      protocol: TCP
  selector:
    {{- include "unrdf-observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
