apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "unrdf-observability.fullname" .) "otel-collector" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unrdf-observability.componentLabels" . | nindent 4 }}
  {{- $component := "otel-collector" }}
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: prometheus
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: health
      port: 13133
      targetPort: 13133
      protocol: TCP
    - name: metrics
      port: 8889
      targetPort: 8889
      protocol: TCP
  selector:
    {{- include "unrdf-observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
