apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "unrdf-observability.fullname" .) "loki" }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "unrdf-observability.componentLabels" . | nindent 4 }}
  {{- $component := "loki" }}
spec:
  type: NodePort
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      nodePort: 30110
      protocol: TCP
  selector:
    {{- include "unrdf-observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
