/**
 * Auto-generated Zod schemas for nunjucks-filters.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for texescape
 */
export const texescapeParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const texescapeReturnSchema = z.string();

export const texescapeSchema = {
  params: texescapeParamsSchema,
  returns: texescapeReturnSchema,
};

/**
 * Schema for bibtexkey
 */
export const bibtexkeyParamsSchema = z.tuple([z.string()]);

export const bibtexkeyReturnSchema = z.string();

export const bibtexkeySchema = {
  params: bibtexkeyParamsSchema,
  returns: bibtexkeyReturnSchema,
};

/**
 * Schema for latexjoin
 */
export const latexjoinParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const latexjoinReturnSchema = z.string();

export const latexjoinSchema = {
  params: latexjoinParamsSchema,
  returns: latexjoinReturnSchema,
};

/**
 * Schema for formatdate
 */
export const formatdateParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const formatdateReturnSchema = z.string();

export const formatdateSchema = {
  params: formatdateParamsSchema,
  returns: formatdateReturnSchema,
};

/**
 * Schema for smallcaps
 */
export const smallcapsParamsSchema = z.tuple([z.string()]);

export const smallcapsReturnSchema = z.string();

export const smallcapsSchema = {
  params: smallcapsParamsSchema,
  returns: smallcapsReturnSchema,
};

/**
 * Schema for emph
 */
export const emphParamsSchema = z.tuple([z.string()]);

export const emphReturnSchema = z.string();

export const emphSchema = {
  params: emphParamsSchema,
  returns: emphReturnSchema,
};

/**
 * Schema for bold
 */
export const boldParamsSchema = z.tuple([z.string()]);

export const boldReturnSchema = z.string();

export const boldSchema = {
  params: boldParamsSchema,
  returns: boldReturnSchema,
};

/**
 * Schema for mono
 */
export const monoParamsSchema = z.tuple([z.string()]);

export const monoReturnSchema = z.string();

export const monoSchema = {
  params: monoParamsSchema,
  returns: monoReturnSchema,
};

/**
 * Schema for cite
 */
export const citeParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const citeReturnSchema = z.string();

export const citeSchema = {
  params: citeParamsSchema,
  returns: citeReturnSchema,
};

/**
 * Schema for label
 */
export const labelParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const labelReturnSchema = z.string();

export const labelSchema = {
  params: labelParamsSchema,
  returns: labelReturnSchema,
};

/**
 * Schema for ref
 */
export const refParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const refReturnSchema = z.string();

export const refSchema = {
  params: refParamsSchema,
  returns: refReturnSchema,
};

/**
 * Schema for environment
 */
export const environmentParamsSchema = z.tuple([z.string(), z.string()]);

export const environmentReturnSchema = z.string();

export const environmentSchema = {
  params: environmentParamsSchema,
  returns: environmentReturnSchema,
};

/**
 * Schema for configureNunjucks
 */
export const configureNunjucksParamsSchema = z.tuple([z.unknown()]);

export const configureNunjucksReturnSchema = z.unknown();

export const configureNunjucksSchema = {
  params: configureNunjucksParamsSchema,
  returns: configureNunjucksReturnSchema,
};

export default {
  texescape: texescapeSchema,
  bibtexkey: bibtexkeySchema,
  latexjoin: latexjoinSchema,
  formatdate: formatdateSchema,
  smallcaps: smallcapsSchema,
  emph: emphSchema,
  bold: boldSchema,
  mono: monoSchema,
  cite: citeSchema,
  label: labelSchema,
  ref: refSchema,
  environment: environmentSchema,
  configureNunjucks: configureNunjucksSchema
};
