/**
 * Auto-generated Zod schemas for grammar.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for grammarCompileCommand
 */
export const grammarCompileCommandParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const grammarCompileCommandReturnSchema = z.unknown();

export const grammarCompileCommandSchema = {
  params: grammarCompileCommandParamsSchema,
  returns: grammarCompileCommandReturnSchema,
};

/**
 * Schema for grammarValidateCommand
 */
export const grammarValidateCommandParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const grammarValidateCommandReturnSchema = z.unknown();

export const grammarValidateCommandSchema = {
  params: grammarValidateCommandParamsSchema,
  returns: grammarValidateCommandReturnSchema,
};

/**
 * Schema for grammarComplexityCommand
 */
export const grammarComplexityCommandParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const grammarComplexityCommandReturnSchema = z.unknown();

export const grammarComplexityCommandSchema = {
  params: grammarComplexityCommandParamsSchema,
  returns: grammarComplexityCommandReturnSchema,
};

export default {
  grammarCompileCommand: grammarCompileCommandSchema,
  grammarValidateCommand: grammarValidateCommandSchema,
  grammarComplexityCommand: grammarComplexityCommandSchema
};
