/**
 * Auto-generated Zod schemas for index.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for receiptCreate
 */
export const receiptCreateParamsSchema = z.tuple([z.unknown()]);

export const receiptCreateReturnSchema = z.unknown();

export const receiptCreateSchema = {
  params: receiptCreateParamsSchema,
  returns: receiptCreateReturnSchema,
};

/**
 * Schema for receiptVerify
 */
export const receiptVerifyParamsSchema = z.tuple([z.unknown()]);

export const receiptVerifyReturnSchema = z.unknown();

export const receiptVerifySchema = {
  params: receiptVerifyParamsSchema,
  returns: receiptVerifyReturnSchema,
};

/**
 * Schema for deltaPropose
 */
export const deltaProposeParamsSchema = z.tuple([z.unknown()]);

export const deltaProposeReturnSchema = z.unknown();

export const deltaProposeSchema = {
  params: deltaProposeParamsSchema,
  returns: deltaProposeReturnSchema,
};

/**
 * Schema for deltaApply
 */
export const deltaApplyParamsSchema = z.tuple([z.unknown()]);

export const deltaApplyReturnSchema = z.unknown();

export const deltaApplySchema = {
  params: deltaApplyParamsSchema,
  returns: deltaApplyReturnSchema,
};

export default {
  receiptCreate: receiptCreateSchema,
  receiptVerify: receiptVerifySchema,
  deltaPropose: deltaProposeSchema,
  deltaApply: deltaApplySchema
};
