/**
 * Auto-generated Zod schemas for receipt.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createReceiptCommand
 */
export const createReceiptCommandParamsSchema = z.tuple([]);

export const createReceiptCommandReturnSchema = z.unknown();

export const createReceiptCommandSchema = {
  params: createReceiptCommandParamsSchema,
  returns: createReceiptCommandReturnSchema,
};

export default {
  createReceiptCommand: createReceiptCommandSchema
};
