/**
 * Auto-generated Zod schemas for thesis.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for thesisBuild
 */
export const thesisBuildParamsSchema = z.tuple([z.unknown().optional()]);

export const thesisBuildReturnSchema = z.unknown();

export const thesisBuildSchema = {
  params: thesisBuildParamsSchema,
  returns: thesisBuildReturnSchema,
};

/**
 * Schema for thesisRender
 */
export const thesisRenderParamsSchema = z.tuple([z.string()]);

export const thesisRenderReturnSchema = z.unknown();

export const thesisRenderSchema = {
  params: thesisRenderParamsSchema,
  returns: thesisRenderReturnSchema,
};

/**
 * Schema for thesisExport
 */
export const thesisExportParamsSchema = z.tuple([z.unknown().optional()]);

export const thesisExportReturnSchema = z.unknown();

export const thesisExportSchema = {
  params: thesisExportParamsSchema,
  returns: thesisExportReturnSchema,
};

export default {
  thesisBuild: thesisBuildSchema,
  thesisRender: thesisRenderSchema,
  thesisExport: thesisExportSchema
};
