/**
 * Auto-generated Zod schemas for merkle-root.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for computeMerkleRoot
 */
export const computeMerkleRootParamsSchema = z.tuple([z.unknown()]);

export const computeMerkleRootReturnSchema = z.unknown();

export const computeMerkleRootSchema = {
  params: computeMerkleRootParamsSchema,
  returns: computeMerkleRootReturnSchema,
};

/**
 * Schema for generateMerkleProof
 */
export const generateMerkleProofParamsSchema = z.tuple([z.unknown(), z.number()]);

export const generateMerkleProofReturnSchema = z.unknown();

export const generateMerkleProofSchema = {
  params: generateMerkleProofParamsSchema,
  returns: generateMerkleProofReturnSchema,
};

/**
 * Schema for verifyMerkleProof
 */
export const verifyMerkleProofParamsSchema = z.tuple([z.string(), z.string(), z.unknown()]);

export const verifyMerkleProofReturnSchema = z.unknown();

export const verifyMerkleProofSchema = {
  params: verifyMerkleProofParamsSchema,
  returns: verifyMerkleProofReturnSchema,
};

/**
 * Schema for batchReceipts
 */
export const batchReceiptsParamsSchema = z.tuple([z.unknown()]);

export const batchReceiptsReturnSchema = z.unknown();

export const batchReceiptsSchema = {
  params: batchReceiptsParamsSchema,
  returns: batchReceiptsReturnSchema,
};

export default {
  computeMerkleRoot: computeMerkleRootSchema,
  generateMerkleProof: generateMerkleProofSchema,
  verifyMerkleProof: verifyMerkleProofSchema,
  batchReceipts: batchReceiptsSchema
};
