/**
 * Auto-generated Zod schemas for receipt-indexer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createIndexer
 */
export const createIndexerParamsSchema = z.tuple([z.unknown()]);

export const createIndexerReturnSchema = z.unknown();

export const createIndexerSchema = {
  params: createIndexerParamsSchema,
  returns: createIndexerReturnSchema,
};

export default {
  createIndexer: createIndexerSchema
};
