/**
 * Auto-generated Zod schemas for receipt-ledger.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createMemoryLedger
 */
export const createMemoryLedgerParamsSchema = z.tuple([]);

export const createMemoryLedgerReturnSchema = z.unknown();

export const createMemoryLedgerSchema = {
  params: createMemoryLedgerParamsSchema,
  returns: createMemoryLedgerReturnSchema,
};

/**
 * Schema for createFileLedger
 */
export const createFileLedgerParamsSchema = z.tuple([z.string()]);

export const createFileLedgerReturnSchema = z.unknown();

export const createFileLedgerSchema = {
  params: createFileLedgerParamsSchema,
  returns: createFileLedgerReturnSchema,
};

/**
 * Schema for createChainSnapshot
 */
export const createChainSnapshotParamsSchema = z.tuple([z.unknown(), z.string()]);

export const createChainSnapshotReturnSchema = z.unknown();

export const createChainSnapshotSchema = {
  params: createChainSnapshotParamsSchema,
  returns: createChainSnapshotReturnSchema,
};

/**
 * Schema for verifyChainSnapshot
 */
export const verifyChainSnapshotParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const verifyChainSnapshotReturnSchema = z.unknown();

export const verifyChainSnapshotSchema = {
  params: verifyChainSnapshotParamsSchema,
  returns: verifyChainSnapshotReturnSchema,
};

export default {
  createMemoryLedger: createMemoryLedgerSchema,
  createFileLedger: createFileLedgerSchema,
  createChainSnapshot: createChainSnapshotSchema,
  verifyChainSnapshot: verifyChainSnapshotSchema
};
