/**
 * Auto-generated Zod schemas for monorepo-universe.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for buildPartitionMap
 */
export const buildPartitionMapParamsSchema = z.tuple([]);

export const buildPartitionMapReturnSchema = z.unknown();

export const buildPartitionMapSchema = {
  params: buildPartitionMapParamsSchema,
  returns: buildPartitionMapReturnSchema,
};

/**
 * Schema for getPartitionByName
 */
export const getPartitionByNameParamsSchema = z.tuple([z.string()]);

export const getPartitionByNameReturnSchema = z.unknown();

export const getPartitionByNameSchema = {
  params: getPartitionByNameParamsSchema,
  returns: getPartitionByNameReturnSchema,
};

/**
 * Schema for getPackagePartition
 */
export const getPackagePartitionParamsSchema = z.tuple([z.string()]);

export const getPackagePartitionReturnSchema = z.unknown();

export const getPackagePartitionSchema = {
  params: getPackagePartitionParamsSchema,
  returns: getPackagePartitionReturnSchema,
};

/**
 * Schema for isDependencyAllowed
 */
export const isDependencyAllowedParamsSchema = z.tuple([z.string(), z.string()]);

export const isDependencyAllowedReturnSchema = z.boolean();

export const isDependencyAllowedSchema = {
  params: isDependencyAllowedParamsSchema,
  returns: isDependencyAllowedReturnSchema,
};

/**
 * Schema for createMonorepoUniverse
 */
export const createMonorepoUniverseParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const createMonorepoUniverseReturnSchema = z.unknown();

export const createMonorepoUniverseSchema = {
  params: createMonorepoUniverseParamsSchema,
  returns: createMonorepoUniverseReturnSchema,
};

/**
 * Schema for loadCurrentUniverse
 */
export const loadCurrentUniverseParamsSchema = z.tuple([z.unknown().optional()]);

export const loadCurrentUniverseReturnSchema = z.unknown();

export const loadCurrentUniverseSchema = {
  params: loadCurrentUniverseParamsSchema,
  returns: loadCurrentUniverseReturnSchema,
};

export default {
  buildPartitionMap: buildPartitionMapSchema,
  getPartitionByName: getPartitionByNameSchema,
  getPackagePartition: getPackagePartitionSchema,
  isDependencyAllowed: isDependencyAllowedSchema,
  createMonorepoUniverse: createMonorepoUniverseSchema,
  loadCurrentUniverse: loadCurrentUniverseSchema
};
