/**
 * Auto-generated Zod schemas for monorepo-queries.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for buildPackageQuery
 */
export const buildPackageQueryParamsSchema = z.tuple([z.unknown().optional()]);

export const buildPackageQueryReturnSchema = z.string();

export const buildPackageQuerySchema = {
  params: buildPackageQueryParamsSchema,
  returns: buildPackageQueryReturnSchema,
};

/**
 * Schema for buildDependencyPathQuery
 */
export const buildDependencyPathQueryParamsSchema = z.tuple([z.string(), z.string()]);

export const buildDependencyPathQueryReturnSchema = z.string();

export const buildDependencyPathQuerySchema = {
  params: buildDependencyPathQueryParamsSchema,
  returns: buildDependencyPathQueryReturnSchema,
};

/**
 * Schema for buildImpactAnalysisQuery
 */
export const buildImpactAnalysisQueryParamsSchema = z.tuple([z.string()]);

export const buildImpactAnalysisQueryReturnSchema = z.string();

export const buildImpactAnalysisQuerySchema = {
  params: buildImpactAnalysisQueryParamsSchema,
  returns: buildImpactAnalysisQueryReturnSchema,
};

/**
 * Schema for formatResults
 */
export const formatResultsParamsSchema = z.tuple([z.unknown()]);

export const formatResultsReturnSchema = z.unknown();

export const formatResultsSchema = {
  params: formatResultsParamsSchema,
  returns: formatResultsReturnSchema,
};

/**
 * Schema for formatAsTable
 */
export const formatAsTableParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const formatAsTableReturnSchema = z.string();

export const formatAsTableSchema = {
  params: formatAsTableParamsSchema,
  returns: formatAsTableReturnSchema,
};

/**
 * Schema for formatAsCsv
 */
export const formatAsCsvParamsSchema = z.tuple([z.unknown()]);

export const formatAsCsvReturnSchema = z.string();

export const formatAsCsvSchema = {
  params: formatAsCsvParamsSchema,
  returns: formatAsCsvReturnSchema,
};

/**
 * Schema for formatAsJson
 */
export const formatAsJsonParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const formatAsJsonReturnSchema = z.string();

export const formatAsJsonSchema = {
  params: formatAsJsonParamsSchema,
  returns: formatAsJsonReturnSchema,
};

/**
 * Schema for executeQuery
 */
export const executeQueryParamsSchema = z.tuple([z.unknown(), z.string(), z.unknown().optional()]);

export const executeQueryReturnSchema = z.unknown();

export const executeQuerySchema = {
  params: executeQueryParamsSchema,
  returns: executeQueryReturnSchema,
};

/**
 * Schema for batchExecuteQueries
 */
export const batchExecuteQueriesParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const batchExecuteQueriesReturnSchema = z.unknown();

export const batchExecuteQueriesSchema = {
  params: batchExecuteQueriesParamsSchema,
  returns: batchExecuteQueriesReturnSchema,
};

/**
 * Schema for analyzeDependencyHealth
 */
export const analyzeDependencyHealthParamsSchema = z.tuple([z.unknown()]);

export const analyzeDependencyHealthReturnSchema = z.unknown();

export const analyzeDependencyHealthSchema = {
  params: analyzeDependencyHealthParamsSchema,
  returns: analyzeDependencyHealthReturnSchema,
};

/**
 * Schema for generatePackageReport
 */
export const generatePackageReportParamsSchema = z.tuple([z.unknown(), z.string()]);

export const generatePackageReportReturnSchema = z.unknown();

export const generatePackageReportSchema = {
  params: generatePackageReportParamsSchema,
  returns: generatePackageReportReturnSchema,
};

export default {
  buildPackageQuery: buildPackageQuerySchema,
  buildDependencyPathQuery: buildDependencyPathQuerySchema,
  buildImpactAnalysisQuery: buildImpactAnalysisQuerySchema,
  formatResults: formatResultsSchema,
  formatAsTable: formatAsTableSchema,
  formatAsCsv: formatAsCsvSchema,
  formatAsJson: formatAsJsonSchema,
  executeQuery: executeQuerySchema,
  batchExecuteQueries: batchExecuteQueriesSchema,
  analyzeDependencyHealth: analyzeDependencyHealthSchema,
  generatePackageReport: generatePackageReportSchema
};
