/**
 * Auto-generated Zod schemas for package-rdf-model.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for pkg
 */
export const pkgParamsSchema = z.tuple([z.string()]);

export const pkgReturnSchema = z.unknown();

export const pkgSchema = {
  params: pkgParamsSchema,
  returns: pkgReturnSchema,
};

/**
 * Schema for dep
 */
export const depParamsSchema = z.tuple([z.string()]);

export const depReturnSchema = z.unknown();

export const depSchema = {
  params: depParamsSchema,
  returns: depReturnSchema,
};

/**
 * Schema for mod
 */
export const modParamsSchema = z.tuple([z.string()]);

export const modReturnSchema = z.unknown();

export const modSchema = {
  params: modParamsSchema,
  returns: modReturnSchema,
};

/**
 * Schema for rdf
 */
export const rdfParamsSchema = z.tuple([z.string()]);

export const rdfReturnSchema = z.unknown();

export const rdfSchema = {
  params: rdfParamsSchema,
  returns: rdfReturnSchema,
};

/**
 * Schema for rdfs
 */
export const rdfsParamsSchema = z.tuple([z.string()]);

export const rdfsReturnSchema = z.unknown();

export const rdfsSchema = {
  params: rdfsParamsSchema,
  returns: rdfsReturnSchema,
};

/**
 * Schema for xsd
 */
export const xsdParamsSchema = z.tuple([z.string()]);

export const xsdReturnSchema = z.unknown();

export const xsdSchema = {
  params: xsdParamsSchema,
  returns: xsdReturnSchema,
};

/**
 * Schema for packageToIri
 */
export const packageToIriParamsSchema = z.tuple([z.string()]);

export const packageToIriReturnSchema = z.unknown();

export const packageToIriSchema = {
  params: packageToIriParamsSchema,
  returns: packageToIriReturnSchema,
};

/**
 * Schema for dependencyToIri
 */
export const dependencyToIriParamsSchema = z.tuple([z.string(), z.string()]);

export const dependencyToIriReturnSchema = z.unknown();

export const dependencyToIriSchema = {
  params: dependencyToIriParamsSchema,
  returns: dependencyToIriReturnSchema,
};

/**
 * Schema for exportToIri
 */
export const exportToIriParamsSchema = z.tuple([z.string(), z.string()]);

export const exportToIriReturnSchema = z.unknown();

export const exportToIriSchema = {
  params: exportToIriParamsSchema,
  returns: exportToIriReturnSchema,
};

/**
 * Schema for scriptToIri
 */
export const scriptToIriParamsSchema = z.tuple([z.string(), z.string()]);

export const scriptToIriReturnSchema = z.unknown();

export const scriptToIriSchema = {
  params: scriptToIriParamsSchema,
  returns: scriptToIriReturnSchema,
};

/**
 * Schema for parsePackageToQuads
 */
export const parsePackageToQuadsParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const parsePackageToQuadsReturnSchema = z.unknown();

export const parsePackageToQuadsSchema = {
  params: parsePackageToQuadsParamsSchema,
  returns: parsePackageToQuadsReturnSchema,
};

/**
 * Schema for loadPackageJsonToQuads
 */
export const loadPackageJsonToQuadsParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const loadPackageJsonToQuadsReturnSchema = z.unknown();

export const loadPackageJsonToQuadsSchema = {
  params: loadPackageJsonToQuadsParamsSchema,
  returns: loadPackageJsonToQuadsReturnSchema,
};

/**
 * Schema for createPackageStore
 */
export const createPackageStoreParamsSchema = z.tuple([z.unknown(), z.unknown().optional()]);

export const createPackageStoreReturnSchema = z.unknown();

export const createPackageStoreSchema = {
  params: createPackageStoreParamsSchema,
  returns: createPackageStoreReturnSchema,
};

/**
 * Schema for addPartitionSchema
 */
export const addPartitionSchemaParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const addPartitionSchemaReturnSchema = z.unknown();

export const addPartitionSchemaSchema = {
  params: addPartitionSchemaParamsSchema,
  returns: addPartitionSchemaReturnSchema,
};

/**
 * Schema for validatePackageJson
 */
export const validatePackageJsonParamsSchema = z.tuple([z.unknown()]);

export const validatePackageJsonReturnSchema = z.unknown();

export const validatePackageJsonSchema = {
  params: validatePackageJsonParamsSchema,
  returns: validatePackageJsonReturnSchema,
};

/**
 * Schema for validateWorkspaceDependencies
 */
export const validateWorkspaceDependenciesParamsSchema = z.tuple([z.unknown()]);

export const validateWorkspaceDependenciesReturnSchema = z.unknown();

export const validateWorkspaceDependenciesSchema = {
  params: validateWorkspaceDependenciesParamsSchema,
  returns: validateWorkspaceDependenciesReturnSchema,
};

export default {
  pkg: pkgSchema,
  dep: depSchema,
  mod: modSchema,
  rdf: rdfSchema,
  rdfs: rdfsSchema,
  xsd: xsdSchema,
  packageToIri: packageToIriSchema,
  dependencyToIri: dependencyToIriSchema,
  exportToIri: exportToIriSchema,
  scriptToIri: scriptToIriSchema,
  parsePackageToQuads: parsePackageToQuadsSchema,
  loadPackageJsonToQuads: loadPackageJsonToQuadsSchema,
  createPackageStore: createPackageStoreSchema,
  addPartitionSchema: addPartitionSchemaSchema,
  validatePackageJson: validatePackageJsonSchema,
  validateWorkspaceDependencies: validateWorkspaceDependenciesSchema
};
