/**
 * Auto-generated Zod schemas for rdf-utils.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateIri
 */
export const validateIriParamsSchema = z.tuple([z.string()]);

export const validateIriReturnSchema = z.boolean();

export const validateIriSchema = {
  params: validateIriParamsSchema,
  returns: validateIriReturnSchema,
};

/**
 * Schema for loadTurtle
 */
export const loadTurtleParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const loadTurtleReturnSchema = z.unknown();

export const loadTurtleSchema = {
  params: loadTurtleParamsSchema,
  returns: loadTurtleReturnSchema,
};

/**
 * Schema for parseQuads
 */
export const parseQuadsParamsSchema = z.tuple([z.string(), z.unknown().optional()]);

export const parseQuadsReturnSchema = z.unknown();

export const parseQuadsSchema = {
  params: parseQuadsParamsSchema,
  returns: parseQuadsReturnSchema,
};

/**
 * Schema for canonicalizeQuads
 */
export const canonicalizeQuadsParamsSchema = z.tuple([z.unknown()]);

export const canonicalizeQuadsReturnSchema = z.unknown();

export const canonicalizeQuadsSchema = {
  params: canonicalizeQuadsParamsSchema,
  returns: canonicalizeQuadsReturnSchema,
};

/**
 * Schema for serializeQuadsToNTriples
 */
export const serializeQuadsToNTriplesParamsSchema = z.tuple([z.unknown()]);

export const serializeQuadsToNTriplesReturnSchema = z.string();

export const serializeQuadsToNTriplesSchema = {
  params: serializeQuadsToNTriplesParamsSchema,
  returns: serializeQuadsToNTriplesReturnSchema,
};

/**
 * Schema for computeContentHash
 */
export const computeContentHashParamsSchema = z.tuple([z.unknown()]);

export const computeContentHashReturnSchema = z.unknown();

export const computeContentHashSchema = {
  params: computeContentHashParamsSchema,
  returns: computeContentHashReturnSchema,
};

/**
 * Schema for hashString
 */
export const hashStringParamsSchema = z.tuple([z.string()]);

export const hashStringReturnSchema = z.unknown();

export const hashStringSchema = {
  params: hashStringParamsSchema,
  returns: hashStringReturnSchema,
};

/**
 * Schema for extractNamespaces
 */
export const extractNamespacesParamsSchema = z.tuple([z.unknown()]);

export const extractNamespacesReturnSchema = z.unknown();

export const extractNamespacesSchema = {
  params: extractNamespacesParamsSchema,
  returns: extractNamespacesReturnSchema,
};

/**
 * Schema for extractNamespaceFromIri
 */
export const extractNamespaceFromIriParamsSchema = z.tuple([z.string()]);

export const extractNamespaceFromIriReturnSchema = z.string();

export const extractNamespaceFromIriSchema = {
  params: extractNamespaceFromIriParamsSchema,
  returns: extractNamespaceFromIriReturnSchema,
};

/**
 * Schema for mergeStores
 */
export const mergeStoresParamsSchema = z.tuple([z.unknown()]);

export const mergeStoresReturnSchema = z.unknown();

export const mergeStoresSchema = {
  params: mergeStoresParamsSchema,
  returns: mergeStoresReturnSchema,
};

export default {
  validateIri: validateIriSchema,
  loadTurtle: loadTurtleSchema,
  parseQuads: parseQuadsSchema,
  canonicalizeQuads: canonicalizeQuadsSchema,
  serializeQuadsToNTriples: serializeQuadsToNTriplesSchema,
  computeContentHash: computeContentHashSchema,
  hashString: hashStringSchema,
  extractNamespaces: extractNamespacesSchema,
  extractNamespaceFromIri: extractNamespaceFromIriSchema,
  mergeStores: mergeStoresSchema
};
