/**
 * Auto-generated Zod schemas for anomaly-detector.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createAnomalyDetector
 */
export const createAnomalyDetectorParamsSchema = z.tuple([z.unknown().optional()]);

export const createAnomalyDetectorReturnSchema = z.unknown();

export const createAnomalyDetectorSchema = {
  params: createAnomalyDetectorParamsSchema,
  returns: createAnomalyDetectorReturnSchema,
};

export default {
  createAnomalyDetector: createAnomalyDetectorSchema
};
