/**
 * Auto-generated Zod schemas for embeddings-manager.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createEmbeddingsManager
 */
export const createEmbeddingsManagerParamsSchema = z.tuple([z.unknown().optional()]);

export const createEmbeddingsManagerReturnSchema = z.unknown();

export const createEmbeddingsManagerSchema = {
  params: createEmbeddingsManagerParamsSchema,
  returns: createEmbeddingsManagerReturnSchema,
};

export default {
  createEmbeddingsManager: createEmbeddingsManagerSchema
};
