/**
 * Auto-generated Zod schemas for nlp-query-builder.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createNLPQueryBuilder
 */
export const createNLPQueryBuilderParamsSchema = z.tuple([z.unknown().optional()]);

export const createNLPQueryBuilderReturnSchema = z.unknown();

export const createNLPQueryBuilderSchema = {
  params: createNLPQueryBuilderParamsSchema,
  returns: createNLPQueryBuilderReturnSchema,
};

export default {
  createNLPQueryBuilder: createNLPQueryBuilderSchema
};
