/**
 * Auto-generated Zod schemas for semantic-analyzer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createSemanticAnalyzer
 */
export const createSemanticAnalyzerParamsSchema = z.tuple([z.unknown().optional()]);

export const createSemanticAnalyzerReturnSchema = z.unknown();

export const createSemanticAnalyzerSchema = {
  params: createSemanticAnalyzerParamsSchema,
  returns: createSemanticAnalyzerReturnSchema,
};

export default {
  createSemanticAnalyzer: createSemanticAnalyzerSchema
};
