/**
 * Auto-generated Zod schemas for use-graph-visualizer.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useGraphVisualizer
 */
export const useGraphVisualizerParamsSchema = z.tuple([z.unknown().optional()]);

export const useGraphVisualizerReturnSchema = z.unknown();

export const useGraphVisualizerSchema = {
  params: useGraphVisualizerParamsSchema,
  returns: useGraphVisualizerReturnSchema,
};

export default {
  useGraphVisualizer: useGraphVisualizerSchema
};
