/**
 * Auto-generated Zod schemas for use-sparql-editor.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useSPARQLEditor
 */
export const useSPARQLEditorParamsSchema = z.tuple([z.unknown().optional()]);

export const useSPARQLEditorReturnSchema = z.unknown();

export const useSPARQLEditorSchema = {
  params: useSPARQLEditorParamsSchema,
  returns: useSPARQLEditorReturnSchema,
};

export default {
  useSPARQLEditor: useSPARQLEditorSchema
};
