/**
 * Auto-generated Zod schemas for use-query-builder.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useQueryBuilder
 */
export const useQueryBuilderParamsSchema = z.tuple([z.unknown().optional()]);

export const useQueryBuilderReturnSchema = z.unknown();

export const useQueryBuilderSchema = {
  params: useQueryBuilderParamsSchema,
  returns: useQueryBuilderReturnSchema,
};

export default {
  useQueryBuilder: useQueryBuilderSchema
};
