name: Deploy mdBook to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install Rust (for mdBook)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/book.toml') }}

      - name: Install mdBook
        run: |
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          if ! command -v mdbook >/dev/null 2>&1; then
            cargo install mdbook --version 0.4.37
          fi
          mdbook --version

      - name: Build book to _site
        run: mdbook build book -d _site

      - name: Inspect build output
        run: |
          ls -la
          ls -la _site || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
