/**
 * Auto-generated Zod schemas for useGammaChecker.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useGammaChecker
 */
export const useGammaCheckerParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional(), z.unknown().optional()]);

export const useGammaCheckerReturnSchema = z.unknown();

export const useGammaCheckerSchema = {
  params: useGammaCheckerParamsSchema,
  returns: useGammaCheckerReturnSchema,
};

export default {
  useGammaChecker: useGammaCheckerSchema
};
