/**
 * Auto-generated Zod schemas for useHTFOntology.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useHTFOntology
 */
export const useHTFOntologyParamsSchema = z.tuple([]);

export const useHTFOntologyReturnSchema = z.unknown();

export const useHTFOntologySchema = {
  params: useHTFOntologyParamsSchema,
  returns: useHTFOntologyReturnSchema,
};

export default {
  useHTFOntology: useHTFOntologySchema
};
