/**
 * Auto-generated Zod schemas for useLambdaScheduling.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useLambdaScheduling
 */
export const useLambdaSchedulingParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional()]);

export const useLambdaSchedulingReturnSchema = z.unknown();

export const useLambdaSchedulingSchema = {
  params: useLambdaSchedulingParamsSchema,
  returns: useLambdaSchedulingReturnSchema,
};

export default {
  useLambdaScheduling: useLambdaSchedulingSchema
};
