/**
 * Auto-generated Zod schemas for usePiProfile.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for usePiProfile
 */
export const usePiProfileParamsSchema = z.tuple([z.unknown().optional(), z.boolean().optional()]);

export const usePiProfileReturnSchema = z.unknown();

export const usePiProfileSchema = {
  params: usePiProfileParamsSchema,
  returns: usePiProfileReturnSchema,
};

export default {
  usePiProfile: usePiProfileSchema
};
