/**
 * Auto-generated Zod schemas for useQInvariants.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for useQInvariants
 */
export const useQInvariantsParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional()]);

export const useQInvariantsReturnSchema = z.unknown();

export const useQInvariantsSchema = {
  params: useQInvariantsParamsSchema,
  returns: useQInvariantsReturnSchema,
};

export default {
  useQInvariants: useQInvariantsSchema
};
