/**
 * Auto-generated Zod schemas for nouns.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateNouns
 */
export const validateNounsParamsSchema = z.tuple([]);

export const validateNounsReturnSchema = z.unknown();

export const validateNounsSchema = {
  params: validateNounsParamsSchema,
  returns: validateNounsReturnSchema,
};

/**
 * Schema for getNoun
 */
export const getNounParamsSchema = z.tuple([z.string()]);

export const getNounReturnSchema = z.unknown();

export const getNounSchema = {
  params: getNounParamsSchema,
  returns: getNounReturnSchema,
};

/**
 * Schema for getNounNames
 */
export const getNounNamesParamsSchema = z.tuple([]);

export const getNounNamesReturnSchema = z.unknown();

export const getNounNamesSchema = {
  params: getNounNamesParamsSchema,
  returns: getNounNamesReturnSchema,
};

/**
 * Schema for buildNounPackageMap
 */
export const buildNounPackageMapParamsSchema = z.tuple([]);

export const buildNounPackageMapReturnSchema = z.unknown();

export const buildNounPackageMapSchema = {
  params: buildNounPackageMapParamsSchema,
  returns: buildNounPackageMapReturnSchema,
};

export default {
  validateNouns: validateNounsSchema,
  getNoun: getNounSchema,
  getNounNames: getNounNamesSchema,
  buildNounPackageMap: buildNounPackageMapSchema
};
