/**
 * Auto-generated Zod schemas for spine.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for buildV6Spine
 */
export const buildV6SpineParamsSchema = z.tuple([z.unknown()]);

export const buildV6SpineReturnSchema = z.unknown();

export const buildV6SpineSchema = {
  params: buildV6SpineParamsSchema,
  returns: buildV6SpineReturnSchema,
};

/**
 * Schema for generateSpineReport
 */
export const generateSpineReportParamsSchema = z.tuple([z.unknown()]);

export const generateSpineReportReturnSchema = z.string();

export const generateSpineReportSchema = {
  params: generateSpineReportParamsSchema,
  returns: generateSpineReportReturnSchema,
};

/**
 * Schema for getNounVerbMatrix
 */
export const getNounVerbMatrixParamsSchema = z.tuple([]);

export const getNounVerbMatrixReturnSchema = z.unknown();

export const getNounVerbMatrixSchema = {
  params: getNounVerbMatrixParamsSchema,
  returns: getNounVerbMatrixReturnSchema,
};

/**
 * Schema for wrapWithReceiptValidation
 */
export const wrapWithReceiptValidationParamsSchema = z.tuple([z.string(), z.string(), z.unknown()]);

export const wrapWithReceiptValidationReturnSchema = z.unknown();

export const wrapWithReceiptValidationSchema = {
  params: wrapWithReceiptValidationParamsSchema,
  returns: wrapWithReceiptValidationReturnSchema,
};

/**
 * Schema for createV6Extension
 */
export const createV6ExtensionParamsSchema = z.tuple([z.unknown(), z.unknown()]);

export const createV6ExtensionReturnSchema = z.unknown();

export const createV6ExtensionSchema = {
  params: createV6ExtensionParamsSchema,
  returns: createV6ExtensionReturnSchema,
};

export default {
  buildV6Spine: buildV6SpineSchema,
  generateSpineReport: generateSpineReportSchema,
  getNounVerbMatrix: getNounVerbMatrixSchema,
  wrapWithReceiptValidation: wrapWithReceiptValidationSchema,
  createV6Extension: createV6ExtensionSchema
};
