/**
 * Auto-generated Zod schemas for verbs.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for validateVerbs
 */
export const validateVerbsParamsSchema = z.tuple([]);

export const validateVerbsReturnSchema = z.unknown();

export const validateVerbsSchema = {
  params: validateVerbsParamsSchema,
  returns: validateVerbsReturnSchema,
};

/**
 * Schema for getVerb
 */
export const getVerbParamsSchema = z.tuple([z.string()]);

export const getVerbReturnSchema = z.unknown();

export const getVerbSchema = {
  params: getVerbParamsSchema,
  returns: getVerbReturnSchema,
};

/**
 * Schema for getVerbsForNoun
 */
export const getVerbsForNounParamsSchema = z.tuple([z.string()]);

export const getVerbsForNounReturnSchema = z.unknown();

export const getVerbsForNounSchema = {
  params: getVerbsForNounParamsSchema,
  returns: getVerbsForNounReturnSchema,
};

/**
 * Schema for buildNounVerbMatrix
 */
export const buildNounVerbMatrixParamsSchema = z.tuple([]);

export const buildNounVerbMatrixReturnSchema = z.unknown();

export const buildNounVerbMatrixSchema = {
  params: buildNounVerbMatrixParamsSchema,
  returns: buildNounVerbMatrixReturnSchema,
};

/**
 * Schema for isValidCombination
 */
export const isValidCombinationParamsSchema = z.tuple([z.string(), z.string()]);

export const isValidCombinationReturnSchema = z.boolean();

export const isValidCombinationSchema = {
  params: isValidCombinationParamsSchema,
  returns: isValidCombinationReturnSchema,
};

export default {
  validateVerbs: validateVerbsSchema,
  getVerb: getVerbSchema,
  getVerbsForNoun: getVerbsForNounSchema,
  buildNounVerbMatrix: buildNounVerbMatrixSchema,
  isValidCombination: isValidCombinationSchema
};
