/**
 * Auto-generated Zod schemas for adaptive-monitor.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createAdaptiveMonitor
 */
export const createAdaptiveMonitorParamsSchema = z.tuple([z.unknown().optional()]);

export const createAdaptiveMonitorReturnSchema = z.unknown();

export const createAdaptiveMonitorSchema = {
  params: createAdaptiveMonitorParamsSchema,
  returns: createAdaptiveMonitorReturnSchema,
};

/**
 * Schema for createMemoryMonitor
 */
export const createMemoryMonitorParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional()]);

export const createMemoryMonitorReturnSchema = z.unknown();

export const createMemoryMonitorSchema = {
  params: createMemoryMonitorParamsSchema,
  returns: createMemoryMonitorReturnSchema,
};

/**
 * Schema for createEventLoopMonitor
 */
export const createEventLoopMonitorParamsSchema = z.tuple([z.unknown().optional(), z.unknown().optional()]);

export const createEventLoopMonitorReturnSchema = z.unknown();

export const createEventLoopMonitorSchema = {
  params: createEventLoopMonitorParamsSchema,
  returns: createEventLoopMonitorReturnSchema,
};

/**
 * Schema for createMonitorOrchestrator
 */
export const createMonitorOrchestratorParamsSchema = z.tuple([]);

export const createMonitorOrchestratorReturnSchema = z.unknown();

export const createMonitorOrchestratorSchema = {
  params: createMonitorOrchestratorParamsSchema,
  returns: createMonitorOrchestratorReturnSchema,
};

export default {
  createAdaptiveMonitor: createAdaptiveMonitorSchema,
  createMemoryMonitor: createMemoryMonitorSchema,
  createEventLoopMonitor: createEventLoopMonitorSchema,
  createMonitorOrchestrator: createMonitorOrchestratorSchema
};
