/**
 * Auto-generated Zod schemas for memory-manager.mjs
 *
 * Generated by @unrdf/v6-compat/schema-generator
 *
 * DO NOT EDIT MANUALLY
 */

import { z } from 'zod';

/**
 * Schema for createMemoryManager
 */
export const createMemoryManagerParamsSchema = z.tuple([z.unknown().optional()]);

export const createMemoryManagerReturnSchema = z.unknown();

export const createMemoryManagerSchema = {
  params: createMemoryManagerParamsSchema,
  returns: createMemoryManagerReturnSchema,
};

/**
 * Schema for createConnectionPool
 */
export const createConnectionPoolParamsSchema = z.tuple([z.unknown().optional()]);

export const createConnectionPoolReturnSchema = z.unknown();

export const createConnectionPoolSchema = {
  params: createConnectionPoolParamsSchema,
  returns: createConnectionPoolReturnSchema,
};

export default {
  createMemoryManager: createMemoryManagerSchema,
  createConnectionPool: createConnectionPoolSchema
};
